Epix-Incorporated/Adonis

- Server/Dependencies/Assets/Fr0g.lua
It uses an invalid asset id for the fr0g's texture, causing both an error to request and failing to render a frame.
> Update fr0g to fix an issue

- Server/Core/Admin.lua
Actually allows panic mode to give moderators panic commands
Is a simple fix
> Fix PanicMode permission checking

- Client/Dependencies/Credits.lua
- Server/Core/Commands.lua
> fixed typo

- Loader/Config/API.lua
> Add some more subtables to API doc

- Server/Core/Commands.lua
:trelloban --- CHECKS FOR TRELLO CONFIG BEFORE ATTEMPTING TO RUN.
~~:trelloupdate --- Updates the Adonis lists (Admin, bans, mutes, music, etc...) from Trello.~~
> Add :trelloban

- Server/Core/Commands.lua
Remove deprecated hopperbin comment lines
Use provided Handle in F3X Deps folder
Rename F3X to the default name Building Tools
> Update Building Tools Command

- Server/Core/Commands.lua
- Server/Core/Service.lua
Changed "Server Banned" to "Game banned"
Modified insert func
> Corrected misleading GameBan hint & resolved possible mem leak (check commits for descriptions)

- Server/Core/Commands.lua
- Server/Dependencies/Assets/Fly.lua
I removed pretty much all of the flynoclip code and implemented noclip into the original fly script for easy editing. This also lets you choose a speed for flynoclip.
> Revamped flynoclip

- Server/Core/Admin.lua
Unban issue that causes to :lower() on a number and not a string
> Fix unban issue

- Server/Core/Commands.lua
This is an issue I have seen before, and I have before where you cannot take a player off of a team after putting them on a team
> Add :unteam

- MainModule/Server/Core/Commands.lua
:abort all has a mistake in it preventing it from working
> Fix abort all

- MainModule/Server/Core/Core.lua
- Fixed MakeEvent function
`Needed to add "Core.RemoteEvent.FuncSec:Disconnect()"` in line 85 to prevent further spams from RemoteFunction's security
> Fixed MakeEvent Function in Core.lua

- MainModule/Client/Dependencies/UI/Default/List.lua
Will fix locallog, serverlog, and scriptlog color not showing.
> Add Color property to List

- MainModule/Server/Core/Commands.lua
- A command allowing the player to join their friend's ongoing server.
> + Add globaljoin command

- MainModule/Server/Core/Commands.lua
- Fixed the size command (now supports R6) (extract source from [Character Scaling (R6 and R15)](https://www.roblox.com/library/1239655916/Character-Scaling-R6-and-R15) by _hunxrepair_)
> Changelog: 196 (Fixed the size command)

- MainModule/Server/Core/Commands.lua
- MainModule/Server/Dependencies/Assets/Clipper.lua
- **:noclip** - Allows player to turn without using shiftlock, also now clips through unanchored parts that the client owns
- **:shirt/:pants/!shirt/!pants** - Now uses InsertService and removes the use of the rather inefficient GetTexture function
- **:alert** - Makes the text argument optional (as it was intended to be originally)
- **:cameras** - Fixes command and displays list of cameras made with :camera 
- **:flatten** - R15 support
- **:size** - Fixes R6 support that was added in #155 
- **:unchar** - Switched to refresh instead of respawn
> Various command fixes and improvements

- MainModule/Server/Core/Commands.lua
- Fixed ``dog`` command
_There was an issue with dog command turning players shirtless and pantsless. Also, I've made a few adjustments with it and extracted Kohl Admin's ``dog`` command to merge with Adonis. _
> Fixed dog command

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Server.lua
This will add a "Player" property to the addlog function.
> Add Player Property to Logs

- MainModule/Server/Core/Commands.lua
- Added **cleareffects** command (Inspired by an [issue)](https://github.com/Sceleratis/Adonis/issues/193)
> Added command "cleareffects"

- MainModule/Server/Core/Commands.lua
As title says, I don't know if anything should be changed to conform to guidelines or something.
> ToolList now works with special prefixes

- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Functions.lua
I updated the commands so you can also use the id of the image asset for clothing.
> Updated shirt, pants, donor pants and donor shirt

- MainModule/Server/Core/Commands.lua
**Keynotes:**
- Improved the command by 80% better
- If specific players have no character nor humanoid, they will be refreshed as a specific player or themselves.
- The command doesn't refresh you while morphing to somebody else
> Improved the character and uncharacter command

- MainModule/Server/Core/Commands.lua
- Added R6 and R15 Commands
P.S. I also fixed a typo while I was adding the two new commands :D
> Added R6 and R15 Commands

- MainModule/Server/Core/Commands.lua
This would allow the pitch/volume to be changed by increments. 
For example, :pitch +1 would increase the pitch by 1 (1.5 --> 2.5) and :volume -0.5 would decrease the pitch by 0.5 (1.5 --> 1)
This would allow for cool things such as `:repeat 10 0.5 :pitch +0.5` to allow for gradual increases of pitch or volume
> Add Add/Subtract Support for :volume & :pitch

- MainModule/Server/Core/Commands.lua
All fixed, cant figure out how to change the original file
> Add a system notify

- Loader/Config/Plugins/Client-Example Plugin.lua
- Loader/Config/Plugins/Server-Example Plugin.lua
source: https://roblox.github.io/luau/lint.html
> use --!nolint GlobalUsedAsLocal instead of setting variables to nil to inhibit the warnings

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/HTTP.lua
- WebPanel.lua
Fixed a ``Core.Loadstring`` bug introduced in #241 and a bug related to the WebPanel introduced in bae154a1acc852df73f4a17ad25ede8dce02c5d8.
Since the WebPanel plugin was moved to an external module, it was no longer on GitHub, so I have added it into the main project folder until a better place for it is found. (Perhaps a separate branch or separate repository?) **When merging this please make sure to update the WebPanel module too, I did actually change the code**
> Emergency fix for command-breaking bugs

- MainModule/Server/Core/Commands.lua
This will add the ability to add aliases using commands.
> Adding Aliases: Commands

- MainModule/Client/Dependencies/UI/Default/UserPanel.lua
> UserPanel: Aliases

- MainModule/Client/Dependencies/UI/Default/Aliases.lua
Preparing for adding specialised Kronos features to Adonis
> Port aliases to Adonis from Kronos

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Core/Commands.lua
:taudio now accepts similar arguments to :music, allowing for fine-tuning the audio
:untaudio will stop any target audio playing on the client
From #201 
:
> Improvements to :taudio

- MainModule/Server/Core/Commands.lua
:pause - Allows you pause music played using :music
:resume - Resume the music previously paused
:music
- If a song is paused with :pause, it will prompt to ask if you want to override it
- If an invalid/ Song/MusicList ID is provided or the 1st argument is nil, it will no longer stop the music playing
> :pause, :resume, and changes to :music

- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
- WebPanel.lua
- Instead of setting commands to nil when disabled, there is now a Disabled setting that will be toggled.
- Changes to command overrides and settings (ranks, etc) will now be applied to existing servers correctly
- Some changes to stats that are sent to the web server for new dashboard
- (misc) Added a shortened version of ``displayname-`` selector, ``dn-``
- (misc) Hidden commands are now also hidden from the console
> Large improvements to WebPanel

- WebPanel.lua
> Remove prints from WebPanel

- Loader/Config/Settings.lua
- MainModule/Client/Dependencies/UI/Default/HelpButton.lua
I FINALLY LEARNED HOW TO DO TWO COMMITS IN ONE REQUEST!
Based on skyy's change but not taken from it
> Add ability to change HelpButtonImage from loader

- MainModule/Server/Dependencies/DefaultSettings.lua
> Fix for helpbuttonimage on old loaders

- MainModule/Client/Core/Remote.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
I think the really red, really blue, and really yellow just kill me because they are too real, replaced them with a more soft color and optimized the code as advised by ccuser
> Server and Client logs no longer emit a deadly lazer that makes you colorblind

- MainModule/Server/Commands/Moderators.lua
> datetime now works without pressing refresh buton

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
Used Players:GetPlayers() for Non-Admins/Admins instead of NetworkServer:GetChildren()
~~Replaced ON/OFF with bool strings to make it more fast~~ [REVERTED]
Removed ThirdPartySales (ROBLOX doesn't respect this afaik and was replaced with one inside Game Settings https://i.imgur.com/Fyo6Hzs.png)
Fixed RunCommandAsPlayer trying to get a unknown variable, which was supposed to be plr
Logs lines with only spaces were removed
Fixed Logs indenting on the ServerDetails function
HTTP.CheckHttp is more simplified
> Update ServerInfo Command, HTTP.CheckHttp and RunCommandAsPlayer

- MainModule/Server/Dependencies/TrelloAPI.lua
TrelloAPI now supports PUT/DELETE requests, added backwards compatibility for previous TrelloAPI versions.
nightmare nightmare nightmare nightmare nightmare nightmare nightmare nightmare nightmare nightmare nightmare
> Updated TrelloAPI

- MainModule/Client/Core/Functions.lua
- MainModule/Client/Core/Variables.lua
- MainModule/Client/UI/Default/Friends.lua
- MainModule/Client/UI/Default/Inspect.lua
- MainModule/Client/UI/Default/ServerDetails
- MainModule/Client/UI/Default/Settings.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Process.lua
I did the following:
Replaced the simple list with a tabbed UI window showing even more info about the game.
Added a new client setting that allows players to auto-hide commands run from the chat (without using /e), like in PB Kronos.
Gotta keep testing.
Fixed an insignificant typo in the player inspection UI module and improved the name display format of the online friends UI.
> Misc. Update

- MainModule/Server/Commands/Moderators.lua
So um yes you get it you understand goodbye
> :admins Now shows Head Admin instead of Supervisor

- MainModule/Server/Commands/HeadAdmins.lua
#327 bad
Hail Kohl the all mighty!
> Added :pban as a command alias for :gameban instead.

- MainModule/Server/Server.lua
The testservice messaging is currently disabled until I find a way to iterate over varargs.
> Made print and warn work properly. Also fixed some intendation.

- MainModule/Client/UI/Default/Inspect.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Shared/Changelog.lua
> Serverside Inspect changes + Contributor Group Role Check

- Contributing.md
just a thing since we now have a road blox contributor role
> smol update

- MainModule/Client/UI/Default/Notepad.lua
- MainModule/Server/Commands/Players.lua
The notepad UI now includes font options and a character count display!
I've given it a test and I'm 99.95% confident it's finally going to work.
(Be assured that greater care will be taken in my future contributions to prevent bugs like this.)
> Enhanced notepad + !addfriend & !unfriend fix

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/Assets/Fly.client.lua
`Server/Core/Dependencies/Fly`:
`listenConnection` function for disconnecting before destroying of flying dependencies.
`DescendantRemoving` connection to check if flying dependencies are going to get removed.
`Server/Core/Functions`:
Fix mismatch with `PlayerMatchers` to `PlayerFinders`
> Update /Server/Core/Dependencies/Fly.client.lua, /Server/Core/Functions.lua

- MainModule/Client/Core/Remote.lua
Properly convert to milliseconds
> Correct math in ping measurement

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
Replaced references of game.Workspce to workspace from Logs.lua
Replaced references of game.Workspace to workspace in Moderators.lua
Improved explosion command in Moderators.lua
Improved GetPlayers iteration in Moderators.lua
Did peoper intending in Moderators.lua
> Some code improvements

- MainModule/Client/UI/Default/Console.rbxmx
**NOTE: This has only been added into Default theme, not Rounded, Hydris or any other theme.**
There is no reason as to why this should not be added into any other theme as it causes no conflicts as so far as I have read from the Hydris and Rounded source code.
> Added tab completion to the Default theme

- MainModule/Server/Core/Core.lua
- MainModule/Server/Shared/FiOne.lua
`FiOne`:
Updated [FiOne](https://github.com/Rerumu/FiOne) to the latest (4th June 2021).
~~`Core.ExecutePermission`:~~
~~Optimisations with the `execution checking` to see if it exists already.~~
~~`_G_API.Scripts.ExecutePermission`:~~
~~Alert the user that is using a script/localscript command that its disabled and will cause an error "`Settings.CodeExecution is disabled.`".~~
[Reason for removal of warning]
I actually didn't check if Adonis already checked for this and it for some reason did on all commands (I didn't know that but now I do, its removed as no script should be able to be ran as their is no script usage if its disabled and checked on all commands with it).
> Loadstring Updates. [Core.Lua/FiOne.lua]

- MainModule/Server/Commands/Fun.lua
> Add :transparency command

- MainModule/Server/Commands/HeadAdmins.lua
it shuts down all running servers thats about it
> finished the FullShutDown command

- MainModule/Server/Core/HTTP.lua
Fixes an issue with Trello syncing that was caused by commit 220fbabd29c6360835b39e77b696016df4abf4af
> Fix Trello syncing issue

- MainModule/Client/Core/Anti.lua
- MainModule/Client/Core/Functions.lua
- MainModule/Client/UI/Aero.rbxmx
- MainModule/Client/UI/Default/Chat.rbxmx
- MainModule/Client/UI/Hydris.rbxmx
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Dependencies/Assets/BotBrain.rbxmx
- MainModule/Server/Dependencies/Assets/F3X Deps.rbxmx
- MainModule/Server/Dependencies/Assets/Fly.client.lua
- MainModule/Server/Dependencies/Assets/Freecam.rbxmx
- MainModule/Server/Dependencies/Assets/Piano.rbxmx
- MainModule/Server/Plugins/Server-Dex.rbxmx
The track command has always annoyed me on how it takes forever to track multiple targets at once, this fixes that issue.
> Making track instant for multiple targets and fixing Magnitude refrences. 

- MainModule/Server/Commands/Fun.lua
Adds R15 compatibility for the dance command. #165
> Fix Dance command R15 compatibility

- MainModule/Client/UI/Windows XP.rbxmx
Version 1 of the Windows XP theme.
Might update it when I get bored again.
[Image of what it looks like](https://cdn.discordapp.com/attachments/195368921451331584/862323370287431680/unknown.png)
> Windows XP Theme

- MainModule/Server/Commands/Moderators.lua
> Add: time and date to a warning when hovering over the warning

- MainModule/Server/Commands/Fun.lua
probably VERY useless
https://user-images.githubusercontent.com/29169102/125321960-377cc000-e30b-11eb-92a5-56191ddbe7f8.mp4
> Add :brazil and :doll fun commands

- MainModule/Server/Commands/Fun.lua
Makes the doll massless and not load animations.
Should fix this issue:
> Fix an issue some person had with :doll

- MainModule/Server/Commands/Fun.lua
Also did some minor optimizations.
> :doll can now be used with non-ingame users

- MainModule/Server/Commands/Moderators.lua
first commit on this repo, hope i help!
> copytools command

- MainModule/Server/Commands/Fun.lua
Turns a player into a doll, but when dropped, can be controlled by the player.
Also my second commit to Adonis
> Add command :playergear

- MainModule/Client/Core/Functions.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Remote.lua
**There should definitely be tests of this as it can modify and possibly break all of adonis's concurrent encryption/decryption (Includes DataStores and other things that use Encryption/Decryption) so please make sure to stress test this.**
My tests were basic joining game and testing if :cmds and etc worked as it used Encrypt. (Client used old and Server used new and it perfectly worked)
`Client/Server | Remote`:
Applied the char var as for some reason it was never used but was set?
Switched from `string.len` to `#` as using a len using a operator is mostly faster than using a function to call to get the length and shouldn't change anything as they are the same.
`Client/Server | Functions`:
Applied some optimizations to B64Encode/Decode to not use string metamethods and to cache some …
> [Encryption/B64/GetRandom] : Improvements to Encryption/Randomization

- MainModule/Client/Core/Anti.lua
> Adonis Anti Exploit Bypass detection (Redid #351)

- MainModule/Client/Core/Anti.lua
I forgot to change "string" to "EnumItem" and thats why it was detecting.
I̶ ̶w̶i̶l̶l̶ ̶s̶t̶i̶l̶l̶ ̶t̶e̶s̶t̶ ̶t̶h̶i̶s̶ ̶t̶h̶o̶u̶g̶h̶ ̶t̶h̶a̶t̶ ̶i̶t̶ ̶w̶o̶r̶k̶s̶. Yep it works now
> Fixed my log detectection

- MainModule/Client/UI/Default/Explorer.lua
- MainModule/Client/UI/Default/Window.rbxmx
Doesn't effect existing themes, they can implement this is they really want but there's no reason as to why unless they update their themes.
NOVA DASHBOARD LEAK [2021] [PUNJABI SAFE] [NO VIRUS] [100% ARAB]
> Exploit patch & data.OnClicked functionality for ImageButton's

- MainModule/Client/UI/Default/Notepad.lua
- MainModule/Client/UI/Default/Paint.lua
- MainModule/Server/Commands/Players.lua
I have absolutely no idea why...
(also minorly updated !notepad)
> Add !paint

- MainModule/Server/Commands/Moderators.lua
Updated "thru" to ONLY teleport to YOURSELF if anyone has a similar name in-game. (Display Name) [Tested]
Added new commands for "joinserver": jserver & jplace
Updated message for "joinserver"
Updated the "tools" commands, added ZIndex values. (Frame = 1, Button = 2) [Tested]
> Updated "thru", New commands for "joinserver": jserver & jplace + new message, Updated "tools"

- MainModule/Server/Dependencies/Loadstring/init.lua
> Revert "Update init.lua"

- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Default/PrivateMessage.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Plugins/Urgent_Messages.lua
Notification UIs for the Default theme now include a customizable icon next to the title. Also, the maximum text size for notification content is now 20 to appear neater.
**Uses [Material icons from Google](https://fonts.google.com/icons?selected=Material+Icons) ('Sharp' collection). Tell me if you need to implement any icon and I'll give the Roblox asset ID.**
> Introducing notification icons!

- .github/workflows/rebase.yml
https://github.com/cirrus-actions/rebase
> Automatic Rebase

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
you wont believe how much pain it took to make all the replacements
the next time yall write code for adonis pls remember spaces after commas, avoid unnecessary semicolons, try to adhere to double quotes for strings, dont use deprecated stuff
also, https://roblox.github.io/lua-style-guide
**two hours**; im not doing this again ok bye
> Code Tidying/Formatting of Command Modules

- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- `!tshirt/givetshirt <ID>`
- `!removetshirt/untshirt/notshirt`
- `:tshirt/givetshirt <player> <ID>`
- `:removetshirt/untshirt/notshirt <player>`
- The `:explode` command now accepts an optional third argument that determines the explosion's pressure (500,000 by default) and an optional forth boolean argument that determines whether the explosion is visible (true by default).
> T-shirt commands & :explode update

- MainModule/Server/Plugins/Server-Dex.rbxmx
This pull request adds the following to Dex:
- Fixes bug preventing creating objects on the server
- Adds support for invoking/firing bindables on the server.
- Adds support for invoking/firing clients on remotes.
- Add support for firing instance functions on the server.
- Fix various dark theme UI issues.
> Dex updates

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
> Simplified type annotations for cmd modules + some random code improvements

- Loader/Config/Settings.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Defaults to off now, apologies for this issue.
We'll look into how we handle the hat anti-exploit.
> Temporary fix to Hat weld anti exploit error

- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Dependencies/TrelloAPI.lua
Tested in a live game; works as intended.
Report any issues ASAP
> HTTP Trello can support Custom Ranks now

- MainModule/Server/Commands/Moderators.lua
> Add :removetool command, improved :removetools

- MainModule/Server/Core/Core.lua
Prevents blacklisted tables from being allowed to load during initial startup.
There was a previous push for this, but that missed the other method. 
This patches both methods now.
All things included in DS_BLACKLIST are no longer able to load from the datastore. 
Including Creators now, as that was a backward-compatibility issue with the new rank structures.
Ranks table in Settings can also no longer be set through the datastore.
> Patch LoadData vulnerability

- MainModule/Server/Core/Core.lua
This also loads and overrides admin levels
> Included Admin.SpecialLevels in blacklist

- MainModule/Server/Commands/Moderators.lua
> [URGENT] Fix :removetools & :removetool

- MainModule/Server/Commands/Fun.lua
I mean... I would rather change it but it looks unfinished, a lot
> Uncommented and modified "Trail" command

- MainModule/Client/UI/Default/ToolCenter.lua
- MainModule/Client/UI/TextPrompt.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
Also added a ``:trigger <player>`` command.
> Tool Center (enhanced :tools) + TextPrompt UI

- MainModule/Client/UI/Default/Teams.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
self-explanatory, i also changed some string functions to the string library
> fixed visibility issues in :teams and :tools

- MainModule/Client/UI/Default/Console.rbxmx
added a service event for toggling the console did not manufacture creamed cheese or fix exploit sorry
clickbait sorry
> [EXPLOIT FIX!!!] Manufacture creamed cheese.

- MainModule/Server/Commands/Donors.lua
Fixed a slight error that cause !donorneon to bug.
> !donorneon Command fix.

- MainModule/Server/Core/HTTP.lua
> Fix critical typo in comments

- MainModule/Client/Core/Remote.lua
- MainModule/Server/Core/Process.lua
We might look into adding a client endpoint for Refreshing a specific UI
> Improve how CharacterAdded loads UIs

- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Logs.lua
- Rich text & tooltips.
- Rectified window sizing.
> Update !timedate command

- MainModule/Client/Core/Anti.lua
I didnt put it in a while true do loop so it didnt work at all.
> Fixed Anti-idle detector not working

- MainModule/Client/UI/Default/HatList.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Moderators.lua
> Add !myhats, :removehat; some improvements

- MainModule/Server/Commands/Moderators.lua
a dupe pr, accident, whoops
well this one is different, but still an accident
> Player Warnings will be shown when notification was clicked for cemoveWarnings and RemoveWarning

- MainModule/Server/Commands/Moderators.lua
> Updated Kickwarn with notification; Player Warnings will be shown when notification was clicked

- MainModule/Client/UI/Default/Window.rbxmx
Moves tooltips to the other side of the mouse if they would get cut off in their normal position
> Tooltips always visible

- MainModule/Server/Commands/Moderators.lua
Changed the line to be hum.MaxHealth instead of humanoid.MaxHealth
> Fixing the health command

- MainModule/Server/Commands/Moderators.lua
so i made my other pr (#651) and I'm kinda fixing it due to a dumb mistake of mine, apologies
> Fixed :bring and :tp bringing you back while flying

- MainModule/Server/Core/Anti.lua
> Added a "for" in the exploitlogs message.

- MainModule/Server/Commands/Players.lua
Why? Because I like it better. 
Palette chosen because colour indirectly ties in with "theme"
> Add icon to theme command

- MainModule/Server/Commands/Moderators.lua
yes i made :unff and :visible ignore this invisible ff too
rtool > removetool
rtools > removetools
> added :fullgod (:god but also gives an invisible forcefield for blast protection) and like 2 new command aliases

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
> Big icon adding pull request

- MainModule/Server/Core/Admin.lua
Added a potential fix for the lack of donator perks for contributors of Adonis
> Add donator check for contributors

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Remote.lua
Added lots of icons to commands that didn't have them before.
> More icons pull

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Variables.lua
A long-overdue PR with some inspiration from Kronos stuff. Brought to you from NullLand development.
I had originally named ``:incognito`` as ``:vanish`` but decided the former to be more suitable.
> Introducing :disguise and :incognito

- MainModule/Server/Commands/Admins.lua
This is very important stuff right here.
> Fix very important grammar

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Variables.lua
``:track <player(s)> <persistent? (default: false)>``
> Add argument option for :track to persist after respawns

- MainModule/Client/Client.lua
- MainModule/Server/Server.lua
Realized this when the ``:countdown`` command broke.
> Fix assert not returning the first arg on assertion success

- MainModule/Client/UI/Default/Countdown.lua
- MainModule/Server/Commands/Players.lua
> Add !countdown; elapsed time display in Countdown UI

- MainModule/Client/UI/Default/ToolCenter.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
Thanks to @Honzzzox for the ``:tools`` 'Storage' & 'Added' tabs inspiration.
> The tools update

- MainModule/Server/Commands/Moderators.lua
View the admin logs for the server.
> fixed remotelogs description

- MainModule/Server/Plugins/Cross_Server.lua
Better than a crude fix inside Admin.lua, you'll agree.
Untested PR but lets be real here it's one line and looks tickity boo.
> Emergency fix relating to donor perks update

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
Resolve the bug with not being able to reequip hats after removing them and also converts bodyswap from cloning all the assets to using humanoid descriptions
> Convert removehats and body swap to humanoid description

- MainModule/Server/Commands/Moderators.lua
I changed the description of AvatarItem and RemoveHats that it changes HumanoidDescription.
And I added an alias on AvatarItem called "giveavataritem" and "catalogitem"
> Changed description of commands to clear up that they change HumanoidDescription.

- MainModule/Server/Core/Variables.lua
> Updated Variables.lua

- .github/FUNDING.yml
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Plugins/Misc_Features.lua
Added donations to github sponsor + Fixed issues with games that have Third party purchases disabled
> Donations update

- MainModule/Client/UI/Default/CommsPanel.lua
- MainModule/Client/UI/Default/Hint.rbxmx
- MainModule/Client/UI/Default/Message.rbxmx
- MainModule/Client/UI/Default/Notif.rbxmx
- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Default/Notify.rbxmx
- MainModule/Server/Commands/Players.lua
> Comms Panel

- MainModule/Server/Core/Variables.lua
Some audios may or may not get added back. If they do just add them back......
Press F to pay respect for the removed audios
> Remove Audios Unplayable due to the Audio Update

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
Wake up new Adonis command dropped.
it's  currently 2am send help
> Add startergear

- MainModule/Client/UI/Default/Music.rbxmx
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Shared/AudioLib.lua
Adds fancy stuff like a working scroll bar and a single global audio sound instance, among (us) other things.
The audio player is almost suitable to replace the new essentially legacy ;music command, but I shan't do that in this PR.
> [2/4] The second bi-annual Audio Player update.

- Loader/Config/Settings.lua
- MainModule/Client/Core/Anti.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
yo, i wanna keep premium players for the good robux premium payouts!
stop kicken my players!
i defaulted to false cuz,
uh, why check for idle?
> Create new AntiClientIdle setting

- MainModule/Server/Commands/Moderators.lua
Added 4 commands back, that allow you to change shirt, pants, face and tshirt with images as well.
They're named "customshirt, custompants, customtshirt, customface", they all allow the player running the command to specifiy image IDs as well.
> Added 4 commands back, that allow you to change clothings and face with images as well.

- MainModule/Server/Commands/Moderators.lua
> fix stupid typo

- MainModule/Server/Dependencies/Assets/UFO.rbxmx
Stopped the message spam relating to the UFO's sounds.
> Remove some private sounds

- MainModule/Server/Core/Remote.lua
Basically this is all I do with my life now
please help
> Epic icon add

- MainModule/Client/Client.lua
- MainModule/Server/Server.lua
Sceleratis, we spoke about this already... Luau already randomizes math.random...
> Removed useless math.randomseed function

- MainModule/Client/Client.lua
Added more common services to ServicesWeUse, fixed typo in StarterPlayer (it's not StarterPlayers guys)
> Added more common services to ServicesWeUse, fixed typo

- MainModule/Client/Client.lua
This is probably one of those years old things that had a use back in the day.
But its causing issues for people and I dont see why it should honestly exist
> (Important) Remove "Shananigans denied" bug which is kicking random people

- MainModule/Server/Shared/MatIcons.lua
Committing in accordance with the prophecy.
> Add epix inc logo as icon

- MainModule/Client/Client.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Plugins/Server-SoftShutdown.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/Service.lua
`Shared`:
TrackTask: Now uses `table.pack` to then use for `unpack` using the `n` argument.
FormatNumber: Use Roblox CoreScripts implementation instead of ugly hacky method.
GetTime: Sunset usage of GetTime to instead use `os.time` instead (will still be referenced just in case of plugin usage)
MaxLen: Rewrote to simplify code.
FormatTime: Rewrote variables and added minor documentation.
> Minor fixes towards Service

- MainModule/Client/UI/Default/Alert.lua
(best one i could find do not judge)
> Replace the alert sound in :alert

- README.md
Though this was a cool thing you could do, it's at the very bottom and I don't see why not.
See [https://contributors-img.web.app/image?repo=sceleratis/adonis](https://contributors-img.web.app/image?repo=sceleratis/adonis) for more details.
> We demand better recognition.

- Loader/Config/Settings.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Also made oldlogs respect settings.DataStoreEnabled
> Added settings.SaveCommandLogs

- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Functions.lua
`BrickColorList` `RequestHelp`
_include little mistake_
> Fixed some player commands

- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Admin.lua
Was working on some enhancements for TTD 3's fork of Adonis and saw the comment in TimeBan's command function asking someone to make the function. Here you go!
This pull request also features DirectTimeBan which will work the same way DirectBan does, just with TimeBans instead.
> Admin.AddTimeBan, Admin.RemoveTimeBan, fix for !join / !follow

- Loader/Config/Settings.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Some more stuff to give place owners more control of the DS loading process in their games
> Coasterteam Load Admins from DS

- MainModule/Server/Core/Core.lua
> [FIX] Fixed it

- Loader/Config/Settings.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Apparently, there is nothing that stops leaks or even uses this setting.
> Remove old AntiLeak setting

- MainModule/Server/Commands/Fun.lua
why would you fix kitty and spooky, but not dogg?
> Fixed :dogg for R15 characters

- MainModule/Client/Core/Anti.lua
There is 0 possibility this could somehow error, but it just does sometimes
> Fixed mystery error

- MainModule/Server/Commands/Moderators.lua
> Add date to old server logs

- MainModule/Server/Commands/Admins.lua
> Fix for #804

- MainModule/Server/Commands/Moderators.lua
don't think that even impacts it in any way
> Added "Fun = false;" to avataritem command.

- MainModule/Client/UI/Aero.rbxmx
- MainModule/Client/UI/Default/Window.rbxmx
- MainModule/Client/UI/Unity.rbxmx
- MainModule/Client/UI/Windows XP.rbxmx
`Window`:
Fixed mobile support somewhat (testing should be done)
Moved Mouse.X/Y -> input.Position.(X/Y)
Switched next -> pairs/ipairs
The other themes have only the mobile fix and movement.
> Partial fixes for Window

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
Essentially, ban commands now record the name of the admin who banned the user.
> Ban moderator information

- MainModule/Server/Commands/Players.lua
- Better error messages/feedback.
- Argument validation. If you're wondering about the 'vulnerability' label, it's because I received a report about ``!join`` and/or ``!joinfriend`` being abused to lag the server because there was "no string limit". If that's true then this fixes it, and improves the command UX anyway.
- If there was any issue with ``!join`` not working, it's probably been fixed here.
> Update !join and !joinfriend

- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
> Switch most teleportation-related commands to using TeleportAsync

- MainModule/Client/UI/Default/ToolPanel.lua
> Rename Tool Cent"er"

- Loader/Config/Settings.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Inspired by PB Kronos. 🛡️🛡️💪💪
When enabled, players will not be informed of whether they entered a command that doesn't exist, or whether that command is one that they don't have permission to run.
> Add settings.SilentCommandDenials

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Process.lua
- General improvements to ``Admin.CheckPermission`` and ``Process.Command`` (most denial messages are now supplied directly by ``Admin.CheckPermission``)
- Creators can no longer bypass CrossServerDenied or NoStudio
> Command permission system changes

- MainModule/Client/Dependencies/Theming_Info [Read].lua
Hasn't been updated in 15 months 😎
> Theming Info update

- MainModule/Server/Commands/Admins.lua
Could probably do with a lovely assert or whatever else.
Lazy fix.
Go lag yourself.
> LYS (Lag yourself)

- MainModule/Client/Core/Functions.lua
- MainModule/Client/Core/Process.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Dependencies/ClientLoader.client.lua
- MainModule/Server/Dependencies/TrelloAPI.lua
* Server/Core/Remote - 4
* Server/Core/Anti - 1
* Server/Dependencies/ClientLoader.client - 1
* Server/Dependencies/TrelloAPI - 7
* Client/Core/Remote - 3
* Client/Core/Process - 1
* Client/Core/Functions - 5
> Removal of next() and pairs() from codebase

- MainModule/Client/Core/Remote.lua
copied server log updater to be the client log updater
> Update :clientlog ListUpdater

- MainModule/Client/Client.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/Service.lua
`Client`:
Prettified the Client code to make it appealing.
Implement IncognitoPlayers table
`Admins`:
Prevent left players from incognito
`HeadAdmins`:
Implement UnIncognito command to make players visible again.
`Process`:
Implement check to prevent players who have left or are not inside the players parent (Sanity check) from being shown.
> Unincognito command

- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
Bans that are removed via Datastore should actually be saved properly now (as in they get removed and then saved with them removed!)
> Unbans save properly once again

- Loader/Config/Settings.lua
> Change settings.HelpButtonImage description

- MainModule/Server/Commands/Players.lua
For servers outside the US, this would just display blank so here's the thingy
> !serverinfo server location display fix

- MainModule/Client/UI/Aero.rbxmx
removed all instances of `pairs` and `next`
replaced all instances of:
`wait` with `task.wait`,
`spawn` with `task.spawn`,
`children()` with `GetChildren()`
> Minor improvements

- Loader/Loader/Loader.server.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Client/UI/Default/Alert.lua
- MainModule/Client/UI/Default/Aliases.lua
- MainModule/Client/UI/Default/ColorPicker.lua
- MainModule/Client/UI/Default/Countdown.lua
- MainModule/Client/UI/Default/Effect.lua
- MainModule/Client/UI/Default/PrivateChat.lua
- MainModule/Client/UI/Default/SelectionPrompt.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Client/UI/Default/Vote.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Dependencies/Assets/BotBrain.rbxmx
- MainModule/Server/Plugins/Cross_Server.lua
- MainModule/Server/Plugins/Generate_CmdList_JSON.lua
- MainModule/Server/Shared/AudioLib.lua
- MainModule/Server/Shared/Service.lua
- MainModule/Server/Shared/Typechecker.lua
- Removed some instances of `next` and `pairs`
- Replaced some instances of `wait` with `task.wait` and `delay` with `task.delay`
- Updated BotBrain to replace deprecated objects such as `workspace:FindPartOnRay` and `CFRame.p` with up-to-date ones
- Updated :bot to fix the issue of "walk" always being true and the bot number always being 50 or higher
- Fixed ":command %" being the same as ":command all"
This pull request therefore declares that I have no job
_i should get contributor fr_
> Optimisations and bug fixes

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Server.lua
`Core`:
Cleanup for junk data removal.
`Server`:
Remove CloneTable duplicate reference
Set CloneTable to use the Server.lua version, shouldn't effect anything (hopefully?, we may have issues with metatables?)
`Moderators`:
Fix typo
Track fix
> Track (all/persistent) fix + Minor code cleanup

- MainModule/Server/Commands/Admins.lua
Fixed the wrong commits this time and tested it
> Added prompt for team removal

- MainModule/Server/Commands/Moderators.lua
> Added a chair intolerance to :massbring.

- MainModule/Client/UI/Default/Console.rbxmx
A Roblox change made the console cursor black but this pr should hopefully fix it
> Fix console cursor being very hard to see

- MainModule/Server/Core/Anti.lua
The game engine doesn't kick the player immediatly allowing a bit of spawm
> Fixed notification spam from gsme engine not instantly kicking

- MainModule/Server/Shared/Credits.lua
He created the Lua compiler in Lua and the first bytecode interpreter used in Epix
Edit: Made pull request also add buildthomas, hes the creator of `MockDataStoreService`
> Added KH Man to credits

- MainModule/Server/Commands/Moderators.lua
Fix for https://discord.com/channels/81902207070380032/1063825775754743878
> Fix Bots command num argument issues.

- MainModule/Server/Core/Variables.lua
Add `It's raining tacos` back to the music list
> Add `It's raining tacos` back to the music list

- MainModule/Client/UI/Default/Music.rbxmx
- MainModule/Client/UI/Unity.rbxmx
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Remote.lua
- WebPanel.lua
Fixes:
- Webpanel key leak
- Being able to set webpanel settings and localdatastore
- Little small code fixes
> [EMERGENCY WEBPANEL KEY LEAK VULN FIX!!!!] & Small code usage fix

- Loader/Config/Settings.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
This pull request adds support for `TextChatService`
Unfortunately due to `TextChatService` using callbacks this will override all developer `.ShouldDeliverCallback`s for every text channel
> Add support for `TextChatService` to `Admins.lua`

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Shared/AudioLib.lua
Non position based global sounds should be in SoundService (both Client and Server made sounds)
Pls make sure I ported all of the sounds from `workspace` to `SoundService` so it doesnt cause any mismatches
> Changed sound parenting to SoundService

- MainModule/Client/Core/UI.lua
> Fixed unchat not applying vanilla chat

- MainModule/Server/Dependencies/TrelloAPI.lua
> Fixed trello queue invalid empty check

- MainModule/Server/Commands/Fun.lua
I don't know why my branch still shows commits which have been committed, must be a bug.
> Improve ;spin with the help of AI.

- MainModule/Client/UI/Unity.rbxmx
**Bug:**
- There was multiple, many, and unnecessary instances (UICorner) being created by the script due to not implementing an "if" statement before the creation of a new one...
**Demonstration:** 
- ![notes marker](https://i.imgur.com/WqlMTVW.gif)
**Solution:**
- Simple "if not" statement to determine if the tooltip is in need for a new UICorner or not.
> Fix for "Unity" theme. Window Gui is creating unnecessary instances

- MainModule/Server/Commands/Fun.lua
> Fix shia command support for newer character systems (R15 and others)

- MainModule/Server/Server.lua
( I may or may not have accidentally deleted my fork )
> remove Duplicated line and update todo list

- .editorconfig
This would be useful for reading and editing from the web.
> Create ".editorconfig" & Apply A Default Tab Size

- MainModule/Server/Core/Remote.lua
Also this is improper syntax which can cause glitches
> Fix lint error

- MainModule/Server/Commands/Moderators.lua
You currently can't remove layered accessories. "GetAccessories(false)" is used to retrieve the layered clothings from there.
@Expertcoderz
> Added "RemoveLayeredClothings" command

- README.md
Ok this is kind of an unnecessary pull but whatever
> Super small markdown fix

- MainModule/Server/Commands/Moderators.lua
Control has been broken since 2015. Here's a fix.
FUN FACT: The old version of this command caused me to get banned by a game's anticheat system when a game moderator used it on me for a joke.
> Rewrite :control

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/Assets/BotBrain.rbxmx
The bot command is slow and lags the server so this makes it faster
> Made botbrain multithreaded

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/FastNuke.lua
The current Adonis nuke command is really bad. This pull request adds a much better nuclear explosion to Adonis.
The nuclear explosion code is from <https://github.com/ccuser44/Fast-nuclear-explosion> (made by me)
> Added a much better nuke from <https://github.com/ccuser44/Fast-nuclear-explosion>

- MainModule/Client/UI/Default/Music.rbxmx
- MainModule/Client/UI/Default/Settings.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Dependencies/Assets/Slippery.client.lua
- MainModule/Server/Shared/AudioLib.lua
Fixes:
- Audiolib not working
- Slippery command not working
- Fixed datastore saving being invalid (This fix also makes the datastore a lot faster than previously, Adonis will probably never hit datastore clogging again)
- Fixed invalid keybind names
> Fixed bugs in nightly

- MainModule/Server/Commands/Moderators.lua
why does this command exist? I dont get it
> Update GRP command

- MainModule/Client/Plugins/Anti_Cheat.lua
Added tons from the synapse documentation and my own memory
> Add more exploit functions to output check

- MainModule/Server/Shared/Changelog.lua
added some last minute commits hopefully
> v239 Changelog final

- MainModule/Server/Commands/Moderators.lua
> Coasterteam patch 1

- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/Service.lua
> Rounded and data save fix

- MainModule/Server/Shared/Changelog.lua
Wow making pull requests for changelogs is so efficient and effective, said no-one ever
> Patch v239a Changelog

- MainModule/Client/Plugins/Anti_Cheat.lua
They don't seem to cause detections but better to be safe than sorry. These are only ones that could in theory cause detections.
> Disable a few lines that could in theory cause detections.

- MainModule/Server/Shared/Typechecker.lua
Indicates that t.instanceIsA() supports childTable  
Adds recent DataType additions 
Replaces usage of nonexistent Enum.EnumType
> Typechecker update

- MainModule/Server/Shared/Changelog.lua
> Patch v239b changelog

- MainModule/Server/Core/Admin.lua
> Fixes potential issue with `:commands` erroring

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/FastNuke.lua
The old Adonis nuke sucks. This one doesn't also this is highly optimised.
Nuke is from <https://github.com/ccuser44/Fast-nuclear-explosion> (made by me).
This was already added in #1033 but was reverted in <https://github.com/Epix-Incorporated/Adonis/commit/2ffe960879a0ae6810ab02bde6877042a2099a4c> for some reason.
> Re add better nuke

- Loader/Version.model.json
- MainModule/Server/Shared/Changelog.lua
> Changelog v240

- MainModule/Server/Shared/Credits.lua
I have 2 merged pull requests fr!!
> Add me to credits

- MainModule/Server/Shared/Credits.lua
> add myself to credits because pro

- MainModule/Server/Commands/HeadAdmins.lua
Simple edit to fix :awardbadge throwing an error every time the command is run
> Fix :awardbadge

- MainModule/Client/Core/Anti.lua
This fixed a few anti bypasses that prevent the Detected function from running.
The anti bypasses this fixes are a more than 4 years old now but now have been fixed.
> Fixed an anti bypass

- MainModule/Client/Plugins/Anti_Cheat.lua
This fixes a *potential* but highly rare false positive for the detection which could happen because of window deselection
Edit: The bug was likely caused by the Roblox Windows store application
> Fix for Tamper Protection 0x16471

- MainModule/Server/Dependencies/Assets/Fly.client.lua
[bug report](https://discord.com/channels/81902207070380032/1108946755921387530/1108946755921387530)
> Fix fly unfunctional

- MainModule/Server/Dependencies/Assets/Fly.client.lua
Fixed :fly so it works with gamepads and mobile touch controls. 
Buttons:
- Toggle: Mobile on-screen button, controller L3 (left thumbstick button), keyboard E
- Up: DPad up, controller A, keyboard space
- Down: DPad down, controller B, keyboard Q
Other changes:
- Gave the mobile flight toggle button a title so people actually know what it does
- Fixed mobile button not removing on :unfly or character respawn
I've tested this code on different devices so it should be good to go.™️
If you guys have any suggestions for performance improvements please let me know and I'll implement it.
> Fix :fly on mobile and console

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
> Age restriction settings

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
> Add atmosphere support

- MainModule/Server/Commands/Moderators.lua
Made Text Selectable & Added the UserId of the Player in front of the format.
> [Add Text Selectable + New Text Format] :selectplayers/:count

- MainModule/Client/Core/Anti.lua
> Anti error codes added

- MainModule/Client/UI/Default/Notepad.lua
https://discord.com/channels/81902207070380032/1118878035672846477
> Dark themed notepad

- MainModule/Client/UI/Default/Chat.rbxmx
- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Default/Hint.rbxmx
- MainModule/Client/UI/Default/Message.rbxmx
- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Default/Notify.rbxmx
- MainModule/Client/UI/Default/Output.rbxmx
- MainModule/Client/UI/Default/PlayerList.rbxmx
- MainModule/Client/UI/Default/Window.rbxmx
@Sceleratis 
merge pls, thx
it fixes Font issues, cuz for Rojo it's only fixed for next update and idk when that should be
everything is the same, just that Roblox changed properties or something but is also able to convert it, while Rojo has to code it or something because it's a third party
also can I have permissions 😭
> Re-save the .rbxmx file to prevent Rojo issues

- MainModule/Server/Shared/Credits.lua
> Update my name

- MainModule/Server/Core/Functions.lua
> Fix odd shutdown format

- MainModule/Client/Plugins/Anti_Cheat.lua
> Add som more non-chad exploits to detections

- Loader/Config/Settings.lua
> Fixed a possible end of the world scenario.

- MainModule/Server/Commands/Moderators.lua
This existed (or something similar thats NOT :message) earlier before. Not sure why it was removed
> Add :cn (:customsmallmessage)

- MainModule/Client/UI/Default/Chat.rbxmx
- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Default/Hint.rbxmx
- MainModule/Client/UI/Default/Message.rbxmx
- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Default/Notify.rbxmx
- MainModule/Client/UI/Default/Output.rbxmx
- MainModule/Client/UI/Default/PlayerList.rbxmx
- MainModule/Client/UI/Default/Window.rbxmx
Reverts Epix-Incorporated/Adonis#1173
@Sceleratis I think I re-saved the bugged ones.
I'll re-submit them with a fixed version. Idk what reverting does, if it doesn't remove it from the commits, for anyone that wants to pull from this repository, then it's pointless to merge this.
> Revert "Re-save the .rbxmx file to prevent Rojo issues"

- MainModule/Client/UI/Default/List.lua
A feature from EISS. Just the difference is that this time it shows in search box instead of being a textlabel in the list.
> Made the search bar show count of items in the current list.

- MainModule/Client/Plugins/Anti_Cheat.lua
> Patch HookMT thingymabob

- Loader/Config/Settings.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
@coasterteam 
wait for Settings.lua
also I added "Anti32bit" into ``order`` because it wasn't there before
This is a revert, but without using the revert thing cuz idk about conflicts
So I manually went through the process.
It undo's this https://github.com/Epix-Incorporated/Adonis/pull/1155 while keeping every change that was made before
My feedback about whatever change the other thing was
https://github.com/Epix-Incorporated/Adonis/pull/1155#issuecomment-1676430252
whatever their excuse is
We don't need to save file space 💀
when this is running on Roblox it's turned into bytecode anyways 💀
&nbsp;
also @coasterteam add me on Discord 🙏 you have all DMs off
> Change DefaultSettings back and sync Settings but keep all the changes, since it caused issues

- MainModule/Server/Shared/Service.lua
This adds support for <https://devforum.roblox.com/t/localization-api-update-for-upcoming-in-experience-language-switcher/1974795>
> Add support for in game locale changing

- README.md
Pretty sure expertcoderz added these and then it turned out they didn't work soooo
> Fix the weird readme links

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
> Disable buy item by default

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/DoubleLinkedList.lua
- MainModule/Server/Shared/Service.lua
This adds various things:
- LinkedList logs (default on, turn off by setting the setting `settings.UseLinkedListsInLogs` to false in Loader (massive performance improvement if on, you lose that when disabled)
- Commands `:createstat` and `:removestats` 
- RateLimiter memory leak fix
> Merge multiple changes

- .github/workflows/build.yml
- .github/workflows/publish.yml
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Shared/Service.lua
Very spooky fixes include fixing workflows, the loader, and :thru/:bring UX issues.
> 👻 Spooky Adonis State Fixups 

- MainModule/Client/Client.lua
- MainModule/Client/Core/Core.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/Service.lua
- Fix remaining MetaTable issues
- Prevent anti-cheat from crashing your whole studio if you are flagged
> 🦃 More Adonis State Fixups 

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Variables.lua
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md
> Coasterteam various fixes and improvements

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Dependencies/Assets/Singer.lua
- MainModule/Server/Dependencies/Assets/Singer.meta.json
This can also be used as a portable sound source
> Create `:sing` command

- MainModule/Client/Plugins/Anti_Cheat.lua
This reverts commit 7d3e06dee27af574df349f777ec5fc1a833838d8.
> Revert "Add som more non-chad exploits to detections (#1174)"

- MainModule/Server/Commands/Fun.lua
> Fixed `:creeper` with non-default character sizes and proportions

- MainModule/Client/UI/Mobilius.rbxmx
> Fix broken help button with Mobilius theme

- MainModule/Server/Commands/Fun.lua
I hadn't made the second commit to #1254 to fix creeper fully and didn't expect it to get merged so quickly so here is the second commit
> Remove `-` Creeper, part 2 of #1254 creeper fix

- .github/ISSUE_TEMPLATE/Bug_Report.yml
- .github/ISSUE_TEMPLATE/Feature_Request.yml
- .github/labeler.yml
- .github/workflows/build.yml
- .github/workflows/publish.yml
> GitHub Repo Changes

- MainModule/Client/Core/Process.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Shared/Service.lua
Convert older functions to the latest changes on TrackTask from https://github.com/Epix-Incorporated/Adonis/pull/1216/commits/be9b35241f7de6b243b3fe9fb35993043f70cf7d
> fix: TrackTask upgrade on older functions

- MainModule/Server/Plugins/Debug_Specific.lua
This makes debugging the anti cheats detection a lot easier
> Add command to debug anti cheat

- MainModule/Client/Core/Anti.lua
This pull request shows what device the user. This is only for gathering analytics
> Show users device on exploitlogs for better analytics

- MainModule/Server/Commands/Fun.lua
This makes it a lot more comedic and scarier
> Add Fresh Meat sound from Diablo 1 to :clown

- MainModule/Server/Commands/Fun.lua
The command seems kinda empty expecially when you don't have sounds enabled
This makes it less so
> Add particles to trigger

- Loader/Config/Settings.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Variables.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Reverts Epix-Incorporated/Adonis#1251
> Revert "Move `UseLinkedListsInLogs` from Settings to Variables"

- Loader/Loader/Loader.server.lua
- MainModule/Server/Dependencies/RebootHandler.rbxmx
- MainModule/Server/Plugins/Debug_Specific.lua
- MainModule/Server/Server.lua
The pull request \\/
[![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/60defbeb-4f16-42d7-9501-712ef848f96c)](https://github.com/Epix-Incorporated/Adonis/pull/1238)
removed the dropper file but left other artifacts which caused Adonis to be bricked. This fixes that
> Remove dropper artifacts, fix Adonis being totally broken

- MainModule/Server/Plugins/Cross_Server.lua
Fixes #1234
Fixes \\/
Loading order before issue:
Loading order after removal of crossserver plugin:
Loading order with fix applied:
> Fix adonis being bricked for a long time (fixes crosserver issue)

- MainModule/Server/Core/Admin.lua
~~This only appears sometimes (why?) (a sign of a deeper issue in Adonis that needs investigation)~~
> Fix odd issue

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- WebPanel.lua
- Optimise `assert` calls
- ~~Remove legacy givepoints command, [PointsService has been disabled totally](https://devforum.roblox.com/t/retiring-pointsservice/2318767)~~
- Fix gamegravity command not being able to reset gravity
- Fix TimeHint from not working at all
- Fix webpanel not understanding error codes properly
> Optimise assert, fix webpanel debug, fix gamegravity default, fix TimeHint

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Plugins/Misc_Features.lua
Move AutoClean to Miscfeatures plugin
> Move AutoClean to Miscfeatures plugin

- MainModule/Server/Commands/Fun.lua
running :chargear as r6 doesn't work because BodyHeightScale, BodyDepthScale, and BodyWidthScale does not exist.
> Fix chargear not working in r6

- Loader/Config/Settings.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
> Turn `settings.CodeExecution` to true by default

- Loader/Config/Settings.lua
- MainModule/Client/Core/Process.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Shared/Service.lua
Nice bugs ngl.
Fixes trello and other things.
> Cherry-pick some issues to release

- MainModule/Server/Commands/Fun.lua
> Fix :sceleratis

- MainModule/Client/Core/Functions.lua
I added every property and class to :GuiView
Before: (By: me)
After: (By: me)
> Added all properties and classes to ":GuiView"

- MainModule/Client/UI/Default/Paint.lua
Fixed support for Touch on Paint to allow for mobile devices.
> Fix Touch input on Paint command

- MainModule/Server/Commands/Admins.lua
This mostly just adds a way to remove starterscripts
List of everything this adds:
- adds :createstarterscript as another name for :starterscript
- adds :starterscripts using a list UI
- adds :removestarterscript <name>
:removestarterscript also supports an "all" argument which removes all scripts
> Adds name argument to :starterscript; Adds :starterscripts; Adds :removestarterscript <name>

- .github/workflows/publish.yml
- MainModule/Server/Shared/Changelog.lua
I'm a sigma female so I'm not gonna include any proof of functionality.
> Merge master changes to release

- MainModule/Client/UI/Default/FPS.lua
- MainModule/Server/Commands/Players.lua
**Command to run:** "!fps" or "!framespersecond"
**Admin Level:** Player
Preview:
> Added FPS Command

- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Process.lua
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md
> Revert regressions introduced in #1313 and #1308

- MainModule/Server/Commands/Moderators.lua
There is no reason to to have a different command specifically for the atmohphere as it's part of the lighting and just adds bloat
Also makes it harder to actually fix lighting because you have to use 2 commands instead of one
> Merge resetatmosphere to resetlighting

- MainModule/Server/Commands/Moderators.lua
Fixed bug where when looking for the player the argument it wasn't there (I didn't put args in a table)
> Fixed :Jail bug not unjailing after set time

- MainModule/Client/UI/Default/FPS.lua
Currently it only shows the render FPS (and a bit improperly).
Now this specifies both the render and physics FPS which are different
It does not fix the invalid reporting of the render FPS though
> Fix FPS gui

- MainModule/Server/Core/Logs.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Server.lua
^^
It's problematic to only have a setting in defaultsettings.
Better change it to a loader flag.
> Make disabling linkedlists a loader flag

- .github/ISSUE_TEMPLATE/Bug_Report.yml
> Improve bug report form

- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Variables.lua
- MainModule/Server/Plugins/Misc_Features.lua
Superseeds #1285
Givepoints is deprecated, this adds backwards compatibility
> Make givepoints an alias

- MainModule/Client/UI/Default/ScriptEditor.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
This script editor is one of the first to be put into adonis (or the first) and it is kind of complex, not really tho.
Showcase:
https://cdn.discordapp.com/attachments/772798498835398659/1188596469058519190/2023-12-24_15-35-51.mp4?ex=659b19b9&is=6588a4b9&hm=0a13fa1ddaa8e16735602f165b44b79c420f1059671452508386518e904a8657&
> Added in-game Script Editor

- MainModule/Server/Core/Functions.lua
Reverts Epix-Incorporated/Adonis#1326
> Revert "String Matching Fix"

- MainModule/Client/UI/Default/Window.rbxmx
I made it where so if there is zero text there then it just won't show up (this is because it's doesn't need to be shown and is annoying)
Proof Of Functionality
https://github.com/Epix-Incorporated/Adonis/assets/122803145/54c216bb-279d-4edb-860d-89876f46c9e2
> Removed blank description displaying

- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Default/Window.rbxmx
Make list texts be able to be clicked
> Make list texts be able to be clicked

- Loader/Loader/Loader.server.lua
- MainModule/Client/Client.lua
- MainModule/Server/Server.lua
> Make Client accept raw Lua code clientplugins

- MainModule/Server/Commands/Moderators.lua
I made it so jail color actually shows.
> Fix jail color not working

- MainModule/Server/Commands/Fun.lua
I made three new properties to the infect command: (these are all optional)
1. Speed (WalkSpeed)
2. Health
3. JumpPower
PoF:
> Add three properties to :infect

- MainModule/Server/Server.lua
> Well this wasnt supposed to happen

- MainModule/Server/Commands/Moderators.lua
This fixes it where long ping clients do not show up at all or show up very late.
This also gives a much more accurate value of the real ping because it's derived from the raknet packet ping and not the Adonis request ping
> Made commands use better, more accurate and functional ping check

- MainModule/Client/UI/Aero.rbxmx
- MainModule/Client/UI/Rounded.rbxmx
- MainModule/Client/UI/Steampunk/Window.rbxmx
- MainModule/Client/UI/TransBlack/Window.rbxmx
- MainModule/Client/UI/Windows XP.rbxmx
I am fixing every bug with the Description in every theme
I'm unable to get proof since it's a lot of stuff, but I did test them and they did work.
> Mass RichText and Empty Description Fix

- MainModule/Server/Plugins/Anti_Cheat.lua
> It's a number not a string

- MainModule/Server/Server.lua
> Tell mainmodule and loader version on boot

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Plugins/Misc_Features.lua
Add flynoclip as a command name to fly and make flyclip an alias
> Add flynoclip as a command name to fly and make flyclip an alias

- MainModule/Server/Dependencies/Assets/Quacker.meta.json
This makes it more performant, lags the server less and more network friendly
> Made quacker be on the client

- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Steampunk/Window.rbxmx
- MainModule/Client/UI/TransBlack/PrivateMessage.rbxmx
- MainModule/Server/Dependencies/Assets/AnimateAvatar.server.lua
- MainModule/Server/Plugins/Anti_Cheat.lua
- MainModule/Server/Plugins/Debug_Specific.lua
> Remove cpcall v2

- MainModule/Server/Core/Process.lua
> Optimise yanderedev code

- MainModule/Client/Core/UI.lua
- MainModule/Client/UI/Colorize/NoEnv.model.json
- MainModule/Client/UI/Colorize/init.lua
Fixes issue with NoEnv with module themes. (after 20 months!!!)
> NoEnv fix for modules.

- MainModule/Client/UI/Default/UserPanel.lua
I am too tired to write anything to describe this pull request.
> Make the Entry UI look a lot less weird

- MainModule/Server/Core/Admin.lua
Fixes logic issue where using `nil` would cause every player in-game to be selected. (Resolves #1409)
> fix(Admin.lua): RunCommand logic fix

- MainModule/Client/UI/Default/UserPanel.lua
Adds the ability to search inside list settings and also see the count of how many values are inside said list at the top!
> Setting list search additions.

- Loader/Config/Settings.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- Adds WarnDangerousCommand to settings
- That's all
- Will add warning functionality sometime in the future
> Add Dangerous command option

- MainModule/Server/Dependencies/Assets/AnimateAvatar.meta.json
- MainModule/Server/Dependencies/Assets/BunnyHop.meta.json
- MainModule/Server/Dependencies/Assets/Fly.meta.json
- MainModule/Server/Dependencies/Assets/FlyClipper.meta.json
- MainModule/Server/Dependencies/Assets/HatPets.meta.json
- MainModule/Server/Dependencies/Assets/Illegal.meta.json
- MainModule/Server/Dependencies/Assets/Quacker.meta.json
- MainModule/Server/Dependencies/Assets/Seize.meta.json
- MainModule/Server/Dependencies/Assets/Singer.meta.json
- MainModule/Server/Dependencies/Assets/Slippery.meta.json
- MainModule/Server/Dependencies/Assets/Spinner.meta.json
- MainModule/Server/Dependencies/ClientLoader.meta.json
- MainModule/Server/Dependencies/ClientMover.meta.json
- MainModule/Server/Dependencies/LocalScriptBase.meta.json
- MainModule/Server/Dependencies/ScriptBase.meta.json
Change the rojo meta.json files properties from Disabled (old) to Enabled (new)
> Change meta files from Disabled to Enabled

- MainModule/Client/UI/Default/Window.rbxmx
> Fix text being editable in lists

- MainModule/Client/Plugins/Anti_Cheat.lua
- MainModule/Server/Commands/Moderators.lua
Some other things that expect GetNetworkPing to be in ms that are resolved here.
> Use :GetNetworkPing() accurately

- MainModule/Server/Plugins/Cross_Server.lua
also included arguments to optionally disable auto refresh
PoF
https://github.com/Epix-Incorporated/Adonis/assets/50679909/4f7802c8-4a95-4334-b776-9ca66d68ae1e
> Make the text selectable in :serverlist

- MainModule/Server/Commands/Moderators.lua
PoF
https://github.com/Epix-Incorporated/Adonis/assets/50679909/1a124ab2-e157-45d7-9e0d-a5645f6e403f
https://github.com/Epix-Incorporated/Adonis/assets/50679909/6cdd2856-602e-4638-834e-e509683f811f
> Add a duration to :mute (as well as notify the person being muted)

- MainModule/Server/Plugins/Cross_Server.lua
- MainModule/Server/Plugins/Server-SoftShutdown.lua
Creates commands to allow restarting all servers. Can be used after an update is deployed as an example.
> Implement a global restart system.

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Process.lua
This pull request makes the incognito mode back visible, allows mods to get access to the list of incognito players, and makes incognito mode work yet again.
> Fix incognito mode.

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
> :banlist text selectable, :timebanlist actually giving reasons, and specified if a ban is a global ban or a server ban

- MainModule/Client/UI/Default/Alert.lua
Reverts Epix-Incorporated/Adonis#777
roblox seems to have made this one public again so revert for nostalgic reasons
and not as scary
> Revert "Replace the alert sound in :alert"

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/Assets/BotBrain.rbxmx
Revert actor usage due to little performance change and overhead. Should fix issues where it would freeze/crash in studio on some PCs.
PoF:
https://github.com/Epix-Incorporated/Adonis/assets/64731916/558ec059-75b3-457c-8fc5-bffa52545c18
> Revert actor change from BotBrain.

- .github/ISSUE_TEMPLATE/Bug_Report.yml
Add device option to bug report
> Add device option to bug report

- MainModule/Client/UI/Default/UserPanel.lua
Also replaced some waits with task.wait
> Added placeholder texts for aliases and keybinds

- MainModule/Client/UI/Default/Window.rbxmx
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/DoubleLinkedList.lua
> Code quality improvements

- MainModule/Server/Shared/FiOne.lua
Update FiOne and use JIT for it
> Update FiOne and use JIT for it

- MainModule/Server/Plugins/Server-SoftShutdown.lua
Resolves error shown below where reserved servers (not created by softshutdown) would error due to not being a reserved server used for teleporting back.
> Fix error with SoftShutdown process

- MainModule/Server/Commands/Moderators.lua
the capitals in the aliases make no sense for them to be there
no PoF needed since im only changing command aliases
> Change command aliases for ShowTrelloBanList

- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
> luau string builtins

- .gitignore
Blacklist more Rojo build/compile files
> Blacklist more Rojo build/compile files

- MainModule/Server/Plugins/Anti_Cheat.lua
- MainModule/Server/Plugins/Cross_Server.lua
- MainModule/Server/Plugins/Debug_Specific.lua
- MainModule/Server/Plugins/FindExistingObjects.lua
- MainModule/Server/Plugins/Misc_Features.lua
- MainModule/Server/Plugins/Server-SoftShutdown.lua
- MainModule/Server/Plugins/Urgent_Messages.lua
setfenv removal as well as some readability upgrades around plugins
(the for iv loops errored in debug_specific btw so thats fixed too)
> Plugin clean-up

- MainModule/Server/Dependencies/Loadstring/LuaX.lua
Fixes #1495
Fixes parser expression which require lookahead buffer
> Fix invalid lookahead buffer handling

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Process.lua
removing \n from kick messages + ;nil description correction
> removing \n from kick messages

- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Functions.lua
Yuh so I added safe integration for user ids in all commands (removing the need for userid-, ps i didnt remove this)
Also fixed the brokey Settings.Prefix shit in the cmds info page and changed the italic so that it is ACTUALLY READABLE (cough scel.)
the image of me banning and unbanning erica using her name and id
(ps i fixed the 6 billion edit thing)
> Enhance user ID integration and fix command info display issues

- MainModule/Client/UI/Aero/Notification.rbxmx
- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Steampunk/Notification.rbxmx
- MainModule/Client/UI/TransBlack/Notification.rbxmx
- MainModule/Client/UI/Unity/Notification.rbxmx
- MainModule/Client/UI/Windows XP/Notification.rbxmx
- MainModule/Server/Core/Functions.lua
Pretty problematic to defualt notification ui to have a time if you cant specify a time in the command, and its been like this for a long time
> Fix floating points and revert default duration to notification UI

- MainModule/Client/Client.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Client/Plugins/Misc_Features.lua
- MainModule/Server/Plugins/Misc_Features.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/Service.lua
Remove cPcall
Has support for usage for userplugins
> Remove cPcall

- MainModule/Server/Core/HTTP.lua
switched from sending a request to google to built-in HttpEnabled
> HttpEnabled view

- .editorconfig
Fix editorconfig for all files
All files now use lf as lineending in IDE and add settings for TOML too
> Fix editorconfig for all files

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Dependencies/Assets/Singer.meta.json
more consistent with rest of deps + wont error if adonis is ingame but not loaded
> Singer localscript changes

- MainModule/Client/Client.lua
- MainModule/Server/Server.lua
Reallocating a large table many times causes big lag
> Ootimie server changelog conversion

- MainModule/Client/Core/Anti.lua
> Protect metamethod detectors

- MainModule/Server/Core/HTTP.lua
reverting #1514 beacuse roblox is retarded?!?!?
> revert httpenabled

- MainModule/Server/Commands/Moderators.lua
Some small changes I dont really need to explain (you can look yourself)
No PoF needed
> Update to :bans

- MainModule/Server/Core/Remote.luau
> Made Remote.MakeLocal parent to PlayerGui instead of Player

- MainModule/Server/Server.luau
we are professionals. 💪 (also a little faster than pairs())
> ipairs iteration for arrays

- MainModule/Server/Commands/Moderators.luau
If issue, blame/contact @purple_creativity
> MADE MORE LISTS SELECTABLE

- MainModule/Server/Core/Process.luau
> Set Removed to true  when player fails a Join Filter

- MainModule/Server/Commands/Moderators.luau
PoF
https://github.com/user-attachments/assets/e91c744d-f169-4098-9f55-5b21aeae688f
> Made :invisible also make currently equipped tool invisible

- MainModule/Client/UI/Aero/Output.rbxmx
- MainModule/Client/UI/Default/Output.rbxmx
- MainModule/Client/UI/Rounded/Output.rbxmx
- MainModule/Client/UI/Steampunk/Output.rbxmx
- MainModule/Client/UI/Unity/Output.rbxmx
- MainModule/Client/UI/Windows XP/Output.rbxmx
- MainModule/Server/Commands/Creators.luau
Remove output titles displaying, except for when embedded
> Remove output titles

- Loader/Version.model.json
- MainModule/Server/Core/Admin.luau
Reverted a change made in #1539
> Fixed alias arguments

- MainModule/Server/Commands/Players.luau
The logic in the Join command beforehand was not working. It's now fixed, so it actually functions.
> Fix Join command

- MainModule/Server/Commands/Players.luau
Minor Changes
BrickColor List and Material List change to Selectable
> Made mats & colors list selectable

- .github/workflows/publish.yml
Make sed turn of nightlymode flag in loader
Complementary pull for #1647
> Turn off nightlymode for release

- MainModule/Server/Core/Remote.luau
Fixes the client not being able to get any default settings from the server.
> Fix default settings pooling

- MainModule/Server/Core/Core.luau
Fixes #1671
PoF:
PoF script:
```lua
task.wait(7.5)
_G.Adonis.Access("Hello", "Service").Test = false
task.wait(5)
print(_G.Adonis.Access("Hello", "Service").Test)
```
> Fix _G API Access write

- MainModule/Server/Commands/Fun.luau
This is for the future change when Gerald would be added to deps. Allows allows Users to locally add Gerald if they want
> Allow local loading of Gerald

- .github/labeler.yml
Apparently RegEx case group modifiers are not supported with the RegEx implementation in labeler.
@Expertcoderz @Dimenpsyonal
> Remove incompatibility

- MainModule/Client/Client.luau
For some reason warning logs were not handled properly like in the server.
> Fix client side warn handling

- MainModule/Server/Server.luau
Fixes  #1632
Also prints the reason why the server shut down.
> Fix Adonis cleanup not being editable

- MainModule/Client/Plugins/Misc_Features.luau
- MainModule/Client/UI/Default/Profile.luau
- MainModule/Server/Core/Admin.luau
- MainModule/Server/Core/Core.luau
- MainModule/Server/Core/Functions.luau
- MainModule/Server/Core/Variables.luau
- MainModule/Server/Plugins/Debug_Specific.luau
- MainModule/Server/Plugins/Misc_Features.luau
- MainModule/Server/Shared/Service.luau
- Remove unused stuff
- Move scel accounts to variables
- Fix blank prefix not working
- Move nuke function loading to proper place
- Optimise assert
- Optimise ExtractLines
- Deprecate altunpack
- Small misc style improvements
PoF:
> Small misc fixes and improvements

- MainModule/Server/Dependencies/Assets/Fly.client.luau
#1595 accidentally changed the fly script in a way which breaks it.
Fixes #1649
> Fix `:fly` being broken

- MainModule/Server/Core/Remote.luau
Fixes loadstring not showing Lua errors, errors not being correctly labeled and trying to show invalid errors if function call works.
> Fix terminal error hadling

- MainModule/Client/UI/Default/PrivateMessage.luau
Non-temporary users like guests and studio test users do not have profile pictures.
> Only show profile picture for non-temporary users

- MainModule/Server/Core/Logs.luau
Allow tabtotype to be updated by plugins.
> Allow tabtotype to be updated

- MainModule/Server/Core/Functions.luau
- Fix invalid `CharacterAppearanceId`
- Fix archivable
- Fix backpack
- Fix kick
- Fix isa
- Fix temporary users
> Fix fake player properties

- MainModule/Server/Core/Admin.luau
Fix donor perks not updating live
> Fix donor perks not updating live

- MainModule/Server/Core/Core.luau
- MainModule/Server/Plugins/Urgent_Messages.luau
Sequel to #699 that I should have done a long time ago. But it's finally here now.
> Use a datastore cache for Adonis Alerts

- MainModule/Client/Core/Remote.luau
- MainModule/Server/Commands/Moderators.luau
Fix `:removecamera` not working
> Fix `:removecamera` not working

- MainModule/Server/Commands/Fun.luau
Fix the handling of blocking the respawning of character.
PoF:
> Fix respawn block handling

- Loader/Config/Settings.luau
- MainModule/Server/Dependencies/DefaultSettings.luau
Better clarify messages description
> Better clarify messages description

- MainModule/Server/Core/Process.luau
Only show command errors during debugmode
> Only show command errors during debugmode

- MainModule/Server/Core/Admin.luau
Fix disguise changing others usernames
> Fix disguise changing others usernames

- MainModule/Server/Shared/DoubleLinkedList.luau
- MainModule/Server/Shared/GoodSignal.luau
- MainModule/Server/Shared/Typechecker.luau
Use JIT compiler optimization for Linked List, GoodSignal and Type Checker modules
> Use JIT compiler optimization for Linked List, GoodSignal and Type Checker modules

- MainModule/Server/Commands/Admins.luau
- MainModule/Server/Core/Functions.luau
Fixes both #1788 and [this bug report in the discord](https://discord.com/channels/81902207070380032/1319657563830353931)
> Some fixes

- MainModule/Server/Core/Functions.luau
> Fix argument handling AGAIN

- MainModule/Server/Dependencies/TrelloAPI.luau
- MainModule/Server/Shared/Changelog.luau
> Merge v261.3 to release

- MainModule/Server/Commands/Fun.luau
Changed from incorrect "Lily White" to "Lily white"
PoF:
> Fix BrickColor typo inside sing command

- MainModule/Server/Commands/Fun.luau
> Fix :oddliest

- MainModule/Server/Plugins/Anti_Cheat.luau
Experimental features should be based on nightly status not debugmode.
> Convert test case to nightly mode

- .github/alerts.deploy.project.json
- .github/workflows/publish.yml
Fixes  #1651
Add a secret for `ALERTS_MODULE_ID` that is `8096250407`. Coresponds to https://roblox.com/library/8096250407/Adonis-Alerts-Module
> Update urgent messages module on publish

- build.bat
- build.sh
This is not strictly necessary but is very useful
> Update Roblox STD before lint

- MainModule/Server/Commands/Donors.luau
Reverts Epix-Incorporated/Adonis#1776
> Revert "add !sit command"

- MainModule/Client/UI/Default/Profile.luau
- MainModule/Server/Shared/Changelog.luau
- MainModule/Server/Shared/Credits.luau
I asked a maintainer before opening this PR, but I just changed my github username from ScriptedConnor, to convxors. Just wanted to update the credits here in Adonis with my new username.
> Github Username Changed

- SECURITY.md
Link to message: https://discord.com/channels/81902207070380032/993393893699751957/1216876488964571196
> Update SECURITY.md to match CoasterTeam's message

- MainModule/Server/Commands/Players.luau
> Fix command aliases not showing

- MainModule/Client/Client.luau
Changes Kill's recursive loop to a replacement that doesn't cause memory leaking.
> Replacement for Kill recursive loop

- MainModule/Server/Core/Admin.luau
- MainModule/Server/Core/Commands.luau
- MainModule/Server/Shared/Changelog.luau
Reverts Epix-Incorporated/Adonis#1852
> Revert "Fix invalid admin level giving no warning"

- MainModule/Server/Commands/Moderators.luau
;fix is so vague and makes no sense
No PoF needed since this is just a name change
> Change name from ";fix" to ;resetlighting

- Loader/Loader/Loader.server.luau
- MainModule/Server/Core/Core.luau
- MainModule/Server/Dependencies/ClientLoader.client.luau
- MainModule/Server/Dependencies/ClientMover.client.luau
- MainModule/Server/Plugins/Misc_Features.luau
- MainModule/Server/Server.luau
- MainModule/Shared/Service.luau
The pull request to move the shared folder was merged when it was not ready. This fixes it anyways
PoF:
> Fix moving of shared folder bricking Adonis

- MainModule/Server/Commands/Moderators.luau
- MainModule/Server/Core/Variables.luau
Made :view persist when the target user respawns
Also added a "persist" argument
PoF:
https://github.com/user-attachments/assets/953cefad-a76b-4cc5-8d3d-4e4a829c831b
> :view persists when the target user respawns

- MainModule/Server/Commands/Fun.luau
- MainModule/Server/Dependencies/Assets/LinkedSword.rbxmx
Made :sword be able to use custom damage if supplied
PoF:
https://github.com/user-attachments/assets/428a1568-f776-43e9-b840-7f7d375c04fa
> :sword using custom damage

- MainModule/Server/Server.luau
- MainModule/Shared/Service.luau
Fixes errors caused by multiprefix that are not accounted for.
> Fix backwards compatibility for command prefix

- MainModule/Server/Core/Admin.luau
- MainModule/Server/Plugins/Misc_Features.luau
This makes the core modules cleaner by moving the functionality to plugins like backwards compatibility features should be.
> Move legacy `Settings.CustomRanks` conversion to misc features command

- Loader/Loader/Loader.server.luau
- MainModule/Client/Client.luau
- MainModule/Client/Plugins/Anti_Cheat.luau
- MainModule/Client/UI/Default/BubbleChat.luau
- MainModule/Client/UI/Default/List.luau
- MainModule/Client/UI/Default/Message.rbxmx
- MainModule/Client/UI/Default/Music/init.luau
- MainModule/Client/UI/Default/UserPanel.luau
- MainModule/Server/Commands/Creators.luau
- MainModule/Server/Commands/Fun.luau
- MainModule/Server/Commands/Moderators.luau
- MainModule/Server/Commands/Players.luau
- MainModule/Server/Core/Admin.luau
- MainModule/Server/Dependencies/Assets/BotBrain/init.server.lua
- MainModule/Server/Dependencies/Assets/LinkedSword.rbxmx
- MainModule/Server/Dependencies/ClientMover.client.luau
- MainModule/Server/Plugins/Cross_Server.luau
- MainModule/Server/Plugins/Debug_Specific.luau
- MainModule/Server/Plugins/Misc_Features.luau
- MainModule/Server/Plugins/Server-SoftShutdown.luau
- MainModule/Server/Server.luau
- MainModule/Shared/AudioLib.luau
- MainModule/Shared/Service.luau
Fixes:
- Fix loader not loading backup module in nightly
- Fix service printing failing due to invalid metamethod
- Fix missing tostring metamethod from AudioLib
- Fix bot patrolling walk
- Fix sword not working on humanoids
- Fix back command alias order
- Fix audioplayer not showing all songs
- Fix bubble chat keycode name
- Fix message not respecting gui insets
- Fix package command not working
- Also fixes `:skeleton`
- Fix backwards compatibility for shared
Improvements:
- Improved search algorithm for list
- Add unseize as an alias for unseizure
- Increase amount of command aliases visible with `:commands` tooltips
- Enable experimental features in nightly
- Allow studio commands to be ran if debugmode is on
- Store ACLI logs in client logs
- Add logError logs to client logs
- Wrap …
> Misc Fixes and improvements

- build.sh
This fixes on unix based systems the print lines for building being wrong
> Fix build messages being in the same line

- MainModule/Client/UI/Default/UserPanel.luau
about time
POF:
https://github.com/user-attachments/assets/ae826204-941a-4cc8-8815-8c6c436f209a
**note:** edits by maintainers are enabled, if you want to, you can change the messages, alternatively you can post a a comment or review with your requested changes and I'll do it
> add: userpanel settings clear confirmation

- MainModule/Shared/Service.luau
Reverts Epix-Incorporated/Adonis#1935
> Revert "Add "Font" to service so that it can be used in UI elements."

- MainModule/Shared/Service.luau
Reverts Epix-Incorporated/Adonis#1953
> Revert "Revert "Add "Font" to service so that it can be used in UI elements.""

- MainModule/Client/Core/Functions.luau
Proof of functionality
https://github.com/user-attachments/assets/fe9daf1e-3fef-4f79-892a-77a96212eeb8
> Fixed client cape disabling

- MainModule/Server/Commands/Moderators.luau
> Fix fly command double error

- MainModule/Client/Core/Functions.luau
fixes https://github.com/Epix-Incorporated/Adonis/issues/1987
> make the InputBegan KeyBindListener check for gameProcessedEvent
