- Server/Core/Admin.lua
- Server/Core/Variables.lua
As documented in https://developer.roblox.com/api-reference/function/GamePassService/PlayerHasPass
PlayerHasPass will **not work with _new_ gamepasses**. Old gamepasses, created before this change, will still work for the time being however.
We can use [MarketplaceService.UserOwnsGamePassAsync(userId, gamePassId)](https://developer.roblox.com/api-reference/function/MarketplaceService/UserOwnsGamePassAsync) instead for new gamepasses.
As explained in [this public update announcement](https://devforum.roblox.com/t/live-changes-to-game-passes/116918/4), this works for old gamepasses as well, but ONLY if the gamepassID is given instead of the asset ID. This means it is not a drop in replacement for old scripts using old gamepasses via assetid. Luckily, GamePass:GamePassId is a new setting, so …
> Fix New Gamepasses via MarketplaceService:UserOwnsGamePassAsync

- Server/Core/Commands.lua
- Server/Core/Functions.lua
Adonis sometimes lags out and players sit right on a seat again causing the anchored seat to teleport with the player.
> Patch Teleport for reliability

- Server/Core/Functions.lua
When a server has performance issues from handling over 100+ players, the game doesn't seem to instantly have PlayerGui ready and Adonis seems to put a burden on replicating the Adonis client to all players by putting it into the Backpack without waiting until PlayerGui can exist, putting a small but preventable network burst or can kill a server on lots of players joining.
Set to wait 12 seconds unless PlayerGui simply won't show to then use Backpack. PlayerGUI only replicates from server to player only, backpack replicates to every player.
TL;DR, try waiting for PlayerGUI before using Backpack as a fallback to reduce un-necessary replication of the unneeded client to all the players in the server.
By replacing the FindFirstChild to WaitForChild for 12 seconds, Adonis will try to wait …
> Adjust LoadOnClient to try to stay on PlayerGui

- Client/Dependencies/UI/Default/UserPanel.lua
- Server/Core/Commands.lua
Add two new commands:
- NotifyPM (npm/smallmessagepm/nmessagepm/nmsgpm/npmmsg/smsgpm/spmmsg/smessagepm)
- Arguments: player, message
- Makes a small message on the target player(s) screen.
- CountdownPM (countdownpm/timerpm/cdpm)
- Arguments: player, time
- Countdown on a target player(s) screen.
Grammar fix:
- Fixed UserPanel saying "It's purpose is to assist..." to "Its purpose is to assist..."
> NotifyPM and CountdownPM, fix typo in UserPanel

- Server/Core/Commands.lua
Recently roblox added a property called displayname that allows you change the nametag of the player. This will take advantage of the new property by adding it to name and unname.
> Change naming system to use displayname

- Loader/Config/Settings.lua
This Pull request will make it clear in the permission's setting format that multiple custom ranks can be used separated by commas.
> Make it more clear that permission setting can have mutiple custom ranks

- MainModule/Server/Core/Commands.lua
After the removal of Tickets, the currency type parameter on PromptPurchase is ignored and so it is no longer a necessary argument for the Sell command.
> Remove currency argument from sell command

- MainModule/Server/Core/Commands.lua
This adds a :stopcountdown command that will end all currently running countdowns, including Hint Countdowns.
This also switches Hint Countdowns to use `service.StartLoop()` so that they can be more easily terminated when :stopcountdown is run.
> Add :stopcountdown

- MainModule/Server/Core/Commands.lua
- Updated the "uncharaudio" command due to it not recognizing ``ADONIS_AUDIO`` sound in player's HumanoidRootPart.
> Fixed uncharaudio command

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Functions.lua
Roblox [recently deprecated](https://devforum.roblox.com/t/deprecating-loadanimation-on-humanoid-and-animationcontroller/857129) the LoadAnimation method on the Humanoid. This pull fixes any potential animation replication issues by creating the Animator on the server, and also switches all animation commands to use Animators.
> Fix animation replication and use Animator class

- MainModule/Server/Core/Core.lua
- **Replaced** ``getfenv(2).script`` to ``rawget(getfenv(2), "script")``
A random script could easily access the Core's script environment. It's better to retrieve the script via rawget without interrupting the caller's environment.
> Improved Core Security

- MainModule/Server/Core/Commands.lua
- **Added two asserts in two script commands (ScriptBuilder & MakeScript)** Instead of players executing that command when ``Settings.CodeExecution`` is disabled, it now returns an error than silently denying the function.
> Added two asserts in two script commands

- MainModule/Server/Core/Commands.lua
- Prevented the repeat command from being used again inside the repeat command, for example:
```
:repeat 50 0.1 :repeat 50 0.1 :respawn all
```
^ That command usage above would create massive lag and abuse to the Adonis system.
**New version:** Returns an error for overusing the loop command
> Prevented the repeat command from repeating cmd

- MainModule/Server/Core/Service.lua
**Purpose of service.SelfEvent:**
SelfEvent allows the function to manage the event. *(Helpful for developers who wanted an easier method to disconnect the event)*
- **NOTE** SelfEvent function uses RbxEvent !!
For example:
__Kill client after player parent turns into nil__
```
service.SelfEvent(service.Player.Changed, function(self, p)
if p == "Parent" and not service.Player.Parent then
self:Disconnect()
wait(10)
client.Kill("Nil detected")
end
end)
```
Instead of:
```
local event; event = service.RbxEvent(service.Player.Changed, function(p)
if p == "Parent" and not service.Player.Parent then
event:Disconnect()
wait(10)
client.Kill("Nil detected")
end
end)
```
> Added service.SelfEvent

- MainModule/Client/Core/Anti.lua
Made the CoreClears table read only in the client sided anticheat to harden from tampering.
> Made coreclears table read only.

- MainModule/Server/Core/Admin.lua
This fixes a bug that caused all commands that give admin (:admin/:pa/:owner/etc) from working, introduced in #221.
There is no new code here, it simply reverts the file back to its previous state.
> Emergency fix for AddAdmin

- MainModule/Server/Core/Admin.lua
There was a problem with not recognizing players not receiving their admin after changing their username from settings. For example, if player ``Bob`` has a user id ``325324``, Adonis would still recognize him; however, if he changes his username to something else, Adonis would think Bob isn't Bob anymore. This goes to all settings on Mods/Admins/Owners/Creators with ``Username``, not ``Username: UserId``.
> Added another check for Admin.DoCheck

- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Process.lua
Although ``Filter = true`` was set for multiple commands, the "name" argument type was being excluded from the filter which caused some commands, like :makecam, :waypoint, and :maketeam to display unfiltered text to other users.
This pull request will fix this issue and also make a few other command arguments consistent.
> Fix missing filter on multiple commands

- MainModule/Server/Server.lua
I find it interesting that plugins could use ``ServiceSpecific`` for necessary connections with functions/variables.
> Allowed ServiceSpecific to be used in server

- Loader/Loader/Dropper.lua
Added line 12, which disables the Dropper script after Adonis has loaded, so when the loader runs BindToClose(), it doesn't attempt to load Adonis again.
> Disable Dropper after first load

- MainModule/Server/Core/Admin.lua
Fixed the structuring of the CreatorPowers if statement. Previously if the user was given admin it would return true before it could check creator powers. 
I.E. if Sceleratis was in the Moderators table he would forfit his creator powers as it would return true early.
> Fixed structuring of IsPlaceOwner

- MainModule/Client/Core/Functions.lua
The print statements fired whenever the player had ;dizzy ran on them and every time the command looped, causing hundreds of logs on the client.
They are not needed for the commands operation - as far as I know anyway...
> Removed client print statements from ;dizzy

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
This pull request is a follow up of the Datetime/Thru PR, it updates and optimizes the serverdetails.
Serverdetails now display ThirdPartySales and Gravity and FallenPartsDestroyHeight, might add a donor player count too in the future
-- Not really important but important feature: The serverdetails now use the table.insert instead of using the dictionary method.
> Follow up of Datetime PR

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Admin.lua
If future commands or plugins use the LevelToListName function, it may break if run by or on the place owner, the level 5 which is given to the player with the isPlaceOwner() boolean true, is now converted to "Place Owner" in the LevelToListName function
Added :broadcast, which is essentially :chatnotify, but for admins, utilizing the System Title, and automatically running the command on everyone
> Added Place Owner (Level 5) to the LevelToListName func and :broadcast

- MainModule/Client/UI/Default/Friends.lua
- MainModule/Client/UI/Default/Inspect.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Owners.lua
- MainModule/Server/Commands/Players.lua
Adds the following commands:
- **:inspect/:playerinfo <player>** - [Moderators] Opens UI window(s) showing information about the target player(s)
- **!invite/!invitefriends** - [Players] Opens ROBLOX's friend invitation popup
- **:promptinvite/:inviteprompt/:forceinvite <player>**  - [Owners] Same as the target player(s) running !invite
- **!onlinefriends/!friendsonline** - [Players] Opens a window listing the executor's online friends with their location info
- **!getpremium/!purchasepremium/!robloxpremium** - [Players] Opens the ROBLOX Premium Purchase Modal
- **!promptpremiumpurchase/!purchasepremiumprompt <player>** - [Admins] Same as target player(s) running !getpremium
- **!addfriend/!friendrequest/!sendfriendrequest <player>** - [Players] Send a friend request to the specified …
> Player-Related Utility Commands

- MainModule/Server/Commands/Players.lua
They no longer exist on ROBLOX and only spark confusion.
> Remove 'besties' from !usage

- MainModule/Server/Commands/Players.lua
Fixed donor neon command to modify all BaseParts instead of just Parts
I am aware that neon does not correctly create a neon effect in most instances because of meshes, but there isn't much that can be done about this ig
> Donor Neon Command Fix

- MainModule/Server/Core/Process.lua
`PlayerAdded`
Removed Guest check as Guests have been removed.
Replaced spawn function with Routine (line 458). (This [gist](https://gist.githubusercontent.com/evaera/3db84579866c099cdd5bb2ff37947cec/raw/a771c20f35a51188f8625ee8022c7e97b825bfcf/evil.md) from [evaera](https://github.com/evaera) talks about the disadvantages of spawn in detail)
Replaced .Changed Connection on PlayerGui with a GetPropertyChangedSignal("Name") Signal for just firing when the Name is changed.
Changed Loading Error kick to state the kick is from Adonis.
`CharacterAdded`
Commented out the SanitizeCharacter function as it isn't used anymore.
Added a timeout argument for WaitForChild for Player.PlayerGui as if it isn't found in 5 seconds it will output a warning such as, 'Infinite Yield possible on …
> Update Process.lua CharacterAdded/PlayerAdded

- MainModule/Server/Commands/Moderators.lua
Sometimes due to ragdolls (like EchoReaper's R15 ragdoll), commands like kill and smite don't work correctly. This change retains the old behaviour of kill, but manually sets the player's health to 0 as well if they have a humanoid under their character (which they should in most cases), rectifying any issues related to the usage of constraints serving as joints.
> Modified behaviour of kill command

- MainModule/Server/Commands/Moderators.lua
Clones look kinda unnatural without animations. This change maintains the current behaviour of the clone command, except it also gives them the original player's animation pack too.
> Character animations for clones

- MainModule/Server/Commands/Moderators.lua
At the moment, :refresh changes the order of tools, which is annoying, so I fixed that up. Other than that, there's just two other minor amendments I've made: removing the wait(0.1) and just listening for CharacterAdded instead before disconnecting, and looking for Humanoid.RootPart if HumanoidRootPart cannot be found.
> Refresh command update

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
`Moderators`:
Just rewrote all of the previous refresh command.
`Logs`:
Fix typo of `CLoneTable` with `CloneTable`.
> Fixed Refresh, Logs typo fixed.

- MainModule/Client/Core/Anti.lua
Roblox has deprecated HopperBin so it can no longer be used with **IsA("Instance Type")**. https://developer.roblox.com/en-us/api-reference/class/HopperBin
The only way to fix this issue is to change **IsA("HopperBin")** to **ClassName == "HopperBin"**.
> HopperBin patch

- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Shared/Service.lua
`HeadAdmins`:
`GlobalMessage`: Command now displays the title as "Global message from (PlayerName)".
`Service`:
service.__index: Caching the service now uses the `index` argument instead of using `tostring` on the gotten Service as Instances such as `UserInputService` just give `Instance` when `tostring` is used. (services also like `ScriptContext` will give `Script Context` as its their original service)
> Update HeadAdmins.lua / Service.lua

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
`Hat`:
Uses `DonorHat` Function to give the hat. (This can prevent possible hat spam (checks if player doesn't have <15 hats) that could crash the server)
Switch of string based metamethod `:lower()` with `string.lower`.
`Face`:
Checks to see if its a Image and if not it will tell the player that it isn't a valid Face.
Checks to see if its assetTypeId 18 (roblox face type) and will insert.
`DonorFace`:
Fix mismatch of 9 (Place) with 18.
> Improved Hat/Face/DonorFace command.

- MainModule/Server/Commands/Fun.lua
Sp00ky and k1tty currently error used in a place where `workspace.MeshPartHeadsAndAccessories` is enabled.
This edit fixes that issue, while trying to retain old behaviour (decals and guis are not visible).
In places where MeshPart heads/accessories are not enabled, the current behaviour is maintained.
> Fix for sp00ky and k1tty on MeshPart head places

- MainModule/Client/UI/Default/Inspect.lua
- MainModule/Server/Core/Admin.lua
Users can have up to 100 groups, and service.GroupService:GetGroupsAsync(p.UserId) or {} returns all the information about a group, including a full URL to the groups image, a group description, and so on.
This takes up megabytes of space and is a poor use of the DataStore since it's only used in 1 command, which runs for 1 person. Caching this before opening up the UI makes no sense either as it just takes up more time creating a cache for each user.
It does not cause any realistic change whatsoever to the speed of commands
> Remove PlayerData.Groups

- .github/build.project.json
- .github/workflows/build.yml
- .gitignore
- foreman.toml
This PR adds a GitHub action that automatically builds PRs and commits and allows the generated model file to be downloaded. 
Useful so people can quickly test PRs and changes without needing Rojo, and any build errors where the build works on one machine but not another can be quickly spotted
> add github build action

- MainModule/Server/Core/Remote.lua
Just mofified code from the already existing client.Remote.Get("Setting", "settingsname") stuff.
Also moved UpdateList from between the settings code caus' thats a stupid place to put it.
This code is going to be used in the upcoming Audio Player, which will have an Adonis Default Music tab - when I get around to removing the copyrighted music and adding some new tracks.
> Added the ability to client.Remote.Get() default adonis settings

- MainModule/Server/Commands/Players.lua
- Command list window title now shows number of available commands.
- Added !cmdinfo which displays detailed info about a specific command (eg. `!cmdinfo loopfling`). I think this is the only way to view built-in command aliases (for example, `:respawn` can be run as `:re`) without having to look at source code in command modules. Also useful for seeing descriptions of hidden commands like `?adminpls` and whether commands are classed as fun.
> Command-related additions

- MainModule/Server/Commands/Admins.lua
Added bytecode verification just in-case people decide to do something wrong in the script they try and run, will also display the error of what caused the bytecode to not compile.
Type of error they would get:
Did not do SB (I don't think anyone uses this anymore but I'm not sure so)
> Updated Commands (s,ls,cs) [Bytecode Verification]

- MainModule/Server/Commands/Players.lua
Opens the Roblox [avatar inspect menu](https://developer.roblox.com/en-us/articles/avatar-inspect-menu) to view the specified player's avatar items, same as the 'View' function in the esc menu player list.
Aliases: `avatarinspect, viewavatar, examineavatar`
> Add !inspectavatar

- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Hydris.rbxmx
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/Service.lua
Displays times for log commands (`:logs`, `:chats`, etc) in the user's local timezone along with the preferred time format for their locale. Also enables timestamps for chat logs since they were disabled before.
> Local timezones display in logs

- MainModule/Server/Dependencies/Assets/ClickTeleport.rbxmx
Fixes things such as the chat causing the tool to be deleted or triggering a rotate.
> Added fix to prevent GP Events from deleting or rotating

- WebPanel.lua
`WebPanel`:
Cached all server core tables to increase performance.
Created a new `WebPanelCleanUp` function for remote shutdowns to clean when a shutdown is started to do some early cleanup before all players are removed.
Instead of indexing `game` to get `Players` it will use `service.Players`. (not sure why it didn't do this already)
> Performance/fixes inside WebPanel.lua

- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Hydris.rbxmx
- MainModule/Server/Core/Functions.lua
Closes #2 and also fixes a backwards compatibility bug that was introduced with #395.
> Validate cape material enum + bug fix

- MainModule/Server/Shared/Service.lua
When the DateTimeLocaleConfig file of the player's LocaleId is not available, it throws an error.
Because of this error all the logs are broken and wont show up. To fix this, i added a try-catch statement to check for this. If the DateTimeLocaleConfig is not available, it will default to "en-gb".
In my case "nl-nl" (which is my LocaleId) is not a DatetimeLocaleConfig and the logs are broken because of that.
> Fix error locale Timezone unavailable

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Agents have more or less been deprecated since the Adonis Trello board included in the loader by default became defunct, so it may be time to remove them entirely. With the introduction of more customizable custom ranks, the need for agents as a feature has decreased significantly, also.
Although I don't think removing them entirely now would cause too many issues, if people feel that it will cause issues then we could also add a notification of some sort that appears to place owners alerting them that agents will be removed soon before merging this.
> Remove Agents

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Plugins/WebPanel.lua
- WebPanel.lua
`Plugins.WebPanel`:
Added coroutine to prevent yield from WebPanel function.
`WebPanel`:
Added a check to see if it returns "HttpError: Timedout" as if it does it checks if adonis.dev is alive and if not it will stall for 30 seconds then continue, otherwise if alive it will just continue.
`Moderators`:
Added checks to gear command to prevent any non gear from being inserted.
Moved insert to Admins rank. (Should be reasonable as moderators shouldn't need to insert anything from ROBLOX or the creators inventory)
> Update WebPanel.lua / Plugins/WebPanel.lua / Moderators.lua/Admins.lua

- MainModule/Client/UI/Default/ServerDetails.lua
- MainModule/Server/Commands/Moderators.lua
**-- IMPORTANT --**
I do not know if it would be ethical to include an IP Address, it is very possible. I have fear this may be exploitable and make it easier for skids to DDOS servers (already possible)
Second issue: When in studio, the ip could reveal yours to unwanted people, so I don't know if it is good to add one and if we do, we might censor it in studio.
Please note that there may be some bugs, such as error handling, checking if HTTP is on, but on the other hand, this would be a pretty good addition to :serverinfo or :serverdetails.
> Add region information in :serverinfo

- MainModule/Client/UI/Default/Inspect.lua
- MainModule/Server/Commands/Moderators.lua
`Inspect`:
SafeChat checking fix. (uses PolicyService and checks if `Discord` social link is able to be seen by the player, indicating that they are <13 and are unable to see social links)
Micro-optimization to improve some performance. (atleast)
Preloading to some thumbnails Inspect adds.
Switched from `spawn` global to Adonis's `Routine` as `spawn` has a delay in some timing of execution and `Routine` uses `coroutines`, which should make it faster.
> Fixes/Updates to Inspect

- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Core.lua
`Commands.UnTimeBan`:
added `untban`/`untimedban` alias.
`Commands.TimeBanList`:
Fixed bug with removing users possibly preventing the whole command being broken (apparently someones change changed i to _, causing an unknown variable)
`Core` (line:1069):
Added persistent `Table` table for untimeban related removals.
`Commands.Usage`:
Add new usage `Timeban` to let people understand what timebans (d/h/m/s) does.
> Timeban Fixes/Updates, new Usage.

- MainModule/Client/UI/Default/PrivateChat.lua
- MainModule/Server/Commands/Moderators.lua
`PrivateChat`:
PeerList now shows `DisplayName`(s) of the Player(s) alongside their name. (Example: FxEok (fxe))
Chatting user also has their DisplayName with the same format as the PeerList.
`Moderators`:
Disable the Hidden feature on PrivateChat command as its working now.
> Added DisplayNames to PrivateChat

- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/Service.lua
`Service`:
Add `ccuser44`'s old pull from a few months ago into this as they haven't ever resolved the conflict (https://github.com/Sceleratis/Adonis/pull/333)
`Server/Process`:
Removed guest checks.
Switch from # (len) to utf8.len+utf8.nfcnormalize (what Roblox does to check chat lengths in ChatModules), many chinese/other unicodes actually exceed this limit with #/string.len and utf8 is a way to fix it so switching should fix many false kicks.
> Fix filtering/Chat limit kick.

- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Default/Notepad.lua
- MainModule/Server/Commands/Players.lua
- List UIs can now have window title buttons.
- Added a 'help' title button to cmd list that shows usage info.
- Increased the default window size of lists.
- Text size customization for notepad UI.
> Help button for command list + Notepad update

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Commands/Moderators.lua
`ESP`:
Added Overhead NameTags.
Optimizations to ESP's internals.
Switched from `service.New` to prevent wrapping checks that shouldn't happen.
Added `Heartbeat` Waits for ChildAdded/Other events to actually replicate instead of instantly checking.
Also switched from checking for the Humanoid class to using `GetPlayerFromCharacter` for more consistency.
Example of the new Overheads:
> [Client/Core/Functions] : ESP Updates

- MainModule/Server/Core/Functions.lua
The function now supports packages as it replaces the character with a HumanoidDescription. However, custom in-game custom characters (e.g. from :char or an avatar editor) are no longer supported. (This can be fixed by updating :char to change the HumanoidDescription, which I may or may not do later. This should also fix :r15.
> Updated ConvertPlayerCharacterToRig()

- MainModule/Client/Core/Functions.lua
`Nametag l: 179`:
Fix error while removing ESPObjects, seemed like an ESPObject was in nil and the parent thus was going to nil which was no parent so it was unable to `FindFirstChild` a child as it was nil.
> ESP Error fix [Nametag removal]

- MainModule/Server/Core/Functions.lua
Now works with :char and no longer broken.
> Fix ConvertPlayerCharacterToRig

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- `:resetbuttonenabled <player> <true/false>` [Moderators] - Allows the reset character button in esc menu to be disabled or enabled
- `:rbxnotify <player> <duration> <text>` [Admins] - Sends a Roblox default notification using StarterGui:SetCore()
- Updated !usage.
- `!notifyme <message>` [Players] - the same as running `:notify me <messsage>`; intended to be used as custom feedback for running aliases/keybinds.
> Add :resetbuttonenabled and :rbxnotify (and other stuff)

- .github/workflows/build.yml
pretty sure it wouldn't work anyway as secrets aren't provided to prs, but the workflow would appear like it failed so might as well
> don't upload to webhook if event is a pr

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Plugins/Cross_Server.lua
- MainModule/Server/Shared/Service.lua
This is quite a long one.
`Admin`:
cached `type` check and checked for string first instead of number.
Changed from `next` to `pairs`.
Removed useless variables.
`Process`:
Changed from using `tostring` on the `player` instance to indexing the `Name` property. (Most likely some sort of RBXLocked/Non-fe trace)
Changed to some `cached functions` Init sets that weren't being used in some parts of the code of Process.
Removed `DataStoreUpdated` as its used only once inside `CrossServer`.
`Process/Command`:
Removed variables that were never used.
Changed from `string metamethods` to `string library` functions for some optimiations.
Spaced out table contents for more readability.
Spaced out `Tracktask` for more readability inside Command.
`Remote`:
Spaced out table in `ProcessCommand` for more …
> Admin/Remote/Process/Service/CRS Updates

- MainModule/Server/Commands/Moderators.lua
This change updates the teleport command to edit the character's HumanoidRootPart's CFrame, instead of using :MoveTo(). This fixes server-sided anti-exploits flagging players for being teleported, as they use CFrame to calculate this.
> Update Teleport to CFrame

- Loader/Config/Settings.lua
- MainModule/Client/Core/UI.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
settings.DefaultTheme = "New Userpanel" -- Theme to be used as a replacement for "Default". The new replacement theme can still use "Default" as its Base_Theme however any other theme which references "Default" as its redirects to this theme.
Base_Themes now use the closest modulescript rather than Default's or the one specified in the theme.
> Added DefaultTheme setting and improved Base_Theme's functionalities

- MainModule/Client/UI/Default/Explorer.lua
- MainModule/Client/UI/Default/ServerDetails.lua
- MainModule/Server/Core/Remote.lua
- Slight enhancements to the game explorer window, including better deletion handling
- Fixed permission checking issue for the server details window 'Open Game Explorer' button @GalacticInspired  (originally allowed for Level < 300 admins to access the game explorer via :serverinfo without proper perms to use :explorer)
Random fact: this is my first time ever using `self` in Lua code.
> Explorer improvements + permission fix (serverinfo UI)

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Plugins/Cross_Server.lua
plus some other things
1.  The `:headadmin` command now properly says that the person is now a head admin instead of an owner
2. Change the mention of the owner rank in the loader config to HeadAdmin (also removed the helper bit from `descs.SaveAdmins` as this would confuse people as helpers aren't a thing anymore)
3. Fix typo in the args for `:vote` and `:crosservervote` (anwser1)
4. The `:unadmin` command now has `:unheadadmin` as an alias
> Rename owner rank mentions in loader to headadmins + typo fixes

- MainModule/Client/UI/Default/Countdown.lua
It's better now.
Fixed the issue with wait(1) creating a cumalitive error. The end time becomes (un)noticably a few seconds seconds slower that the one inputted. :countdown 120 would realistically be :countdown 125 because of how dumb wait(1) is.
Fixed the mute button so that it displayed central on all themes. This has been an issue on all themes which didn't manually correct it, such as rounded, since the mute buttons creation.
Shout out to all the themes which did correct it using a probably worse method than the one I came up with. Please read it to see the sheer size of my brain. It's incomprehencable!
> Made :countdown better

- MainModule/Client/UI/Default/PrivateMessage.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Shared/Service.lua
`Moderators`:
Moved `small message` command to Admins as for some reason it was for Moderators. (Address this inside changelogs to avoid confusion of actual game moderators using this?)
Removed using `tostring` on player instances to use `Name` property.
ClearGuis command now uses coroutines to prevent any possible yielding.
Messagers/etc that publicly show your name now can support DisplayNames+Name. (format: `%s (@%s)`, arg1: displayname arg2: real name)
`Service`:
Uses `table.pack` to get any arguments that could be varargs to fix some possible bugs on some functions/args that need it. (?)
Caching of some functions.
`SetSpecial` can now return its meta object table for some cases where you don't want to get the variable for it sometimes, example: …
> Service/Moderators Updates.

- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Default/Window.rbxmx
- MainModule/Server/Commands/Moderators.lua
You can now copy the text in `:serverlogs`, `:clientlogs` and `:errorlogs` lists. (highlight and press Ctrl+C) 
_(Currently only implemented for the Default theme.)_
Idea came from @DaEnder although I think he was referring to the output UI?
> Selectable Text for List UIs

- MainModule/Server/Core/Variables.lua
The audios removed in this pr have been removed from the `:musiclist`, as Roblox has blocked the audios for copyright reasons and can no longer be played. Two of the audios were content deleted, this pr also removes them as they are also unplayable.
(these screenshots come from the `:audioplayer`)
> Music list cleanup

- Loader/Config/Settings.lua
- MainModule/Client/UI/Default/YesNoPrompt.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Plugins/Cross_Server.lua
- Adds confirm prompt to `:clearplayerdata` so people don't reset PlayerData by accident (also adds the ability to have a custom title for YesNoPrompt)
- Adds several aliases to some commands as they may be useful to some people as some of these are shorter while still being recognisable to users (not like `:oa` or `:pa` as these were for setting ranks and people were using them in a way to mislead unfamiliar mod/admins into admining them)
- Adds `:globaltimemessage` - it works the same as `:gm` but it allows you to set a custom amount of time on the message
- Enable filtering to the ban commands (will avoid possible moderation action against people's games and Adonis) and #488 will add the ability to add a reason to `:timeban` so we will enable filtering in preperation for that
- Add the …
> Confirm prompt to `:clearplayerdata`, add option to disable cross-server commands, global time messages, some other stuff

- MainModule/Client/Core/Functions.lua
- MainModule/Client/UI/Default/UserPanel.lua
Mostly visual improvements. Note: the Studio icons on _Get Loader_ and _Get Source_ buttons are intended to show they are primarily for Roblox devs and not regular players/admins (to reduce possible confusion), if it doesn't look good please suggest an edit to remove them.
- Keybinds & aliases management interface has better selection mechanics
- Keybinds & aliases added/removed notifications/hints more verbose
- UserPanel window re-opens automatically upon theme setting change
- New ForceField material option for donor capes
> Userpanel update

- MainModule/Server/Commands/Players.lua
- `!rand` - a real number between 0 and 1
- `!rand <upper>` - an integer between 1 and \<upper> (both inclusive)
- `!rand <lower> <upper>` - an integer between \<lower> and \<upper> (both inclusive)
`!brickcolors` (sorted alphabetically)
`!materials`
> Add !rand, !brickcolors, !materials, updated !usage

- Loader/Loader/Loader.server.lua
- MainModule/Client/Core/Process.lua
- MainModule/Client/Core/UI.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Plugins/Cross_Server.lua
- MainModule/Server/Plugins/Debug_Specific.lua
- MainModule/Server/Plugins/Generate_CmdList_JSON.lua
- MainModule/Server/Plugins/Misc_Features.lua
- MainModule/Server/Plugins/Server-Dex.rbxmx
- MainModule/Server/Plugins/Urgent_Messages.lua
- MainModule/Server/Plugins/WebPanel.lua
`Map Restoration Fix`:
Fixed a check I added where I checked if it was a model. (not even sure why I did this)
Added script logs for RestoreMap.
`Admin`:
Replaced some string metamethods on commands that check for commands/set stuff inside with their library counterpart.
Fixed Blank prefixes not hiding/just breaking by checking if the command exists.
> Map Restore/Backup fix, HideChatCmd Fixes, Anti Responding fix?

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
Add timeban alias as per https://roblox.fandom.com/wiki/Ban/In-experience_ban
This adds an alias which is more familiar to players, especially those who have used other admin systems. 
This is what #493 is doing however it didn't an alias for `:timeban` so this will add the alias 
also this makes the duration of `:cm` stays on the screen for depend on how long the message is
> Add timeban alias `:tempban`

- MainModule/Server/Dependencies/LocalScriptBase.client.lua
- MainModule/Server/Dependencies/ScriptBase.server.lua
This time. Unlike last time it uses the script base instead of editing the loadstring module itself.
It has 2 advantages which are: it doesn't have problematic behavior of fenvs, and 2 it doesnt cause issues with bytecode.
> Made it use vanilla loadstring again

- .github/loader.deploy.project.json
- .github/module.deploy.project.json
- .github/workflows/publish.yml
- .github/workflows/publish_loader.yml
Automatically turns off `DebugMode` and uploads the loader (and MainModule, includes #502 as a combined action). Requires a `ROBLOSECURITY` secret to be set.
> Automatic GitHub actions deployments

- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
1. `:cmdinfo` now shows the admin rank a command is associated to and also prevent `nil` being returned by the `Fun` and `Hidden` command checks
2. Fixes a typo in some command aliases introduced in #493 (`permenant`) - should be `permanent`
3. add confirm prompt for `:globalplace`
4. add some donor cmd aliases in case someone makes both `settings.Prefix` and `settings.PlayerPrefix` the same (maybe we should have some sort of in-game notification about this?)
> `:cmdinfo` now shows admin rank for command, fix cmd alias typo

- .github/workflows/pr-stats.yml
https://github.com/marketplace/actions/pull-request-stats
Github action to print relevant stats about Pull Request reviewers.
The objective of this action is to:
- Reduce the time taken to review the pull requests.
- Encourage quality on reviews.
- Help deciding which people to assign as reviewers.
> Pull Request Stats

- MainModule/Client/Client.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/Service.lua
- WebPanel.lua
`Admin`:
switched some string metamethods
Cached to some tables that could possibly get huge (depends if on settings and datastores)
`Commands`:
Switched to getEnv instead of giving the commands env.
`Core`:
`GetDataStore` will now check if you can actually use DataStores in studio first before setting to prevent a big warn pileup if they are disabled.
Switch of `next` to `pairs`
More caching to datastores (datastore entries can get really big in size overtime so having it be pretty fast is essential)
`Process`:
`OnSpawn` and `OnJoin` will run synchronous to prevent yields to the function.
`Service`:
Changing of string metamethods.
> Admin/Commands/Core/Process.lua | Optimizations

- Loader/Config/Settings.lua
- MainModule/Client/Core/Anti.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Shared/Credits.lua
Removed:
Unnecessary `AntiNIL`
Unnecessary Fake player checks.
Unnecessary client side fake name detection.
Changed:
Renamed AntiParanoid to AntiRootJointDeletion and set to true.
Added:
_ClientSide Anti-Cheat:_
- Anti Anti Kick. Will kick anyone who uses anti-kick.
- Anti Anti Idle. Will kick anyone who uses anti-idle.
- Anti Anti FPS detection. Will kick anyone who uses anti-fps detection.
_ServerSide Anti-Cheat:_
- Invalid humanoid deletion. Will undo this and kill the player. Prevents an FE god exploit.
- Invalid root joint / waist joint deletion. Will kill anyone who deletes their rootjoint. This prevents several exploits.
- MultiTool. Stops hackers from equipping multiple tools. To utilise other exploits.
- Inappropriate animation. Stops a sexual character animation.
- Invalid hat …
> [AntiCheat] : Huge addition to server side. Yeeted some client side exploits. Removed unnecessary stuff.

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Remote.lua
title is pretty explaniatory, basically the console will now show all aliases for commands in the Command.Commands table, instead of only the first one.
> made console show all sub-commands/aliases for commands

- MainModule/Server/Core/Variables.lua
Winds of Fjords is actually a modtracker file, but roblox actually doesn't support modtracker files for audio anymore soo
> Updated WOF audio id

- MainModule/Server/Commands/Moderators.lua
If the second argument to `:sword` is "false", the sword(s) given via the command will not be effective against players in the same team with the wielder(s).
~~hope roblox's old sword script inserted by adonis actually works as intended~~
> (Dis)allow teamkill option for :sword

- MainModule/Client/Core/Anti.lua
Apparently adonis wraps all instances and the wrapped version doesnt function like the raw one, which caused this.
Fixed it here.
> Fixed the bug with the anti cheat

- MainModule/Server/Commands/Moderators.lua
- `:ff` command now accepts a second, boolean argument that optionally specifies whether the forcefield is visible. (defaults to `true`)
- some random optimizations
- `:removetools` command now unequips the tool that the target player is currently holding (if any) before clearing it along with the backpack's contents; this behavior prevents some scripted tools from causing issues
> :ff command update and :removetools now unequips tools before deleting

- MainModule/Client/UI/Teams.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
**This depends on my [material icons PR](https://github.com/Sceleratis/Adonis/pull/533) to function.**
Notes on the teams UI:
- It is live-updated from the client.
- Hovering the mouse over a team's name shows the tooltip _"[Auto-Assignable]: true/false"_.
- Hovering the mouse over a team's color display (located left to the name label) shows a tooltip with the BrickColor's name.
- The interface is accessible by moderators, _but_ the create/delete team buttons only work for admins, by default permissions.
> Team management GUI (:teams) + !colorlist fix for Rounded theme

- MainModule/Client/Client.lua
- MainModule/Client/Core/Core.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
- MainModule/Server/Dependencies/Assets/Illegal.client.lua
- MainModule/Server/Dependencies/Loadstring/LuaK.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/Service.lua
Tested everything and seems to be working all good.
`All Server.Core Modules`:
**Client Core won't get this as I feel like it could be a risk and easy way for exploiters to get (you can implement this if you need to)
All Core Modules have an env variable to help prevent unknown globals (for RLSP intellisense globals for Server.lua)
`Core.Functions`:
Rig switching uses PVInstance::GetPivot now
`Admins`:
Defined Routine to prevent intellisense warnings
`Core`:
Fixed ClearAllData possibly not having SavedTables
`Commands.Admins`:
Fixed uncolorcorrect
Improved players command
Fixed tshirt
`Commands.Donors`:
fixed tshirt (variable mismatch)
`Commands.Fun`:
Fixed size command.
`Commands.Moderators`:
Loopheal had an undefined variable.
Shirt alias was removeshirt (?)
removeshirt has its own …
> Command fixes, server change

- MainModule/Client/Core/Variables.lua
- MainModule/Client/UI/Default/List.lua
- MainModule/Client/UI/Default/Profile.lua
- MainModule/Client/UI/Default/Terminal.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
To start with the simple things,
- Added title icons support for List UIs, this should have been done in my Material Icons PR but either I forgot or the changes disappeared.
- Set `ClearTextOnFocus` for the Terminal window command input box to ``false``.
- Re-added as a player command.
- Completely removed country/region code from being displayed. Players and moderators alike do _not_ need this information, it has caused more trouble/questioning than what is worth the satisfaction of individual curiosity.
- Now indicates if the user is the private server owner. Also fixed a critical visual bug with mispositioning.
- The 'View Tools' button under the 'Game' tab now runs ``:viewtools`` internally.
> Resolve controversy & bugs with !profile, some fixes

- MainModule/Server/Commands/Moderators.lua
(yes i know some other countries also use british spellings)
This was done for a couple of reasons after a discussion about this on the discord:
1. It can be confusing for people who do not understand this variant of english.
2. Most programming languages use US english for spelling.
3. Most of Roblox's playerbase is american and not everyone knows british spellings...
e.g. people might know what `center` means but not `centre`
> Update jail command description to not use UK English spellings

- MainModule/Server/Commands/Fun.lua
The "particle" command can't find the texture, because it looks at ``args[1]`` instead of ``args[2]``
There's also this command that uses the first argument https://github.com/Sceleratis/Adonis/blob/master/MainModule/Server/Commands/Donors.lua#L378
perhaps it was copy pasted there?
> Fixed the "particle" command

- MainModule/Client/Core/Variables.lua
- MainModule/Client/UI/Default/CommsCentre.lua
- MainModule/Client/UI/Default/Hint.rbxmx
- MainModule/Client/UI/Default/Message.rbxmx
- MainModule/Client/UI/Default/Notif.rbxmx
- MainModule/Client/UI/Default/Notification.rbxmx
- MainModule/Client/UI/Default/NotificationHolder.rbxmx
- MainModule/Client/UI/Default/Notify.rbxmx
!nh and similar aliases exist
Notifications look better, function way better, and function using ScrollingFrames.
Commiting to only the default theme because of conflicts in *some* other themes (You cannot tween a frames position under the influence of UIListLayout).
Bad screenshot provided
<3
> Communications Centre & Notifications update.

- MainModule/Server/Commands/Fun.lua
Added "head" command to change the package of a player's head, because it didn't exist for some reason.
Basically, I copied "Torso" command, changed the name to "head" and changed the AssetTypeId for it to validate to "17", based on here https://developer.roblox.com/en-us/api-reference/enum/AssetType
then changed some things because the function in Adonis actually couldn't change the Head body part.
> Added "head" command

- MainModule/Server/Commands/Fun.lua
https://github.com/Sceleratis/Adonis/blob/master/MainModule/Server/Commands/Players.lua#L130
As you see, currently it is ``Paint =``
and the command ``:paint`` also has the same thing ``Paint =``, perhaps that this causes a conflict and why that one ``:paint`` command never exists ingame, so I made changes to that, but perhaps that you might want to modify it in a different way, I just did it like this now.
> Removed "color" because it is the same as "paint" and changed "paint" to "playercolor"

- MainModule/Server/Commands/Fun.lua
Added a command called "TransparentPart", which allows you to make individual parts including all accessories and the face.
I've tested the command, it works both on R15 and R6. I've also made it that if someone would be specifying "LeftArm" on a R15 model, that it would delete "LeftArm" from the given input and add "LeftUpperArm, LeftLowerLeg and LeftHand". And for R6 it does the opposite, it would keep "LeftArm" and remove the R15 ones.
However, the part at where I clean up the input, is actually not that optimal. I think I should just put a check if it is R15 and then R6 and then remove everything that would be from R15, and for removing the R6 things, convert them into R15.
Regarding this individual parts thing, I think whenever the actual function for it seems more optimal to keep as …
> Added a command called "TransparentPart", which allows you to make individual parts and more transparent

- MainModule/Client/Client.lua
- MainModule/Client/Core/Core.lua
- MainModule/Client/Core/Functions.lua
- MainModule/Client/Core/Process.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
- MainModule/Server/Server.lua
`Server Core Modules`:
All environment info will be hardcoded instead of sent for convenience.
No more environment being given as Adonis shouldn't need globals inside the scripts environment.
`Variables`:
Switch from next to ipairs
`Commands.Moderators`:
Optimizations and string formatting used.
`Client`:
New table `Changelog`: Stores changelog module contents inside client to prevent table gc spam.
log set to nil to prevent intellisense warnings.
`Client.UI.UserPanel`:
next -> ipairs/pairs
Using new cached Changelog table
> UserPanel, "Admins" Command, server change

- MainModule/Server/Commands/Players.lua
Players should not be allowed to view the server IP at all since "some" people like to DDoS them.
> Disallow players to see server ip in !serverinfo

- MainModule/Client/UI/Default/Profile.lua
To prevent long group names from overlapping with the rank.
> Text truncation for !profile Groups tab entries (visual fix)

- MainModule/Client/UI/Default/Notification.rbxmx
fixes scrollingframe being interactable when holding right click above a notification if that makes sense
> Disable Active when NotificationHolder is created

- MainModule/Server/Commands/Fun.lua
Makes it so that disabling `settings.FunCommands` (in settings module) will disable `:trigger`
> Mark `:trigger` as a fun command

- MainModule/Server/Commands/Fun.lua
Mentioned in a pull request for "transparentpart" command, that I would consider making the "transparency" command make everything transparent by default, and allow the "transparentpart" command to be the more advanced version of the "transparency" command.
However, for now, I guess we can keep the "all" argument for "transparentpart" anyways.
> Change "Transparency" command to make everything transparent

- MainModule/Server/Commands/Fun.lua
I added commands to change the Walk, Run, Jump and Fall animation. You can also specify "R15" or "R6" as argument, to use the default rig animations.
> Added new commands to change some player animations

- MainModule/Server/Commands/Moderators.lua
It now has additional arguments for "volume", "looped" and "pitch"
Another thing is that if the loop is disabled, that it will delete the sound once it has finished playing.
I used ``:Connect()`` for that and then it destroys itself. Not sure if "Debris" should be used, but I tried it as well, both worked alright.
> Enhanced the "CharacterAudio" command

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/HTTP.lua
`Moderators`:
Convert from new format to supported format.
`Admin`:
If a reason is found it will filter the message with the player itself. (tested and will filter)
* This will expose the players name which banned the user.
`HTTP`:
Banned cards support new format to provide a reason.
Banned check on GetPlayers fixed and also continues if the user is banned in order to prevent code from being continued even though they've been kicked.
> Add TrelloBan reason support.

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- Update `Functions.Notification` to use the icon system introduced in #533 
- Shortened some assert messages in `moderators.lua`
- Allows the player command notifications introduced in #513 to be disabled (set `settings.PlayerCommandFeedback` to `false`)
This was done due to the notifications getting spammy and not everyone wants to hear notification sounds whenever someone runs a command on them.
> Update `Functions.Notification` to use `server.MatIcons`, allow player command notifications to be disabled

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
New command for moderators: `:leavelogs`, `:leaves` or `:leavehistory`. These logs (as the name suggests) logs the players who leave the game.
> Feat: Added leave logs

- MainModule/Server/Commands/Moderators.lua
This sets the ReplicationFocus of the player for viewing, which will correctly tell the engine to handle steaming enabled, along with other engine features. Also adds RequestStreamAroundAsync on teleporting, to help prevent steaming pausing (and the player from falling thru the map, if streaming pausing is disabled).
> Better teleporting/view StreamingEnabled support

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Dependencies/Assets/ClickTeleport.rbxmx
self explanatory, it basically re-positions the body movers to the new root part position, preventing them to bring you back where you were
> Made :tp, :to, :bring and :clickteleport not bring you back when flying

- MainModule/Server/Commands/Fun.lua
When using the :resize command, the user's head mesh is also resized along with the part, causing the head to either be way too large or way too small. This PR fixes this issue by checking if the parent of the mesh's name isn't "Head" before resizing the mesh too.
Co-Authored-By: LykaonBotkin <65002282+LykaonBotkin@users.noreply.github.com>
Closes #663
> Fix head size multiplying twice on R6 characters

- .github/workflows/build.yml
When the nightly main module was added, it did not check if it was a pull request to update the main module. This would be unexpected behavior, however, the pull request actions failed, as the pull_request event doesn't have access to secrets.
> Only deploy Nightly MainModule on push

- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
Adds !avataritem which instead depends on humanoid descriptions and is usable with any avatar item, also supporting the new layered clothing (when enabled in StarterPlayer). Replaces !hat, !shirt, and !pants which is now an alias instead.
> Add !avataritem which uses humanoid description

- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Shared/Service.lua
FormatTime now accepts an options table as the second argument, with `FormatString`, `WithDate`, and `WithWrittenDate` arguments.
> Update FormatTime for timeban date strings

- MainModule/Server/Server.lua
You could still rename the mutex to stop it from re-generating.
Also this fixed a bug where the mutex is potentially set to nil because of garbage collection.
> Fixed model mutex

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
I added the commands back that were removed when "AvatarItem" was added. The reason for that is, it caused issues, the previous commands were able to also apply Images that are not Catalog Items to the player, which "AvatarItem" does not. "AvatarItem" is a command specifically for catalog items, and also applies to the HumanoidDescription.
Applying things to the HumanoidDescription may not be ideal for anyone that uses Adonis, perhaps it could break other games, if the previous commands didn't work like how they did before, in terms of what they did.
The previous "hat" command as example, did not apply to the HumanoidDescription, and I think that's fine so. Let "AvatarItem" be the one that makes changes to the HumanoidDescription, also because the HumanoidDescription mostly accepts …
> Clean up issues caused by recent pull requests

- MainModule/Server/Core/Admin.lua
- WebPanel.lua
`Admin + WebPanel`:
More error catching techniques have been attempted to prevent Roblox from erroring due to the API limit.
Changed from `GetRankInGroup` to use `Admin.GetPlayerGroup` for fetching >30 second cached group info to prevent the API limit
> Error catching on group API's to prevent errors.

- Loader/Config/Plugins/Client-Example Plugin.lua
- Loader/Config/Plugins/Server-Example Plugin.lua
It should have already been removed because vargs return the values.
And it may cause issues with debugging because you dont see if a variable is never defined
> Remove the nolint from plugins

- MainModule/Client/Core/Anti.lua
Roblox is really weird and has some edge cases but I fixed it now.
Unless there are other edge cases that this doesn't handle :/
- Fixed a bug where Roblox doesn't produce a proper error message because player is wrongly parented.
- Fixed a potential bug relating to .Idled event (Not sure if this is actually the cause)
Anyways it's really weird how Roblox does this internally so there might be other edge cases. I'm not sure but if you know one you are free to make a pull to fix it.
> Fixed anti-idle and anti-kick once and for all

- MainModule/Server/Commands/Moderators.lua
1. Changed the feedback message if you don't specify a valid argument|
2. Updated the list so it shows just the name of the reverb type and not the full Enum Name
ie. Enum.ReverbType.NoReverb --> NoReverb (As the command says it is case sensitive, this change was made to clear up confusion)
> Minor change to :reverb command

- MainModule/Server/Core/Functions.lua
This should prevent anything like "Group:, Item:, GamePass:, (%s):(%d)" from being passed when a fake player is used.
(for some reason this glitched something with fake players on giving admin and possibly other commands that rely on fake players)
> Fix Fake Players bug

- MainModule/Server/Core/Admin.lua
Adonis used pcall on GroupService, and not the actual intended method
> Make the admin call the method and not a service

- MainModule/Client/Core/Anti.lua
Ok now the Adonis AC is much better.
I could have added more detections, but they are too unstable for Adonis.
Additions
- Anti-dex bypass detection, detects some `anti-dex` bypasses
- Anti-coregui bypass detection, detects if a certain CoreGui anti-detection is in place
- Disallowed Content URLs in CoreGui, _(Idea not invented by me)_
- Proper __index and __namecall detections for Instances _(Idea not invented by me)_
- __eq and __index detections for Enums
- anti-Noclip bypass detection
- __namecall based anti-kick as well, a lot of noob anti-kicks use the __namecall method instead
Fixes:
- Fixed log detection
- Made not parented to players "kick" instead of "crash"
I also thought of adding __namecall __index and __eq checks for strings but it doesn't make much sense to have them for …
> Clientside anti-cheat addisions / fixes

- Loader/Config/Settings.lua
- MainModule/Client/Core/Anti.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Additions:
- Made the logspoof check work for disabling events too, now it is quite hard to bypass
- Implemented #716 expect the seperation of the log message checks (Details below)
- - Added `VirtualUser` and `VirtualInputManager` to disallowed services
- - Added "getrawmetatable" and "setfflag" to log detection strings
Deletions:
- Removed legacy coreclears & corenums and their updater, they aren't used for anything
- Removed legacy unused AntiGui, it was probably supposed to be made functional back in the day, but now it doesnt make much sense because of coregui, besides it would conflict with games if said was ever enabled
- Removed a dublicate tool detection, there was already one, so I removed the dublicate one
- Implemented #733 expect the removing of logservice detections because …
> Important anti bug fixes! and indluded parts of #716 and parts of #733 also fixes anti-dex bypass method 2 kicking all nonadmins

- MainModule/Client/Core/Anti.lua
When this
happened. **It doesn't mean that the AC kicked the player**, **Roblox already kicked the player for AFKing for 20 minutes.** But what happens is that the localscripts continue running, until the .Idled event produces an invalid value. When the player has been already kicked from the game by Roblox, the AC re-kicks them changing the kick message. **This leads to confusion that the Anti-Idle kicked the player from the game which isn't true.**
This pull request makes it so that the AntiIdle stops after the player has been disconnected from the game. And this this will no longer lead to confusion
Also don't worry about the excessive if checks, they can't lead to any "false detections" because they don't controll any detections. They are only to stop simple bypasses from completely …
> Fixed anti-idle for the final time

- MainModule/Client/Core/Anti.lua
These are mostly unnecessary checks. They used to serve a purpose when Filtering Enabled (mid 2018 and before) didn't exist because you should possible hide the local player. But it no longer serves much use to exploiters and causes issues.
> Remove legacy check Anti-Cheat Parent not players from the pre-Filtering Enabled era

- MainModule/Server/Core/Anti.lua
On legacy loaders this was called "AntiParanoid".
> Add support for legacy loader settings

- MainModule/Server/Dependencies/TrelloAPI.lua
Trello has blocked requests to non-api routes from Roblox, and api routes if a Trello token and key are not specified. This PR addresses this.
> Fix TrelloAPI

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Process.lua
- for commands where trello is required, display an error saying that trello isnt configured correctly if it wasnt setup properly or disabled
- `!usage` now has an example for the `@username` argument
> better trello errors + provide example of `@username` in `!usage`

- Loader/Config/Settings.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Dependencies/MockDataStoreService.rbxmx
Useful for testing or if you have a free admin game.
For example on free Admin games (or other games too) you never wan't any datastores to ever save.
> Add option to force use MockDatastore

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- Attempting to run ``:crash``, ``:ban`` etc. on a higher-ranked admin now displays an "insufficient permission level" error hint as a feedback to the executor, rather than doing nothing and leaving them to wonder if the command is working properly.
- Edited and fixed ``:loopkill <player> <num>``. That is, I hope.
- Updated the description of ``:nil`` and made it a hidden command since we don't expect it to be useful in any way nor easily-understood by users.
- Updated the description of ``:explorer``, amongst a few miscellaneous wording improvements.
- And of course, there's the random code formatting improvements here and there.
> Some command feedback-related UX and misc. improvements 

- MainModule/Server/Commands/Moderators.lua
This fixes the issue that the custom shirts given with ``:customshirt`` and etc. can't be removed with ``:removeshirt``
and this also fixes the issue that it doesn't replace a custom shirt if you give yourself a shirt
Basically, the customshirt get a Humanoid clothing tied Instance where its asset ID gets modified.
It's using this as a default ID for the shirt ``855777286``
this for the pants ``855782781``
and this for the TShirt ``6901238398``
What should be done is that Sceleratis should create a shirt and pants that have nothing on it or, idk something, so that we can replace these IDs I just mentioned.
Reason for that is, you won't be able to give yourself this shirt "855777286" and that's why these IDs should be changed in the future.
> Make the custom clothing commands compatible with the HumanoidDescription ones

- MainModule/Client/Core/Process.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
Kinda old and unused; also potentially abusable considering that it isn't ratelimited.
Credit to @fxeP1 for suggesting its complete removal.
> Deprecation of Remote.UnEncrypted

- MainModule/Server/Commands/Moderators.lua
Caused by the script checking for an IntValue only,
This made it so it check for both IntValue and NumberValue
> Fix for :resetstats not resetting NumberValues

- MainModule/Server/Core/HTTP.lua
Fixes issue where HTTP Service occasionally would block calls. Instead, checks for a specific roblox-created error when disabled rather than a pcall failure alone.
> Check for specific http-enabled error for HTTP check

- MainModule/Server/Dependencies/TrelloAPI.lua
By sending a http request to `https://trello.com/1/members/me`, it would return 400 if there was no token. 
Changing this to some constant like `https://trello.com/1/members/trello` will work with a valid app key. With an invalid app key it returns an error. No token is required. 
This PR also adds in a check for httpenabled before running the trello validity check. 
I am open to criticism with this.
> Fix TrelloAPI requiring Token

- MainModule/Client/UI/Default/Settings.lua
- MainModule/Client/UI/Default/UserPanel.lua
The desc for the keybinds setting on the client page was "- Enabled/Disables Keybinds"
I have corrected it to be "- Enables/Disables Keybinds"
> Fixed typo on Keybinds settings description

- MainModule/Client/Core/Anti.lua
- MainModule/Client/Core/Functions.lua
- MainModule/Client/Core/Remote.lua
- MainModule/Client/Core/UI.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Donors.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/HeadAdmins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Anti.lua
- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Core/Remote.lua
- MainModule/Server/Core/Variables.lua
``pairs()`` and ``ipairs()`` are no longer necessary with the introduction of the __iter metamethod.
By how many characters have our file sizes been reduced after killing the pairs? (All figures are approximate.)
Commands\Admins - 420
Commands\Creators - 30
Commands\Donors - 20
Commands\Fun - 1460
Commands\HeadAdmins - 90
Commands\Moderators - 2320
Commands\Players - 210
Core\Admin - 330
Core\Anti - 50
Core\Commands - 50
Core\Core - 210
Core\Functions - 420
Core\HTTP - 80
Core\Logs - 20
Core\Process - 80
Core\Remote - 150
Core\Variables - 20
**Total:** 5960 characters
Core\Anti - 60
Core\Core - 0
Core\Functions - 240
Core\Process - 0
Core\Remote - 20
Core\UI - 70
Core\Variables - 0
**Total:** 390 characters
> Remove all instances of pairs()/ipairs() in core modules

- MainModule/Client/Core/UI.lua
- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Default/HelpButton.lua
- MainModule/Server/Core/Process.lua
Enabled CanKeepAlive for Console and HelpButton; the loading of those GUIs is now handled by Process.FinishLoading instead of Process.CharacterAdded.
And of course there's the massive code improvements.
> Avoid reloading Console and HelpButton GUIs upon respawn

- MainModule/Server/Commands/Moderators.lua
It is currently difficult to tell which players are godded, have altered health, etc. This command makes an automatically updating list of all players and their respective healths. Players are ordered first by max health, then current health, then display name, then username.
> Add a healthlist command

- MainModule/Client/Core/Functions.lua
Why is ender in the fps lock code
> Remove Ender

- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Functions.lua
First Change:
Players removed with the -Name grouping will be subtracted at the end once the full list of players has been collected. This means that first, players do not need to be removed at the end of the list, for example :bring all,-%TEAM can now be written as :bring -%TEAM,all and function the same way.
Second Change:
Additionally, the random and #NUMBER sections have been moved to the end, which ensures both that the random player will not be one already selected, and also will not be one purposely removed with the -Name. This means that a command such as :bring random,-%TEAM,-%TEAM2 will bring a player who is not on TEAM1 or TEAM2, where previously, if the random player was on one of these teams, the command would just bring no players.
Third Change:
Because this reformating may …
> Revised: Edit the way Players are Selected

- MainModule/Client/UI/Default/Music.rbxmx
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Remote.lua
The permissions of !audioplayer global audio now rely on the player's permission to use the :music command, meaning if the player is not allowed to use :music, the player cannot broadcast global audio (to prevent players being able to play music for the entire server even if they can't use :music, which functions the same as global audio in the audio player)
In addition, if a player is not allowed to broadcast global audio, the global audio toggle on their end won't be visible at all. (and the server check is still there and updated for the permission changes)
> Improve !audioplayer global audio permissions system

- Loader/Config/Settings.lua
- MainModule/Server/Core/HTTP.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Default setting state: `false`
Behavior:
* This setting takes effect only when a Trello board is configured and linked with Adonis.
* When `true`, ranks loaded from Trello board lists will be omitted from the admins list (`:admins`).
* When `false`, ranks loaded from Trello board lists will be listed in the admins list in the format "[Trello] *RankName*", eg. "[Trello] Moderators".
> Add settings.Trello_HideRanks

- MainModule/Server/Commands/Moderators.lua
> Rename 'Admin Logs' to 'Command Logs'

- MainModule/Client/UI/Default/Effect.lua
The changes include:
- Changed the default raycast length from 80 to 128 (power of 2 = better)
- Removed all instances of `pairs`
- Edited the `renderScreen` function for defaulting pixel colors to (105, 170, 255) if the raycast was unsuccessful, fixing :lowres
> Fix for :lowres

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Functions.lua
Reduces the attack surface relating to commands that utilize the `Humanoid:ApplyDescription()` function.
Refer: https://create.roblox.com/docs/reference/engine/enums/AssetTypeVerification
> AssetTypeVerification for Humanoid:ApplyDescription()

- MainModule/Client/Core/Anti.lua
A new feature disconnects all player events when a player is parented to nil, which breaks `:unincognito`
This fixes the difference issues caused by: https://devforum.roblox.com/t/disconnect-player-on-removal-from-datamodel/2061753
> Fix support for https://devforum.roblox.com/t/disconnect-player-on-removal-from-datamodel/2061753

- MainModule/Server/Commands/Fun.lua
Fixes support for some guis with https://devforum.roblox.com/t/new-keybinds-for-keyboard-navigation/2069353
Fixes support for some guis with https://devforum.roblox.com/t/notched-screen-support-studio-beta/2074324
Fixes support for auto gui translation for some guis
Ok this will be only applied to these GUIs too lazy to modify the UI code.
Also **normally GUIs should be translated**! The only reason to turn off translation is if you are using a custom translation system or the GUI has no text (*in this case neither has any text which means checking them is innecessary*)
> Add support for new gui features

- MainModule/Server/Core/HTTP.lua
If it doesn't have `www.` it becomes a 301 redirect instead of a success
> Fix `HTTP.HttpEnabled`

- MainModule/Server/Shared/MatIcons.lua
- Made `ROBLOX` to `Roblox`. FIrst letter capitalised ir proper trademark. First is improper use
- Credited `Google LLC` for material icons
> Misc copyright/trademark stuff

- MainModule/Server/Commands/Moderators.lua
**This pull request fixes:**
- Invalid usage of the third function argument (stops conflicting with global function arguments,  stops undocumented instance property behavior)
- `:flynoclip` invalidly using the args table resulting in undesired behavior and lag (if ran on multiple people)
**Fixed by:**
- Function argument bug fixed by using command arguments instead of function arguments
- `:flynoclip` bug fixed by using a custom args table
---------
The fly function invalidly reads the third argument of the command function as a boolean. This works fine if said command is ran via the `flynoclip`
If the :fly command is ran via normal means this is what the `noclip` argument of the function will be a table, it won't be a boolean. The argument `noclip` will be normally this table:
```lua
{ …
```
> Fix error with fly

- MainModule/Server/Commands/Moderators.lua
This makes clearing lag and unnecessary stuff easier than doing `:clear | :clean`
> Made `:clear` additionally also do `:clean`

- MainModule/Server/Core/Core.lua
Users with a negative userid are temporary accounts for which data shouldn't be saved. Currently used by Studio fake players and was used previously by Guests.
> Made `SavePlayerData` only save data for valid players

- MainModule/Server/Dependencies/ClientMover.client.lua
These would still be detected by Adonises remote detector but I guess it's a good idea to immediatly kick them.
Fixes:
> Fixed all public full Adonis bypasses

- MainModule/Server/Shared/FiOne.lua
If we wan't to use a virtual env ever then FiOne calling fenv would negate any of it's benefits.
> Made FiOne use an empty env instead of the fenv for performance and future compatibility

- MainModule/Server/Core/Admin.lua
If a ban is stored in the format Username:UserId, the UserId is not checked because the UserId in the string is not converted to a number. This PR fixes that issue.
> Fix UserIds not checked

- README.md
Markdown files should use as much markdown as possible. Also fixes markdown errors
Also adds:
- Lint visualiser
- Subtitles for Github badges
> Markdown instead of HTML fix

- MainModule/Server/Plugins/Server-Dex.rbxmx
The RawApiJson had two ``}`` extra brackets at the end.
So I removed them.
> Server-Dex: Fix can't parse JSON

- MainModule/Server/Commands/Players.lua
Dependencies instead of Shared folder. That was this simple actually.
Error was: "CountryRegionCodes is not a valid member of Folder "MainModule.Server.Shared".
> Fix for the CountryList commands or "!countries" command (Not working as expected and gives an error upon execution).

- MainModule/Server/Dependencies/Assets/Clipper.client.lua
Idk why changing the root part cframe.. it was causing the character to repeatly go up and down lol.
> Fix for ":noclip" command & the Noclip script (Clipper) along with readability improvements

- MainModule/Server/Core/Core.lua
Groups saving in datastore is the worst feature ever. It makes datastores very bloated
Biggest bruh moment feature
> Don't save groups

- MainModule/Client/UI/Default/Hint.rbxmx
Hint for some reason became bigger without good reason? This seems to pretty much fix it. Although there is a slight font difference
Edit: Apparently it's because Scelratis updated the hint and somehow Roblox makes it weird
> Fix mystery error with hint

- MainModule/Client/Plugins/Anti_Cheat.lua
Also fixes for
```
GetCollisionGroups is deprecated, please use GetRegisteredCollisionGroups instead. More info: https://devforum.roblox.com/t/updates-to-collision-groups/1990215
```
> Fix some potential false flags

- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
Updated the command that shows the synced trello bans.
Changed above command to show a notification instead of creating the list if trello is not configured/enabled.
Changed the trelloban command to make a notification instead of a hint if trello is not configured/enabled.
> Update the trello related commands

- MainModule/Server/Core/Functions.lua
Fixed `service.GetPlayers()` not finding players if given a partial player/display name that includes capitals
> Fix name matching in service.GetPlayers()

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Shared/Credits.lua
This base64 implementation is much faster than the current one.
Benchmark for both with Luau optimisations. \\/
Old: 160.56607509899186 seconds
New: 9.714655200194102 seconds
This one added to Adonis doesn't have all Luau optimisation because Adonis uses fenv. But if anyone wants a Luau optimised one then here it is \\/
```lua
-- Thanks to Tiffany352 for this base64 implementation!
local function base64Encode(str)
local nOut = 0
local alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local strLen = string.len(str)
local out = table.create(math.ceil(strLen / 0.75))
-- 3 octets become 4 hextets
for i = 1, strLen - 2, 3 do
local b1, b2, b3 = string.byte(str, i, i + 3)
local word = b3 + b2 * 256 + b1 * 256 * 256
local h4 = word % 64 + 1
word = math.floor(word / 64) …
```
> Added a better and much faster base64 implementation

- .editorconfig
- .gitattributes
This makes the Github IDE (and other IDEs):
- Trim trailing whitespace (Roblox studio already does this)
- Use linefeed as the line terminator (in case some other IDEs use something else). Fixes incompatibilities with some IDEs
> Made IDEs trim trailing whitespace and use linefeed

- MainModule/Server/Dependencies/Assets/F3X Deps.rbxmx
Currently creating `Seat`s, `VehicleSeat`s and `SpawnLocation`s has bad UX because they have incorrect default values making them hard to distinguish from other parts.
This makes them have the same defaults as studio making them easily differenciable from other parts.
I have created a pull for this in the upstream F3X repository 2 years ago but the repo is inactive so I'm going to add this here as well.
> Made createpart have correct values

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Variables.lua
- Added code to adjust character density based on size to avoid sliding around while small (due to roblox clamping density to 100, if you go below 10% of normal character size you can start to slide. But hey, at least it's better)
- Replaced `Variables.SizedCharacters` with an attribute on the character so it clears when that character is destroyed
> Fix :size causing small players to slide around

- MainModule/Client/UI/BasicAdmin.rbxmx
- MainModule/Client/UI/Mobilius.rbxmx
- MainModule/Client/UI/Rounded.rbxmx
- MainModule/Client/UI/Unity.rbxmx
- MainModule/Client/UI/Windows XP.rbxmx
Reverts Epix-Incorporated/Adonis#1102
The pull request fixed the rojo lint warnings but it breaks the fontsizes for other themes.
> Revert "Megafix Lint"

- MainModule/Server/Dependencies/ClientMover.client.lua
This fixed another AC bypass which hooks in to the Adonis loading functions
> Fixed Adonis AC bypass which disables Adonis

- MainModule/Server/Dependencies/Assets/F3X Deps.rbxmx
The current UX for pasting asset ids in F3X is very bad because they don't work with links. This makes them work with links.
I added a pull request to here as well because upstream F3X might be abandoned.
> Made F3X Texture and Mesh tools extract asset id from links in provided text for better UX.

- MainModule/Server/Commands/Admins.lua
The ":cs" command is useful for a variety of reasons. If I need to display a dependent message during an in-game event, I can use the command to do this easily. It is restricted in the way that I need to rerun this command each time a player joins, and I've had to create some workarounds due to this limitation. While large scripts are not usually ran with :cs, I believe adding a :starterscript command would make things much easier.
> Add ":starterscript" command

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Functions.lua
This makes the legacy chatservice wait for 5 minutes to check if there is a chatservice even if textchatservice is enabled.
This fixes *most* bugs in games where there are multiple chat systems. 5 minutes is probably long enough for most usecases. I could have made it wait for even longer but this seems to suffice.
> Made chatservice handlers wait for 5 minutes. Fixes bugs in games with many chatsystems

- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
This eases datastore usage.
It also fixes a problem where important logs can be cleared out by unimportant ones.
> Made player and donor commands not save in oldlogs

- MainModule/Client/Plugins/Anti_Cheat.lua
- MainModule/Server/Shared/Credits.lua
This fixes the anti cheat crashing players if their console gets a deprecated collision group method warning. It was falsely triggered by matching `getreg` from `GetRegisteredCollisionGroups` in the warning message.
> Add myself to credits

- MainModule/Client/UI/Default/Profile.lua
- MainModule/Server/Commands/Players.lua
This is to adapt with the new Roblox feature, Player:IsVerified(), which was released just 3 days ago, despite of the title still saying Beta, and some games like Arsenal already uses this feature for it's "Premium Servers" feature.
https://devforum.roblox.com/t/isverified-api-beta/2432501
This also includes a way for checking Mail Verified, using the MarketplaceService:PlayerOwnsAsset() to check if the Verified Bonafide hat is owned by the player. (https://www.roblox.com/catalog/102611803)
The code in the backend is a bit inspired from the SafeChat check (xpcall, conditional variable) so the code shouldn't be too messy although if there's still something wrong in the code, feel free to comment the faulty code and suggest a potential fix.
This PR have been tested across one account (my …
> Update !playerinfo command - Mail & Phone/ID Verified Status

- MainModule/Server/Commands/Moderators.lua
Also take BillboardGui inside body parts into account in case of those "over-head GUIs" feature used in-game.
> Update Moderators.lua - for :invisible and :visible command.

- MainModule/Server/Commands/Fun.lua
The bunnyScript was supposed to be renamed **after** the clone, however in this current case it's actually renamed **before** the script gets cloned, thus editing the first script's name causing the further executions to fail. This commit should fix this issue to it's intended function.
> Fix for :bunnyhop not executing more than once

- aftman.toml
idk
but Nightly Fonts are bugged and 7.2.1 has like a publish mistake so I change it to 7.3.0
For some reason the build logs in GitHub say that it's using 7.3.0 but idk
> Change Rojo to 7.3.0 or something

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
This change is a change that Adonis needs. It's a change that will revolutionize any other admin system, because they do not have this.
They do not have that what Garry's Mod has, which I even think is implemented by the Source SDK in the Console. It's quotation support.
Being able to turn this ``"%Team 1"`` into one argument ``%Team 1``.
Previously it would do something like this ``%Team`` and the rest would be for the second argument.
&nbsp;
If you want to select a specific Team for the ``:team`` command.
You'd be unable to select any specific Team because the first argument of ``:team`` gets split after a space.
What this addition does. Is that If you have it wrapped inside a quotation. e.g.
``:team "%Team 1" Team 2``
this would put everyone in "Team 1" inside Team 2.
Notice how I …
> A very good addition to commands, quotation support

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
This finally fixes the issues that Adonis has long had with naming.
Fixes:
and
> Fix naming

- MainModule/Server/Dependencies/Assets/BunnyHop.client.lua
Almost locking hum.Jump using while loops is unreliable, and sometimes the humanoid doesn't even jump because Roblox engine will sometimes get confused whether the character should jump or not.
> Update BunnyHop.client.lua - use GetPropertyChangedSignal

- MainModule/Server/Dependencies/Assets/Fly.client.lua
The commit will reverse commit f0cb4d:
https://github.com/Epix-Incorporated/Adonis/commit/f0cb4ddd50f8fc6f1d51475bf2faa64fe374a4e9
Mentioned commit breaks the fly command and will keep moving you to the void. Caused by feeding Vector3 values into the new AlignPosition and AlignOrientation, causing the values to stay at zero aka nil. The person behind this commit might be using an older or unofficial version of Adonis, or even being misled by the "bGyro" variable name while it's actually AlignOrientation behind the scenes, since only the legacy BodyMover objects request Vector3 for MaxTorque and MaxForce, the newer ones take number values instead. To fix this I removed the tranVec() function that convert numbers to Vector3 values and thus reverting the commit.
Some proofs can be seen that …
> Update Fly.client.lua - Remove the breaking Vector3 transformation function

- MainModule/Server/Shared/Service.lua
- By default the users account locale is `en-us` even if they don't have it on their device which will cause timestampts to be shown in US time. This fixes it by making it so that if the users account locale is default then system locale is used instead.
- Also fixed a bug where the failsafe could fail too. This makes it use `ToIsoDate` which will never fail. Also unsupported locales would not generate an error because they are overritten internally so ISO dates only appear if there is an internal error in Roblox.
> Fixed locale handling

- MainModule/Client/Plugins/Anti_Cheat.lua
This is because recently in my exploit logs systems which is connected to Adonis someone was kicked because of Disallowed content URL in CoreGui but the URL it gets was from one of the gears in StarterPack.
> Update Anti_Cheat.lua - Add StarterPack for CoreGui check

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Functions.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Adds support for:
- CanSend mutes (doesn't need to use the ShouldDeliverCallback in TCS)
- :chatnotify works with TextChatService
- :broadcast works with TextChatService
- Both broadcast/chatnotify escape text as well
> Add more TextChatService functionality

- Loader/Config/Settings.lua
- MainModule/Client/Plugins/Anti_Cheat.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
A maintainer (me) overlooked the flaws of #1186, and merged it before further discussion concluded that it would be a bad idea to implement. This PR undoes #1186, removing the (currently optional and unreleased) detection & rejection of 32-bit Roblox clients.
At best, Anti32bit has highly limited use cases; at worst, its built-in availability as an anti-exploit setting is misleading, as there is a strong risk of rejecting legitimate players on the UWP app from joining experiences.
> Remove Anti32bit

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Plugins/Anti_Cheat.lua
- MainModule/Server/Plugins/Urgent_Messages.lua
I've cleaned up some code to use string interpolation instead of concatenation. Additionally, I have modified the server-side anti-cheat and removed the explicit calls to `tostring`, which I don't think is necessary since it should be called automatically.
> Use string interpolation in favor of concatenation

- MainModule/Client/Plugins/Anti_Cheat.lua
- MainModule/Server/Shared/Credits.lua
Since recent updates many false kicks happened due to how Roblox implemented their Face Camera UI, they started the UI after game scripts were loaded. This commit is going to whitelist the rbxassetid for Camera UI and also the "rbxassetid://0" occuring on some low-end devices.
> Whitelist RBLX Camera SFX - Update Anti_Cheat.lua

- selene.toml
This fixes selene accidentally linting about TestEz files so the lint doesn't have a bunch of unnecessary warnings
> Fix selene linting about TestEz files

- .github/workflows/lint.yml
Currently it uses node12 which is being depracated soon, v2.1 uses node16 which is still supported
> Update setup-foreman to v2.1

- MainModule/Server/Plugins/Server-Dex.rbxmx
The "Filter workspace" searchbox should only search upon pressing enter. Before each time you typed a character it would start filtering, which is very laggy for the client.
> For :dex command, Removed free lag from Dex - The "Filter workspace" searchbox should only search upon pressing enter

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
In a new update Roblox added creator UGC which can be purchased from in game. Due to this update some types of UGC limiteds can be purchased free if they are purchased from the creators game.
A vulnerability appeared which allowed people to steal UGC limiteds by doing this.
The pull #1221 fixed this by disabling the command altogether but introduces more setting bloats (boolean parameters should be avoided). This pull fixes it so that you can still buy items if they are not limiteds avoiding the boolean parameter.
Things that need to be tested:
- Are non-limited UGCs still problematic to buy??
> Make `:BuyItem` only block limiteds

- MainModule/Server/Plugins/Anti_Cheat.lua
`Workspace.RejectCharacterDeletions` was added in https://devforum.roblox.com/t/action-required-workspacerejectcharacterdeletions/2196175/1 and enabled by default on games on May 1st 2023 https://devforum.roblox.com/t/workspacerejectcharacterdeletions-default-transition/2269179 .
RejectCharacterDeletions does the same thing as `settings.AntiHumanoidDeletion`, `settings.ProtectHats` and partially `settings.AntiRootJointDeletion/settings.AntiParanoid`.
Also do not remove `settings.AntiRootJointDeletion` explosions and joint breakers can still break the character so some games rely on it!!
1. Phase 1 ✅ - Remove legacy settings from settings files and suggest alternative in settings file (expect for settings.AntiRootJointDeletion) - Already done in #778
2. Phase 2 🔄 - Make all games after May …
> Disabled protections superseded by `Workspace.RejectCharacterDeletions` on new games

- MainModule/Server/Commands/Moderators.lua
This command works similar to :char, however it will take an OutfitID as a way to get a HumanoidDescription. 
You can get OutfitID by using Roblox Avatar API, for example this is how to get the outfit list of Roblox (User ID 1) which only contains a classic guest avatar: https://avatar.roblox.com/v1/users/1/outfits?itemsPerPage=50
For example this is Outfit ID 19461896 which is a Classic Guest Avatar back in 2011 - early 2016:
> Add :outfit command

- MainModule/Server/Commands/Fun.lua
Didn't test this on R6 so this was left here accidentally. A leftover from the previous command
> Fix accidental mistype of creaper breaking R6

- MainModule/Server/Core/Functions.lua
- MainModule/Server/Plugins/Server-SoftShutdown.lua
If the teleport fails the script doesn't attempt to re-teleport the user leading to them being stuck.
- Part1 - Fix softshutdown not retrying on failure
- Part2 - Switch softshutdown (and maybe other teleports) to [TeleportService:TeleportAsync](https://robloxapi.github.io/ref/class/TeleportService.html#member-TeleportAsync)
- Part3 - Add loading screen for softshutdown servers
> [Part1 of softshutdown fix]: Fix softshutdown failing and not retrying

- MainModule/Server/Commands/Fun.lua
Having humanoids named to `Zombie` is a common de facto way of characterizing certain humanoids as zombies. This add support for that so the infect script doesn't infect those.
> Small fix/improvement to zombie detection

- MainModule/Server/Core/Functions.lua
This used to work but no longer appears to do because at some point Roblox probably changed how Enums work
> Fix longstanding issue with `:bot` animations not working with R15

- MainModule/Client/Client.lua
- MainModule/Client/Core/Functions.lua
- MainModule/Client/Plugins/Anti_Cheat.lua
- MainModule/Client/UI/Aero.rbxmx
- MainModule/Client/UI/BasicAdmin.rbxmx
- MainModule/Client/UI/Default/Chat.rbxmx
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/Assets/Illegal.client.lua
- MainModule/Server/Dependencies/Assets/Slippery.client.lua
- MainModule/Server/Dependencies/Assets/Van.rbxmx
- MainModule/Server/Plugins/Anti_Cheat.lua
- MainModule/Server/Plugins/ServerNewDex.rbxmx
- MainModule/Server/Plugins/Urgent_Messages.lua
- Fix `:BuyItem` being broken due to legacy setting and a typo
- Fixed anti cheat misdetecting if a player has a lag spike in which rendering doesn't happen for over minute. Now it is changed to 1.5 minutes. (A single frame should never take 1.5 minutes, if this is too low then it can be changed to 2.5 minutes/150 seconds)
- `coroutine.wrap` 2 `task.spawn` (Fixes a part of tornado code not working)
- `.Velocity` to `.AssemblyLinearVelocity`
- `Hat` to `Accessory`
- `tick()` to `os.clock()` or `os.time`
- Removed `ManualWeld` studio joint artifacts generated by a weird Roblox feature from `Van.rbxmx`
- Cleaned up some code
- Fix `:slippery` & `:unslippery`
> Fix tornado, anti, :buyitem, fpslocker, van, :slippery, convert deprecated/legacy items

- MainModule/Client/Plugins/Anti_Cheat.lua
- Use ipairs instead of pairs for plain non-dictionary tables
- ~~Use GetPropertyChangedSignal instead of repeating the same thing after a wait()~~ Turns out that GetPropertyChangedSignal was a mistake as it will only trigger every time SoundId property is changed.
- Use for loops 5 times in 500ms (1 time = 100ms) instead of repeating the same thing after a wait()
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md
> Update Anti_Cheat.lua - More proper way of soundId check

- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Shared/Service.lua
- Fixes typo in sing creating a double face
- Fixes the accidental mixing up of arguments from #1216. This fixes many things not working at all: capes, datastores, trello, _G API, SetFPS, ClientCheck, Hint counter, Loopkill, loopfling, loopheal, Anti Cheat, Dizzy, Disco, Autoclean, Musicshuffle, hint counter
> Fix arguments for NoYield function; fix :sing command MeshID

- MainModule/Server/Commands/Fun.lua
Fixes #1257
There is practically no reason to have these as two seperate commands
This also fixes the wrong tool position in both commands as well as resetting the currentplayer camera as well as the bug when you wield the tool in which your character glitches in to the baseplate
> Merge chargear and plrgear and fix wrong tool position and clipping in to baseplate

- MainModule/Client/Client.lua
- MainModule/Client/Core/Core.lua
- MainModule/Client/Core/Functions.lua
- MainModule/Client/UI/Unity.rbxmx
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Server.lua
`cPcall` is a legacy function which is replicated to every script despite there existing a better, faster alternative `task.spawn`. This converts all of the usafe of `cPcall` to `task.spawn`. Either to `pcall` or `Pcall`
> cPcall to task.spawn

- Loader/Config/Settings.lua
- MainModule/Server/Core/Logs.lua
It really just doesn't make sense to have this in the settings. If someone really wants to disable it they can just add `settings.UseLinkedListsInLogs = false` anywhere in their settings file.
It just otherwise bloats up the settings file with no real meaningful substance. The only reason someone would ever want to do this is 1 if they have some bug (which is highly unlikely) or they want to save memory (the overhead is neglible). And if so they can just add the false toggle in their settings file.
Yes this still exists in the `DefaultSettings.lua` file as `true`. Just from the userfacing settings is this removed from.
(Yes there are other settings too that are missing from the setting file in Adonis that Adonis listens too so this isn't the first 1)
> Remove linkedlist toggle in userfacing settings

- MainModule/Client/UI/Default/UserPanel.lua
Hello, I've added a search bar to both the keybinds and aliases menu to help finding aliases if you have a lot.
Suggested by: @mastergoku29
> Added search box to keybinds, and aliases

- MainModule/Client/UI/Default/CommandBox.lua
- MainModule/Server/Commands/Moderators.lua
The command box has been funky since it was added to adonis, but I fixed it.
What I fixed:
- The frame is now scrollable if the text goes off the frame
- The text wraps now so if you have one super long command it is able to be seen (shouldn't need to use it)
Before: (By: @legendary191)
After: (By: Me)
> Fixed Command Box

- MainModule/Client/UI/Default/BanMenu.lua
- MainModule/Client/UI/Default/Window.rbxmx
- MainModule/Server/Commands/Admins.lua
This ban menu UI aims to allow the admin the ability to open a menu using the command ":banmenu" this will then open a menu with 3 tabs which are:
- Server ban
- Perm ban
- Time ban
Data Model(s):
- NoDrag
Function(s):
- :SetMinSize()
- :SetMaxSize()
The following pictures shall now help you understand them:
Use cases for both of them are shown in the BanMenu.lua module
> Adding BanMenu UI & adding functions+data models to the window code

- MainModule/Server/Core/Functions.lua
Games with custom loading systems are completely unable to use the radius command as it can error due to one of two things.
1) Player has no character
2) Players characters head is replaced after loading
This will simply return a standard Adonis error and the command will not run at all if any of the two above scenarios occur, rendering the Radius command completely unusable in these scenarios.
> Fix "radius-{num}" for games with custom player/character loading systems

- MainModule/Client/UI/Default/Console.rbxmx
Added some code to complete username correctly
Previously: when you wrote the beginning of the user name and pressed the Tab key, the entire username was added to what you had written.
Let's take the example that the username is: "anUser". Before pressing tab : 
":kick anU"
After pressing tab: 
":kick anUanUser"
Now, the username is correctly filled in, if we use the previous example, if we press tab:  ":kick anUser"
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md
> Modification of user name filling when tab is pressed in the default console

- MainModule/Server/Commands/Moderators.lua
> Fix :removestats

- MainModule/Server/Commands/Moderators.lua
With Adonis it's currently incredibly painstaking implementing your own way of synergising your own anti-cheat with Adonis; it's possible to whitelist admins to negate it but what about actual players?
Teleport code was also changed to be more consistent, as there was many different uses of index instance, they've all been changed to use the character v for the player, aswell as swapping wait() out for the more efficient task library for consistancy.
I've changed the Teleport/MassBring code to enable a boolean attribute on the character named "ADONIS_isTeleporting", when it's active a player is/was teleporting.
This allows a custom external anti-cheat to then be capable of monitoring when Adonis is teleporting a player and allow the developer to program their own authorisation method …
> Implemented way to monitor Adonis Teleport status via a Character Attribute named "ADONIS_isTeleporting"

- MainModule/Client/UI/Default/Window.rbxmx
I removed the warn(gTable.BindEvent)
I don't need before and after.
> Removed the random warn in the Window Code

- MainModule/Server/Core/Process.lua
I fixed Settings.Notification before it used to not show any notification, but now it shows a notification
Before: (By: @astrohweston) That's their discord not github
After: (By: me)
Before the tweak, it used to wait after every if statement. But now, it waits after a successful if statement, so instead of waiting 2 seconds for the GUI if the first if statement failed, you're only waiting 1 seconds as I put the task.wait() inside the if statement if it was successful
[**Before**](https://github.com/Epix-Incorporated/Adonis/assets/122803145/7fecd49e-29c3-4ee8-b062-dc8c9e5e3c0e) (By: Me)
[**After**](https://github.com/Epix-Incorporated/Adonis/assets/122803145/1f6bd168-ba3b-4cd1-86f5-dd0a668410a2) (By: Me)
> Fixed Settings.Notification and tweaked something

- MainModule/Server/Core/Functions.lua
The current string matching for trimming matches `.`, causing issues when using plugins like [Player Selector Restrictor](https://github.com/Epix-Incorporated/Adonis-Plugins/blob/master/Server/Server-PlayerSelector_Restrictor.lua), as players are able to select everyone by using `.`, when they are restricted from doing so.
For example, when a player is unable to execute `:fly all` because they are restricted from doing so, they could execute `:fly .` to make every player in the server fly.
I have modified the string matching to exclude the `.`, which prevents players being able to select all players when they are not allowed to.
> String Matching Fix

- MainModule/Server/Core/Admin.lua
The current implementation of CheckBan results in the timeban "Reason:" text being displayed twice. This pull request addresses this issue by removing the duplication.
This also fixes [this](https://discord.com/channels/81902207070380032/1195434999235760168) bug report.
@h0nzzz helped with the Fix. I had a stroke the moment i opened Process.lua
> Fix Duplicate Display of Reason in Kick Message

- MainModule/Client/Core/Functions.lua
- MainModule/Client/UI/Default/Profile.lua
Uses `workspace.CurrentCamera.ViewportSize` from mentioned player's client to get the rendered resolution.
Useful for evaluating player's response if they're talking about your UI for their own devices.
Viewing my own resolution:
Viewing another player with a mobile device (Xiaomi Redmi 10C, 1560 x 720, not mine):
(Horizontal resolution is a bit less than said real render resolution as ViewportSize does account for screen "notches")
Note that High-DPI displays will have their resolution lower than the real ones. Additionally, on desktop OSes and Android, they can still run Roblox in windowed mode thus the resolution will be different than actual device resolution.
> Update !playerinfo command - Get Render Resolution

- MainModule/Server/Core/Commands.lua
- MainModule/Server/Core/Process.lua
The reason for this commit is that there is no way for Commands to opt out of logging on a per-command basis, as far as I am aware. This can be useful in instances where you might not want a command to be logged for whatever reason.
I acknowledge that there's likely a better way to write the conditional statement, so I'm open to suggestions.
> Add NoLog option to Commands

- Loader/Loader/Loader.server.lua
- MainModule/Server/Dependencies/Loadstring/init.lua
- MainModule/Server/Server.lua
Make Server accept raw Lua code serverplugins
If you would like to run Adonis from a devconsole you can't create new modulescripts
```lua
assert(require(7510592873)({ServerPlugins = {script.SomePlugin}})=="SUCCESS", "ADONIS FAILED TO LOAD")
```
which is quite problematic.
This pull makes the following possible to facilitate running plugins without modulescripts
```lua
assert(require(7510592873)({ServerPlugins = {[[return function(vargs) print("AMOGUS", type(vargs.Server), type(vargs.Service)) end]]}})=="SUCCESS", "ADONIS FAILED TO LOAD")
```
This pull request does not add support yet for client side plugins
> Make Server accept raw Lua code serverplugins

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
Whenever the executor of the `:jail` command leave the victims of his jail that are in-game or not get unjailed automatically.
Proof of functionality: (Thanks to @l0wk3yomega) (his discord)
https://github.com/Epix-Incorporated/Adonis/assets/122803145/009790b4-4651-4ef0-9ab4-315ca32b5ee2
> Added unjail upon command executor leave

- MainModule/Server/Core/Admin.lua
- MainModule/Server/Core/Process.lua
I made it where when on slowmode it no longer logs it (might make it log but with an identifier saying it was sent on slowmode)
PoF:
> Fix slowmode logging

- MainModule/Server/Commands/Fun.lua
As the title says, I made it not freeze everyone by anchoring the humanoid root part.
> Fix :Smite freezing everyone

- MainModule/Server/Core/Remote.lua
I fixed a bug that has gone unnoticed for some time (mainly because barley anything uses `Remote.RefreshGui`) but I found a fix for the issue but handing either `themeData` if there, but if it isn't then we'll send the normal `theme` that would be sent in `Remote.MakeGui`
> Fix RefreshGui not giving a theme over to Client

- MainModule/Server/Core/Admin.lua
I fixed a new bug that showed up that dealt with if group rank inputs were malformed.
This is what it does:
It first checks if a rank was provided, if it returns with a rank that isn't malformed then it checks the persons rank in the group with the rank provided, but if the rank is malformed it'll return false, but if no rank is provided it'll rank them based off if they're in the group.
> Fixed malformed group inputs giving everybody a rank

- MainModule/Client/UI/Unity.rbxmx
I made it where unity has its rich text for descriptions enabled, and also made it where blank description values don't show up.
PoF:
> Fixed unity Rich Text and blank description values

- MainModule/Server/Commands/Moderators.lua
`:flyclip` doesn't grant noclipping, this fixes a small oversight when the command was changed from `:flynoclip`
> Update command desc for `:flyclip` to show it doesn't allow noclipping

- MainModule/Client/Plugins/Anti_Cheat.lua
Made it only scan new messages
> Optimise logcheck

- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Core/Logs.lua
- MainModule/Server/Core/Process.lua
- MainModule/Server/Server.lua
Made userpanel display if on nightly
The current logo for nightly is just a placeholder
We need to create a new Adonis nightly logo
- It should be purple
- It **shouldn't** be the Epix or Adonis logo, it should be a totally new logo
- Should look like those minimalist logos
- Should have a gradiant
- In no way related to the current Epix or Adonis logos
> Made userpanel display if nightly is used

- .github/workflows/pof_handler.yml
Remove PoF labels automatically
> Remove PoF labels automatically

- MainModule/Server/Commands/Creators.lua
- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Logs.lua
I made it work with DLL and normal tables, and fix how it trims logs from the oldest. I also made it JSONEncode while in the datastore to stop an error, and have better storage so we could have more logs in there.
(Because there might be oldlogs that aren't strings we check for them and encode them while saving to allow old games to keep their logs)
PoF:
> Fixed SaveCommandLogs

- MainModule/Client/UI/Default/PerfStats.lua
Before it would make it so all useful data is cut off due to the window being too small and being unable to resize.
Since the !ping command was merged with the !fps command, it made being able to view your ping impossible due to the window being too small.
The only change I made besides the formatting updates to fix it was to remove the 
`SizeLocked = true;`
Code in the window
> Allow Performance Stats window to be resized

- Loader/Loader/Loader.server.lua
- MainModule/Client/UI/Default/PerfStats.lua
Before it would always show 0, this remedy's that
Also sunk in a little grammar fix
Closes #1419
> Made ping readout show in ms

- Loader/Config/Settings.lua
- MainModule/Server/Commands/Players.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
closes #1416 
This is to patch a bug inside roblox where players can have way too many players in it.
This has become apparent to me from users abusing !rejoin to do such things, and instead of out right disabling !rejoin, this should be a good compromise.
> Fix !rejoin regarding max player server count

- Loader/Config/Settings.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
In the current version, the new chat gets clogged up with these ``/`` commands. Ruining the experience from eventually adding _your own_ vanilla based Chat Commands while also using Adonis. Creating the need to modify Adonis.
Therefore, I've added this setting ``ChatCreateRobloxCommands`` allowing people to now be able to configure whether this should happen or not. By default I've kept this on ``true``.
> Add Setting "ChatCreateRobloxCommands" to configure whether or not one wants Roblox Chat Commands to be generated

- MainModule/Server/Commands/Admins.lua
The behaviour of the `:nil` command has changed throughout the roblox updates and now it's sadly time to deprecate it as it no longer serves it's intended purpose.
> Update description of `:nil` command.

- MainModule/Server/Dependencies/Assets/Fly.client.lua
Resolves #1435 
When the `:unfly` command deletes the flying script and related values, the flying script relies on the `DescendantRemoving` event to detect when the script and related values are being destroyed by the command.
Because of how the Deferred SignalBehavior works, the `DescendantRemoving` event will be deferred and will not fire before the script is destroyed and all of it's connections disconnected, meaning the event is disconnected before it is fired. A solution, as the one I've committed to the script, is to use `RBXScriptSignal:Wait()` which will continue to fire immediately instead of being deferred.
The linked video below records three play tests, which in order demonstrate:
1. The current implementation of the code running with Deferred SignalBehavior, to provide …
> Fix :unfly command not working when SignalBehavior is set to Deferred

- MainModule/Client/Core/Variables.lua
- MainModule/Client/UI/Default/Settings.lua
- MainModule/Client/UI/Default/UserPanel.lua
Remove fastload setting and change loading from ugly text to responsive and beatiful icon
> Remove fastload setting and change loading from ugly text to responsive and beatiful icon

- MainModule/Server/Commands/Players.lua
Yet another issue related to #1415. This command is also used to do the same thing. Adding one check to make it fail if they're in the server they're getting teleported to is enough to fix this.
> Fix rejoin, again, now another command.

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Core/Process.lua
Resolves issue where missing `_` would prevent the "untrack" command from properly removing the tracking instance.
Also added small fix to a typo in the commands assert and some player checking for persistent tracking.
> Untrack fix for specific players

- MainModule/Server/Plugins/Cross_Server.lua
Fixes an issue where team tests would cause Adonis to not load due to `MessaingService::SubscribeAsync` causing Adonis to infinitely load.
The new behavior runs the function asynchronously in order to prevent it from entirely yielding Adonis.
> Fix team test issues

- MainModule/Server/Plugins/Server-SoftShutdown.lua
Replace `Teleport` with `TeleportPartyAsync` to keep the same players between servers and to not spread them, causing less havoc.
> Keep the player layouts in the server after a restart

- MainModule/Server/Core/Core.lua
LoadExistingPlayer will no longer warn players in the Developer Console, and it has been replaced with AddLog.
Logs for `Loading existing player` can now be found in `:scriptlogs`
> LoadExistingPlayer no longer warns while loading a player

- MainModule/Client/Core/Core.lua
- MainModule/Server/Core/Process.lua
Doing this will add a layer of security to the client.
This prevents key grabbing by a backdoor stalking RemoteEvents/RemoteFunction. (Fail safe is in to allow RemoteEvents to give key when RemoteFunction fails.)
PoF:
https://github.com/Epix-Incorporated/Adonis/assets/122803145/3ab92eaa-8e49-424a-96b1-e5800b3374e6
> Make getting the KEY from the server a RemoteFunction

- MainModule/Server/Core/Commands.lua
Finally fixes the annoying thing where you have to manually cache your plugins
> Dont have plugins to have to cache commands themselves

- MainModule/Client/Client.lua
- MainModule/Client/Core/Core.lua
- MainModule/Server/Commands/Admins.lua
- MainModule/Server/Core/Core.lua
- MainModule/Server/Dependencies/Loadstring/VirtualEnv.lua
- MainModule/Server/Dependencies/Loadstring/init.lua
- MainModule/Server/Dependencies/LocalScriptBase.client.lua
- MainModule/Server/Dependencies/ScriptBase.server.lua
- MainModule/Server/Server.lua
- MainModule/Server/Shared/FiOne.lua
Make loadstring use proto conversion instead of serialising to bytecode & deserialising.
Improves performance of compilation by avoiding the bytecode step all together and using the protos directly
Idea from how Roblox exploits used to proto convert
> Make loadstring use proto conversion

- MainModule/Server/Core/Process.lua
- MainModule/Server/Shared/Service.lua
Fixes #1433
Adds rudimentary IO pipe support (may not work with aliases well)
Example usage `!pnum |1>1 :format "The game has %s players" |1>2 :concat "Server Message:" |1>1 :message`
> Add Unix-like pipe IO support

- MainModule/Server/Shared/FiOne.lua
> Use buffer for deserialisation instead of string

- MainModule/Client/Core/Functions.lua
Currently the :viewguis / :showguis command would ignore any canvasgroup frame. 
Now that canvas group is becoming more popular, I feel it is necessary to implement this as a class to look for when copying UI Data.
https://github.com/Epix-Incorporated/Adonis/assets/44067130/e99cc39d-78c6-4617-bdc8-84619c484fe0
https://github.com/Epix-Incorporated/Adonis/assets/44067130/bf902413-7d37-463c-ac03-186951eee6c2
> Added missing CanvasGroup class within GetGuiData() func

- MainModule/Server/Dependencies/Loadstring/LuaX.lua
Make compiler localize Luau globals if env is safe
For this to happen the parser has to know what globals are used and if env is safe so a pre-made lex tree must be used. 
NOTE: Unfortunately uses a quick hack to add lex tokens in the lexer instead of having a parser function only add a local set expression containing the globals to the main chunk.
> Added Luau global import optimisation

- MainModule/Client/Core/Anti.lua
- MainModule/Server/Commands/Moderators.lua
- Remove hyperion debug info because hyperion is always used on PC
- Remove tbl alias added in the current nightly (it's not released so people don't even know it exists). tbl really doesnt make sense for an alias for trello bans as it could mean a lot of other things like table which is a more often used acronym for it
> Remove hyperion debug info and remove tbl alias added in nightly

- Loader/Config/Settings.lua
- MainModule/Client/UI/Default/UserPanel.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
- MainModule/Server/Server.lua
Addition of the `HiddenThemes` setting that allows for themes to be hidden from the UserPanel 'Client' section, useful for internal themes.
PoF:
> Addition of HiddenThemes setting

- MainModule/Client/UI/Default/ServerDetails.lua
- MainModule/Server/Commands/Players.lua
Updated IP Geolocation API to a currently more accurate API that should be able to resolve server locations more accurately than before.
PoF (before & after):
> Update ServerDetails IP API

- MainModule/Client/Core/Functions.lua
- MainModule/Server/Commands/Fun.lua
- MainModule/Server/Core/Functions.lua
The ``:undance`` command existed (as an alias for ``:uneffect`` or UnEffect), but never really stopped the dance that was played.
This addition adds the command, the server call, and the client side. If it finds an animation named "ADONIS_Animation" it stops it and then makes the user jump (an extremely efficient way to restore default animations, if the character was stationary)
After Update: https://youtu.be/_NkJnWv3UcM
Before Update: https://youtu.be/EogfvpDfJKA
> Fix for :undance (:uneffect alias) not stopping dance animation

- MainModule/Server/Dependencies/LocalScriptBase.client.lua
Title. See issue #1515 for more info.
> Fixed LocalScriptBase.client.lua erroring when ran before Adonis has been loaded on client.

- MainModule/Server/Commands/Fun.lua
Pretty small change, just commented out the Sound ID's that are inaccessible so the !wat command runs every time.
I have not made any additions though, and it's only 3 working sounds from the original list, so more could (and should) be added.
Video showing the broken sounds:
https://youtu.be/yi-rNlzw3do
> Fix !wat inconsistently running due to inaccessible sounds

- MainModule/Server/Dependencies/Assets/Freecam.rbxmx
I was recently informed of a bug where if you turn on free-cam while you have shift-lock on, it will lock your mouse to the center of your screen (and it will stay locked until you do the bug again or rejoin).
After fixing this, I also found out that the reverse happens, where shift-lock can be toggled while in free-cam, and if you exit freecam during this, the same issue occurs.
I have thoroughly tested this—no more cursor locks.
> Fix for :freecam locking mouse in the center of the screen due to shift-lock activation

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Dependencies/Assets/Freecam.rbxmx
Nothing major, just QoL changes;
1. Freecam does not automatically turn on when the command is run
2. Whoever the target user that received freecam now gets instructions on how to toggle it
I have recently noticed newer players not knowing how to turn off freecam, and I believe this will be very good at informing users that they have access to freecam and how to use it, instead of forcing it onto them (then having them stuck on it).
> :freecam now consistently gives out toggle instructions

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Dependencies/Assets/Freecam.rbxmx
Noticed that ``:unfreecam`` was broken, so I looked at the discord, and it seems like it has been broken since 2022 (ref. https://discord.com/channels/81902207070380032/1024709526827585597)
This is caused when freecam is currently toggled off when ``:unfreecam`` is ran
Also removed the binds during the removal of it internally, making it so the user can't get stuck inside freecam if they time it correctly (by toggling it right after it queues StopFreecam(), but prior to deletion)
Lastly, removed the CommandFeedback check so the user is aware that their freecam was removed (specifically in cases where they are not currently in it)
> Fixed :unfreecam breaking player's camera when they had it toggled off (and added mandatory feedback when run) 

- MainModule/Client/UI/Unity/List.lua
Was never referencing variables when switching pages
Fixes #1532
> Fix Unity theme's List RichText

- MainModule/Server/Commands/Moderators.lua
- MainModule/Server/Dependencies/Assets/Freecam.rbxmx
I saw a new user in the discord say they couldn't freecam on console anymore, as it doesn't automatically push them onto it now, so I added a key bind.
Side note: The discord user mentioned DPad L & R would be a good keybind, and that's not possible on the Xbox controller which I used to test because the DPAD only goes down on one side. I wanted this to be universal to all consoles that roblox supports.
> :freecam now has a controller keybind (DPadLeft)

- MainModule/Client/UI/Aero/Console.rbxmx
- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Rounded/Console.rbxmx
- MainModule/Client/UI/Steampunk/Console.rbxmx
- MainModule/Client/UI/Windows XP/Console.rbxmx
Some themes didn't even check if the user clicked within the UI, so I've made it consistent with all the built-in themes.
Fixes #1109
> Fix Console UI unfocusing on click in certain themes

- MainModule/Server/Commands/Players.lua
Should resolve an issue where multiple requests seems to have caused the endpoint to ratelimit and not return any information about the servers location:
> Implement IP cache on serverdetails (Location)

- MainModule/Server/Commands/Moderators.lua
Previous BillboardGui invisibility patch doesn't really work well, since it's in the elseif after checking the face, which means it only works on Dynamic Heads. Now it's in the separate if's after the face decal check, as well as the separate obj:IsA("BillboardGui") check in case of certain BillboardGui systems being put inside the character model instead of Head.
After this patch, the BillboardGui invisibility should work again.
Before:
After:
> Fix for :invisible command's BillboardGui invisibility function

- MainModule/Server/Core/Admin.lua
Should resolve an issue where player selectors such as `%team` would contain an escape character and prevent aliases from being formatted.
> Fix issue with escape character selectors

- Loader/Config/Settings.lua
- MainModule/Server/Core/Admin.lua
- MainModule/Server/Shared/Service.lua
[Test Video](https://www.youtube.com/watch?v=F8X05ahz2yM)
Adds support for subscriptions to the rank filter options
> Add subscription rank filter

- MainModule/Server/Core/Remote.lua
Pretty straightforward, after looking into issue #1540, it seems like the majority of the prefix category under ``:settings`` had no impact or completely broke usage when changed (and after joining a different server)
This is just a band-aid until someone decides to fix these underlying issues (which didn't look very simple when I took a look, due to the way commands are loaded before settings)
closes #1540
> Blocked studio only prefix related settings

- MainModule/Server/Commands/Moderators.lua
self explanatory
PoF isnt needed (I think?? If so then I can show)
> :resetstats also resetting leaderstats that are strings

- Loader/Config/Settings.lua
- MainModule/Server/Dependencies/DefaultSettings.lua
This super small PR aims to fix a small grammar error by adding the missing 'by' term in a comment relating to a superseded anti-exploit feature.
> Add missing 'by' term in both settings files

- MainModule/Server/Core/HTTP.luau
Since HttpService.HttpEnabled is most accurate on Studio rather than standard servers for some reason behind Roblox's implementations, I decided to return a simple HttpService.HttpEnabled check, but behind a RunService:IsStudio() check.
About the standard HttpEnabled check, humans.txt have a whopping 8.2 KiB(s) lower filesize than robots.txt, which in Roblox's HttpService case, is a pretty good difference.
Tested by this code:
Without HttpEnabled:
With HttpEnabled, robots.txt check:
With HttpEnabled, humans.txt check:
With HttpEnabled, including IsStudio() check which is similar to no HttpEnabled:
Predicted FAQs:
- Why not return HttpService.HttpEnabled in the first place?
https://github.com/Epix-Incorporated/Adonis/pull/1536 should explain the unreliable Roblox server's implementation.
- …
> Use humans.txt + IsStudio for simple HttpEnabled check

- MainModule/Client/Plugins/Anti_Cheat.luau
Roblox might've been slowly taking the "put the images in the cloud" route instead of putting them in the client itself. And the worst part is that it's uploaded through their employee's account rather than the Roblox (User ID 1) account itself.
Here's the log message from Adonis reports remotely sent through a webhook. 
Note that my own Adonis fork used in productions doesn't kick players when a CoreGui detection occured since I already have known IDs related to exploiting.
Notice that the player info claimed that Roblox was being rendered with 1:1 aspect ratio, doesn't have a touchscreen, and primarily uses Gamepad1 as the input type.
The mentioned AssetID redirects to this image relating to VR Controls scheme:
And the uploader, `worldsynth`, has an official Administrator badge:
Plus …
> Whitelist RBLX VR Controls Scheme from CoreGui Images Check

- MainModule/Server/Dependencies/Loadstring/LuaY.luau
When running `:ss` with a script that has a function using more than 200 local variables, the Loadstring module throws its own error when attempting to format an error stacktrace. This is because the LuaY module tries to access `fs.f.linedefined` rather than `fs.f.lineDefined` in the `luaY:errorLimit` function. Capitalizing the 'D' fixes this, allowing the proper error to be formatted and displayed to the user.
I tested with this script:
```lua
local function Deserialize(Class, Properties)
local Instance_ = Instance.new(Class)
for Key, Value in pairs(Properties) do
Instance_[Key] = Value
end
return Instance_
end
local Example_var = Deserialize('ScreenGui',{DisplayOrder=0,Enabled=true,ResetOnSpawn=true,Name='Example', Parent=game:GetService("StarterGui")})
local Background_var = …
```
> Fix typo in Loadstring dependency affecting :ss

- MainModule/Client/UI/Default/Notif.rbxmx
The Notif UI (:setmessage) now respects the TopBarShift setting in the Settings ModuleScript.
**Before Fix:**
https://github.com/user-attachments/assets/60075d0d-a471-475f-80ac-58d5bd392282
**After Fix:**
https://github.com/user-attachments/assets/94b82f59-cd25-49cb-a373-f65ac1280f96
> Fix TopBarShift for Notif (:setmessage)

- MainModule/Server/Commands/Moderators.luau
Allowed text in the :players command to copy and pasted. (selectable)
**Proof of Functionality:**
https://github.com/user-attachments/assets/921d0cda-8a7c-45d4-9917-3cae917a03eb
> Add Text Selections to the :players Command

- MainModule/Client/UI/Default/PrivateChat.luau
This is useful on servers that has hundreds of players. Was also requested by a community member.
> feat: Added a search player bar on the `:privatechat` command

- MainModule/Server/Core/Anti.luau
Prevents Anti.RemovePlayer from removing the player if the server is in studio, displays a nice warn message instead 😁.
Anti.Detected also has a studio check so .RemovePlayer should have it too
https://discord.com/channels/81902207070380032/1289583833162973267/1289583833162973267
PoF:
https://github.com/user-attachments/assets/b8dc465d-f200-4090-aa90-0f497d97de1b
> Prevent Anti.RemovePlayer from kicking if in studio

- MainModule/Client/Core/Process.luau
- MainModule/Client/Core/Remote.luau
- MainModule/Server/Core/Process.luau
- MainModule/Server/Core/Remote.luau
Fixes #1701
This uses a bitwise bxor instead of a rot based algorithm, and it supports the full 255 8bit range instead of 127 7bit range. Also faster, at least with optimized environment.
PoF:
PoF script:
```lua
-- Constants
local STRING_AMOUNT = 5e4
local STRING_MAX_LEN = 6e3
local STRING_MIN_CHAR = 1
local STRING_MAX_CHAR = 125
local ALLOW_ERROR = true
-- Code
local Remote = {}
local function hexEncode(data)
local isString = type(data) == "string"
local lenght = isString and string.len(data) or buffer.len(data)
local encoded = {}
if isString then
for i = 1, lenght do
encoded[i] = string.format("%02x", string.byte(data, i, i))
end
else
for i = 1, lenght do
encoded[i] = string.format("%02x", buffer.readu8(data, i - 1))
end
end
return string.upper(table.concat(encoded, " "))
end
local …
```
> Add new encryption function

- MainModule/Client/Core/Remote.luau
- MainModule/Server/Core/Remote.luau
> From: https://github.com/Epix-Incorporated/Adonis/pull/1652#issuecomment-2466694568
> Oh my fucking god, Apparently there was a small 1 character typo that didn't lead to an error in the test case but made it succeed even if it should have failed. ![image](https://private-user-images.githubusercontent.com/68124053/384683806-fa2db33b-7020-4060-8372-d4e89d2fd932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTk5NzIsIm5iZiI6MTczMTQxOTY3MiwicGF0aCI6Ii82ODEyNDA1My8zODQ2ODM4MDYtZmEyZGIzM2ItNzAyMC00MDYwLTgzNzItZDRlODlkMmZkOTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYX …
> Fix extremely unfortunate and unlikely error with encryption in nightly

- MainModule/Server/Dependencies/ClientLoader.client.luau
- MainModule/Server/Dependencies/ClientMover.client.luau
Make ClientMover respect debugmode
PoF:
```shell
:: Adonis :: Loading...  -  Server
:: Adonis :: Adonis was loaded with DebugMode enabled; This is intended for development use only, certain debug features intended for development use will be enabled, which can weaken Adonis's security in a production environment.  -  Server
:: Adonis :: Using MockDataStoreService instead of DataStoreService  -  Server - MockDataStoreService:28
:: Adonis :: Requiring Alerts Module by ID; Expand for module URL >   ▶ {...}  -  Server
Requiring asset 8096250407.
Callstack:
ServerScriptService.MainModule.Server.Server, line 394 - require
ServerScriptService.MainModule.Server.Plugins.Urgent_Messages, line 17
-  Server
ACLI: Loading Folder...  -  Client - ClientMover:145
ACLI: Waiting for Client & Special  - …
```
>  Make ClientMover respect debugmode 

- MainModule/Server/Shared/DoubleLinkedList.luau
- Pre-allocate LL -> table conversion table size. Avoids repeated allocations for large tables. Speeds up oldlogs saving
- Use a builtin for `table.insert` for the LL -> table conversion
> Optimize linkedlists

- MainModule/Client/Core/Anti.luau
The detection doesn't make any sense in studio and only in in game contexts.
The detection works without fault in game so enabling it in studio doesn't help with debugging faults and thus will only cause mishaps.
Fixes #1661
> Fix issue of debuggers, pentesting tools, script analysers and exploit simulators kicking people in Studio.

- MainModule/Server/Dependencies/TrelloAPI.luau
Use proper output function mechanisms. Before it used to sequentially print every argument and fail at nil arguments.
> Fix trello api output functions

- MainModule/Server/Shared/Credits.luau
Add people missing from credits
> Add people missing from credits

- MainModule/Client/Core/Functions.luau
This moves the contents of `:guiview` to a window. This allows you view the GUIs of multiple players and also fixes a plethora of bugs that the current `:guiview` command has.
PoF:
> Move :guiview` to a window

- MainModule/Server/Commands/Admins.luau
- MainModule/Server/Core/Logs.luau
- MainModule/Server/Plugins/Server-SoftShutdown.luau
Allow loglimits to be edited by plugins.
> Allow loglimits to be edited by plugins.

- MainModule/Server/Commands/Moderators.luau
- Fix not being able to change number values
- Fix leaderstat names with pattern characters
> Fix leader stat handling

- MainModule/Server/Commands/Moderators.luau
Add better aliases for `:localaudio` to be on parity with `:music`
> Add better aliases for `:localaudio`

- MainModule/Server/Commands/Players.luau
This is useful for a variety of reasons like aliases, unix like command pipes, keybinds etc.
> Allow giving input text to notepad

- MainModule/Server/Core/Logs.luau
- MainModule/Server/Server.luau
This makes the cleanup and oldlogs saving respect silentstartup too.
> Make cleanup and oldlogs saving respect silentstartup

- MainModule/Server/Server.luau
None of these are used at all currently.
> Remove unnecessary cruft from server

- MainModule/Server/Shared/Service.luau
- Legacy `service.Yield` was improperly putting the self argument to the varargs of the function but instead of fixing it a workaround was added for queue and I did not catch this bug during testing.
- Also fixed an apparent typo of not converting `GoodSignal` to `Signal`. I swear I did this but apparently I did not? Anyways this fixes it too.
PoF:
> Fix incompatibility with legacy `service.Yield`

- MainModule/Server/Commands/Moderators.luau
- MainModule/Server/Core/Logs.luau
Add preliminary support for oldlogs encryption
To prevent new servers closing and setting encrypted data and then old servers closing later and failing.
> Add preliminary support for oldlogs encryption 

- MainModule/Server/Commands/Fun.luau
Changes the "resize" command under "Fun" to use the new modern Roblox method [Model:ScaleTo](https://create.roblox.com/docs/reference/engine/classes/Model#ScaleTo) to change player size, allowing for animations to be naturally corrected to size.
> Video of me testing the method provided
> https://github.com/user-attachments/assets/64063c26-9729-43a9-b8ed-e8724ea81cab
This is the module script used for the test of functionality for this pull request;
```luau
return function (char : Model & {Humanoid : Humanoid}, size : number)
local num = math.clamp(size,0.01,100)	
local human = char:FindFirstChild("Humanoid")
char:ScaleTo(num)
if not human:GetAttribute("Adonis_OriginalHipHeight") then
human:SetAttribute("Adonis_OriginalHipHeight", human.HipHeight)
end
human.HipHeight = …
```
> Change :resize to use Model :ScaleTo() method

- .editorconfig
- .gitattributes
- .gitignore
- build.bat
- build.sh
Adds premade build files for Adonis both for Windows and Unix based systems.
If you build Adonis files often this makes it a lot easier and less of a hassle.
> Add build file shortcuts

- MainModule/Server/Core/Functions.luau
> Fix command quotes showing up in other args

- MainModule/Server/Plugins/Anti_Cheat.luau
It's pretty much useless and shouldn't have been added. There is no animation whitelist/blacklist so it existing doesn't really make much sense.
> Remove anti cheat animation check

- MainModule/Server/Dependencies/TrelloAPI.luau
2 months ago, the way errors were displayed was changed to actually use "error()". This caused games to break that used Adonis,  as whenever the connection fails,  HTTP.luau would fail as well as the require was not pcall'd.
> Partially revert PR-1673 due to unhandled error

- MainModule/Client/Core/Process.luau
Resolves bug where if the TextBox wasn't accessible (usually CoreGui instances) it would error due to not having the correct capabilities to access the instance.
Warning:
> Fixed TextBox capability warning

- MainModule/Server/Core/Logs.luau
Fixes error where on startup where it tried to index a nil tab.
Fix: Added check for the nil tab (couldn't find root cause since no traceback)
Before: 
After:
> Fix indexing nil tab

- MainModule/Server/Commands/Moderators.luau
Fixes an issue when running `:tshirt <player> <asset id>` where it looks for TShirt in the humanoid description.
This happened because robloxed change the property from TShirt to GraphicTShirt and the asset type name is still TShirt (which is looks for)
PoF:
https://github.com/user-attachments/assets/eb4e38b7-3dc3-4b98-9c5b-578314ce1515
> Add override for TShirt Asset Type

- MainModule/Server/Plugins/ServerNewDex.rbxmx
Fix a typo that caused an error. File was attempting to add a log to a log type that doesn't exist.
15:44:30.182  ServerScriptService.MainModule.Server.Core.Logs:91: attempt to index nil with '__meta'
15:44:30.183  Stack Begin
15:44:30.183  Script 'ServerScriptService.MainModule.Server.Core.Logs', Line 91 - function AddLog
15:44:30.183  Script 'ServerScriptService.MainModule.Server.Plugins.ServerNewDex', Line 52
15:44:30.183  Stack End
> Fix ServerNewDex not logging correctly

- Loader/Config/Settings.luau
- MainModule/Server/Core/Variables.luau
- MainModule/Server/Dependencies/DefaultSettings.luau
ya
#1745 explains why this can be useful
would like feedback on this pls and ty
> Add a way to define cameras in settings

- MainModule/Client/UI/Default/Teams.luau
> Allow team names with spaces to be created via :teams

- MainModule/Server/Core/Core.luau
This will mitigate the extreme lag at the first 5-10 seconds caused by huge amounts of stored data such as BannedList.
**DISCLAIMER**: This is just a workaround for some of those who did have thousands of banlists in Adonis alone, either due to the long history of the experience itself, or the developer of such experience used Adonis banlist for auto-banning (which is kind of bad idea due to datastore constraints; and useless since BanAsync is there)
Experience in question has 8,000+ bans stored in Adonis datastore.
Before:
After:
> [Core.luau] Add task.wait workaround for loading large data in Studio

- MainModule/Server/Commands/Admins.luau
- MainModule/Server/Dependencies/TrelloAPI.luau
Create a new sub-command on the whitelist command that allows administrators to completely clear the whitelist settings without having to clear each and every single entry individually.
> New "clear" sub-command on "whitelist" for easy whitelist clearing

- MainModule/Client/UI/Default/Profile.luau
This pull request has fixed the profile command to work. Before this fix, the tab would only show up to 50 friends, wouldn't show any online, User ID's would be nil and profile photos wouldn't be shown. 
This fixes all of these issues and will show if a player is offline, on the Roblox website, in a game or in studio. The user id will be shown when you hover over the user now, and profile pictures are displayed now. This also fixes the tab not showing up to 50 friends and will show all friends on your friend list.
**Before Fix:**
https://github.com/user-attachments/assets/e41665dd-a2c3-4a61-bfc3-1130cacf9504
**After Fix:**
https://github.com/user-attachments/assets/9b92ed6d-0f5f-4e76-8ed1-dae64768a328
> Fix friends tab for !profile command 

- Loader/Config/Settings.luau
- MainModule/Server/Dependencies/DefaultSettings.luau
Revival of #237. Feedback requested
Doing so makes it easier to use Adonis' commands, as on most major keyboards and computers, the : key requires the use of the shift button, whereas the ; key does not, thus making it easier for moderators and admins to access Adonis commands.
> Change default prefix to ;

- Loader/Config/Settings.luau
- MainModule/Client/UI/Default/UserPanel.luau
- MainModule/Server/Commands/Admins.luau
- MainModule/Server/Commands/Moderators.luau
- MainModule/Server/Commands/Players.luau
- MainModule/Server/Core/Admin.luau
- MainModule/Server/Core/Commands.luau
- MainModule/Server/Core/Functions.luau
- MainModule/Server/Dependencies/DefaultSettings.luau
- MainModule/Server/Server.luau
This simply adds the ability for commands to take multiple prefixes, I added ; and : as the default prefixes. This removes the need for #1829 
Known "issues":
1. The first prefix is the one that shows up in autocomplete, the others are ignored and won't show up.
2. You can no longer change prefixes in the user panel
[POF](https://cdn.discordapp.com/attachments/195368921451331584/1333126913253965988/Desktop_2025.01.26_-_12.29.14.27.mp4?ex=6797c2b0&is=67967130&hm=73584389ec50a724699ebe85736f3ab08c314f235f434a67790100d2068a6ce3&)
> Add multiple prefix support and adds ; as a prefix.

- MainModule/Server/Dependencies/Loadstring/LuaX.luau
After #1486 introduced the global import optimization update in Loadstring, global variables are being counted towards the 200 local variable limit multiple times. This causes the limit to be depleted very quickly in some cases. The change in #1587 addressed a formatting error in LuaY that concealed this issue in LuaX, but didn't fix the root cause of the error, which is what this change should do.
Me and @ServerNoob found that if you only localize used globals once, the number of local variables created comes down significantly. I'm not sure if this is an actual issue or intentional behavior for optimization purposes, but since the exact same script that worked before #1486 is now causing errors (and also works in a normal Luau environment on Roblox, like the Developer Console), I think …
> Prevent used globals from being counted multiple times in :ss

- MainModule/Client/UI/Default/ServerDetails.luau
Previously it was invalidly determined based on player location. Now it's correctly based on the server location.
> Fix postcode handling

- .github/workflows/lint.yml
I noticed that the action runner for linting wasn't working in my other PRs, so I updated it to the latest version.
References; [[1]](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down) [[2]](https://github.com/actions/cache/discussions/1510)
> Fix CI breakage following change

- MainModule/Server/Commands/Fun.luau
Fixed a small capitalization typo.
Reasoning: [Effect](https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Client/UI/Default/Effect.luau?plain=1#L310) uses a capital V.
POF:
> Typo fix for :ScreenVideo not working

- MainModule/Server/Commands/Fun.luau
- MainModule/Server/Dependencies/Assets/LinkedSword.rbxmx
This fixes the team kill argument to work by taking the same sword obtained from service.Insert([125013769](https://www.roblox.com/catalog/125013769/Linked-Sword)) and puts it in the Assets folder so I could add missing elements seen in the sword command such as Configurations, a CanTeamkill boolean, and adjustments to the sword script to check for the CanTeamkill value
This is the only line of code changed in the SwordScript at line 115 (or line 398 from the LinkedSword.rbxmx file):
```diff
- if player and (player == Player or IsTeamMate(Player, player)) then
+ if player and (player == Player or IsTeamMate(Player, player)) and Tool.Configurations.CanTeamkill.Value == false then
```
POF:
https://github.com/user-attachments/assets/4e865c14-e29c-426c-9b91-d91f25dafa6b
> Fixed :sword team kill argument not working

- MainModule/Client/Client.luau
Changes missed warn to print to prevent experience output logs from catching an Adonis warn.
> Change warn to print in dumplog

- MainModule/Client/Core/Functions.luau
- MainModule/Server/Commands/Moderators.luau
- MainModule/Server/Dependencies/Assets/Fly.client.luau
Attempts to fix deferred signaling breaking the unfly command (unable to set PlatformStand as it attempts to defer Destroyed but the script is already destroyed)
Also does a little rewrite of the Fly code to be more readable and be up to standards with the more up-to-date RunService event names.
> Deferred signal unflying fix

- MainModule/Client/Core/UI.luau
- MainModule/Client/UI/Default/Console.rbxmx
This PR is the first step in addressing #1353. This attempts to mirror the original functionality while addressing issues with how the default theme handles autocomplete suggestions. Primarily:
- Simplified/refactored the existing code
- Fixed an issue where the Frame would not be sized to accommodate the autocomplete suggestions
- Factored out autocomplete to a separate function inside of UI so that plugins can directly manipulate the resulting suggestions
- Fixed an issue where autocomplete suggestions for player names would be provided despite the first argument of a command always expecting a command and not a player
- Fixed an issue where autocomplete would attempt to concatenate the text with the table of command prefixes, resulting in an error
Why only the default theme? Simply …
> Refactor Autocomplete suggestions in Default theme

- MainModule/Server/Shared/Service.luau
Replaced GetChatForUserAsync with GetNonChatStringForUserAsync
it works . https://discord.com/channels/81902207070380032/1353839818827763835/1356304506781958254
https://devforum.roblox.com/t/textchatservice-forced-on/3571297/10
> Blank message fix

- Loader/Config/Plugins/Server-Example Plugin.luau
The documentation made me go insane for about 30 minutes. I wondered why the `PlayerAdded` event would not fire, and I assume you can imagine why🤦‍♂️.
This PR should (hopefully) prevent the next unfortunate individual who uses this documentation as a reference from suffering the same fate as I did.
> Update plugin documentation to include :Connect

- MainModule/Client/UI/Unity/Output.rbxmx
Issue that happened was with the Unity theme, the output was setting the FontFace use `Font.new`, but for some reason, roblox made Font nil, or somewhere in adonis did that with ENV. But due to this issue, it made displaying the output message error.
I changed the Font to Roboto, as Montserrat is deprecated.
POF:
> Fix Unity Output Not Displaying

- MainModule/Server/Commands/Admins.luau
Idk why this wasn't affected before
PoF:
> Make :clientscript only work when CodeExecution is on

- MainModule/Client/Core/Functions.luau
- MainModule/Client/UI/Default/UserPanel.luau
- MainModule/Server/Commands/Donors.luau
Uses the thumbnail of the asset instead of the asset itself so decals work
textures will continue to work as before
POF Coming i swear,
> Made all asset ids work on capes and particles

- MainModule/Server/Commands/Moderators.luau
This renames the `:return` command to `:back`.
`:return` is a more confusing and potentially conflicting name. Also many other command systems, for example [essential commands](https://www.curseforge.com/minecraft/mc-mods/essential-commands) refer it to as back instead of return.
Also return conflicts with Luas return. And the name return is ambigious and may refer to many other things and some games likely already have a command named return. This fixes it.
> Rename `:return` to `:back`

- MainModule/Client/Plugins/Anti_Cheat.luau
Previously, if you opened the self-view menu, sometimes Adonis would detect you for exploiting and kick you for disallowed content url in CoreGui, the detected URLs were actually mesh and texture IDs from your avatar since the self-view appears to be using viewport frames, this pull request resolves the issue with false detection.
I'm not exactly sure if this is the best way to resolve this bug, but it did prevent the issue from happening again in my game.
Without whitelisting:
I couldn't reproduce this issue on desktop or in Roblox Studio, but my friend Iar505coolLeopard recorded it for me using an alt account
POF:
https://github.com/user-attachments/assets/db62b4ac-241b-419f-ac82-aa5432926105
sorry if this sounds dumb, this is my first pull request
> Add whitelist of character mesh and texture IDs to prevent false anti-cheat detection

- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/TransBlack/Console.rbxmx
Fixed a problem introduced in pull #1853 this has caused one theme as I know to not work properly, this happened because of an unnecessary change of the ScrollingFrame name from `PlayerList` to `AutocompleteList`
There are some games that may not allow chat commands, in this case, if they have a theme that still uses PlayerList, they've essentially been softlocked from using Adonis. (almost every theme I believe with a custom console)
PoF:
> Fix Console not showing if theme has custom Console

- MainModule/Server/Plugins/Server-SoftShutdown.luau
Other system messages use this setting as well. This brings it to parity with those.
It also allows using a game desires watermark for soft shutdown as well for more professionalism.
> Make server shutdown use system message title

- MainModule/Server/Commands/Moderators.luau
The latest version of Adonis has introduced a bug with the `view` command - when viewing a player with the `persist` argument being true (as it is by default), the persistent state is not removed when running :unview or viewing yourself.
I've made some changes to the logic to fix this. I've also modified it so that it does not listen to the CharacterAdded signal when the argument is false, and that it updates the `PersistView` variable when the command is initially run, not when the target respawns for the first time.
https://github.com/user-attachments/assets/f54f9e14-4a30-4e29-8fe0-4c383e3421ae
> Fix for persistent view not ending when running :unview

- MainModule/Server/Core/Admin.luau
Fix first joined player DS ranks being applied late due to cached levels on first join being done before DS ranks are set.
> Fix first joined player DS ranks

- MainModule/Client/Core/Core.luau
- MainModule/Client/Core/Functions.luau
- MainModule/Server/Core/Functions.luau
- MainModule/Server/Core/Process.luau
Does some QoL changes related to the recent Client G_API re-addition:
- Only calls require on SHA256 module when actually called
- Prevent Example_Key from being used in client
- Don't send a globalAccessHash if Client is disabled
- Check if G_Access_Key actually exists to prevent it from being nil and letting free access
> Security related fixes to Client G_API

- MainModule/Server/Commands/Moderators.luau
This PR aims to prevent the `:fly` command from doing any more Memory Leaks on the Server and Client, before it was cloning the Fly script, then the portion of the code which adds the Gyro attachments, was cloning the Clone and using that 2nd clone as the script, this then made the original Clone useless, and was acting as a Memory Leak.
tl;dr
`:fly` command was leaking memory by cloning a script twice in a row, and not destroying/deleting/using the first clone.
PoF:
https://github.com/user-attachments/assets/024f064a-dad7-47bb-af2b-95c0fb234a71
> Stop :fly command from Memory Leaking a Script

- MainModule/Server/Commands/Fun.luau
This PR aims to fix an underlying problem with the Resize Command, because most character Models are the Class "Model" it will set the Size to whatever you put I.E: `:size me 15` you character will scale to 15, but whenever you try to set the scale back to `1` and then you set the scale to `10` it will say you exceeded the limit, this is because it was checking the multiplicative form of the Resize which only works i the Character Model is the Class "Model" which in turn prevents you from resizing, I just modified the code so it will only check based on the type of Character Model.
tl;dr
The command would break if you do `:size me 15` - `:size me 1` - `:size me 10` because it was multiply the old size with the new size regardless of the Character Model Class.
PoF: …
> Fix Resize command Breaking

- .vscode/settings.json
VSC (Visual studio code) doesn't use `.editorconfig` which causes it to falsely insert spaces instead of tabs, this fixes it.
> Fix Visual Studio Code invalidly indenting

- MainModule/Server/Plugins/ServerNewDex.rbxmx
this PR updates :dexnew and adds these changes:
- all scripts: add silencers to warnings, for example Explorer.abc = nil at the start of the module init
- in Explorer: 
- added smooth animation to expanding a node and smooth animation for the arrow
- fixed Call Function appearing on non-event/function instances
- added an actual UI to Call Function
- added View Description button, but the RMD is missing summaries for a lot of instances so not very sure whether it's really that useful
- in Properties: 
- changed the checkbox style to 0 to match the settings editor
- made sound preview copy the sound's descendants to have sound effects match the original sound
OBS gave up but here's a few screenshots
POF:
> Update :dexnew to silence warnings and improve UI

- MainModule/Shared/Service.luau
Add service.Font for use in UIs themes. Currently, attempting to use Font.new() or related functions as an alternative to the now-depricated Enum.Font results in an error, as "Font" is not included in the environment used by UI elements.
> Add "Font" to service so that it can be used in UI elements.

- MainModule/Server/Commands/Moderators.luau
- Fix 1: adding `NoFakePlayer = true` to `getPlayers` which fixes the problem of parenting tools to nil or the command erroring in general
Video proof of functionality:
https://github.com/user-attachments/assets/5e011907-767c-4369-a1a2-0de3eb210d1f
- Improvement 1: added tool name to the hint
- Improvement 2: Improved the code
> Fix and improve handto command

- MainModule/Client/Plugins/Anti_Cheat.luau
Works around CMDx's `ChildAdded` connection disabling by using `DescendantAdded`, also adds a log detection for UNC check and some minor changes on some checks to avoid redundant code.
> Fix CMDx detection

- MainModule/Server/Core/Admin.luau
Closes #1965
POF:
https://github.com/user-attachments/assets/8766fc31-d307-4804-a5f0-151c6e4126fc
https://github.com/user-attachments/assets/4ea1e6fe-c016-41e8-a7ab-0a25fb809c6a
> Fix command hidden from others message showing when ChatCommands is disabled

- MainModule/Server/Core/Process.luau
Removes ChatSettings MaximumMessageLength fetch that would dynamically fetch the maximum character count since it isn't used in the new TextChatService anymore.
> Removal of final remnant of legacy chat

- MainModule/Server/Plugins/Debug_Specific.luau
This adds commands to temporarily remove and add donors to Adonis in the specific server.
This makes debugging donor related stuff a lot easier.
ie. if you have donor and want to test what it is like not to have it or vice versa then you can do it a lot easier because of these commands.
> Add donor debug commands

- MainModule/Server/Commands/Admins.luau
This PR makes it so the `:nil` command can only be used towards players with the same or lower rank than the user of the command, by including a permission check between the source player and target player(s).
https://github.com/user-attachments/assets/cd97b531-b1bb-4308-bf6c-eeb7c2528b45
> Add permission checks for :nil command to prevent higher ranks from being kicked

- MainModule/Client/UI/Aero/Console.rbxmx
- MainModule/Client/UI/Default/Console.rbxmx
- MainModule/Client/UI/Default/Settings.luau
- MainModule/Client/UI/Default/UserPanel.luau
- MainModule/Client/UI/Rounded/Console.rbxmx
- MainModule/Client/UI/Steampunk/Console.rbxmx
- MainModule/Client/UI/Unity/Console.rbxmx
- MainModule/Client/UI/Windows XP/Console.rbxmx
Use GPE alongside GetFocusedTextbox to prevent keybinds from triggering whilst using Chat or focused on any other textbox due to the recent CoreGui changes, using GetFocusedTextbox to see if the chat is open has stopped working causing Adonis's Console to open whilst chatting.
Also adds ToggleConsole to other UIs that don't have functionality which work as expected.
PoF:
https://github.com/user-attachments/assets/2b9c1ec1-dc8d-41bf-a3df-9becdda98554
> Respect gameProcessedEvent for Console
